### ISSUE TITLE
Set correct Site hostname for default site during deployment

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#10]
It would be nice if we can set the correct hostname on the default `Site` during deployment on heroku, so that things like page previews work without having to manually alter the site settings (a 500 is thrown if you forget to do this).

See also the approach taken here for generating sample data for review apps: https://github.com/mozilla/foundation.mozilla.org/blob/master/network-api/networkapi/wagtailpages/factory/homepage.py

**Comment by patjouk** [comment]
Fixed by #33 :)
