### ISSUE TITLE
[https://give.thunderbird.net/] Footer tweaks

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/donate-wagtail#1018]
Implementation ticket for footer changes.

**Impacted sites:**
[Thunderbird donate site](https://give.thunderbird.net/)

**Changes:**
1. Organized items by alphabetical order
2. Add "Press Center" copy. Link for [Press Center here](https://foundation.mozilla.org/press-center/)

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/22157921/87987349-5eefd280-ca93-11ea-8974-7b7e6f842e46.png">

---

**🗒  Design -> Dev Handoff Checklist**
(Feel free to remove items that are not applicable.)

- [x] Design has been finalized
- [x] Link to original design ticket: [#4868](https://github.com/mozilla/foundation.mozilla.org/issues/4868)
- [x] Link to InVision: [link here](https://mozilla.invisionapp.com/share/PJXWEC7BU86#/425165977_Footers-Thunderbird)
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included

cc: @TheoChevalier - updates we will be doing to our English Footers

**Comment by taisdesouzalessa** [comment]
After talking to Abigail today, the changes from [ticket 4868 (from foundation.mozilla.org repo)](https://github.com/mozilla/foundation.mozilla.org/issues/4868) won't affect this page so I am reopening this ticket.

**Comment by benhohner** [comment]
@taisdesouzalessa is this still relevant?

**Comment by taisdesouzalessa** [comment]
The current footer is not updated according to the recommendations above so it is a task that still needs to be done by an engineer. It doesn't seem urgent, though.
