### ISSUE TITLE
Add privacy link to donate form

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate-wagtail#1053]
request came in from Abigail on legal team.  We need to add a link to our privacy policy on the donate form (all languages).

So, just under the payment buttons, we currently have text that says "Your payment details will be processed by Braintree, a PayPal company (for credit/debit cards) or PayPal, and a record of your donation will be stored by Mozilla,".

This change will add, immediately preceding that ^^ statement (same paragraph and font style/size)... "Mozilla is committed to your privacy; please read our [privacy policy here](https://www.mozilla.org/privacy/websites/)."

Linked text goes to https://www.mozilla.org/privacy/websites/ .

Thanks!

**Comment by cadecairos** [comment]
@WillatMozFdn is there a related change we want to make for the Thunderbird disclaimer text?

**Comment by WillatMozFdn** [comment]
Thanks @cadecairos , indeed there is.  Checked in with Abigail and here's what we would like it to say for Thunderbird:

> "Your payment details will be processed by [Braintree](url)
<https://www.braintreepayments.com/legal/braintree-privacy-policy>, a
PayPal company (for credit/debit cards) or [PayPal](url)
<https://www.paypal.com/us/webapps/mpp/ua/privacy-full>, and a record of
your donation will be stored by Thunderbird. Please read our [privacy
policy here](url) <https://www.mozilla.org/privacy/websites/>."

Does that make sense?

**Comment by cadecairos** [comment]
I think so - Just want to clarify that the new text for the MoFo form should _precede_ the processor details, and for Thunderbird it should follow after it?

**Comment by WillatMozFdn** [comment]
@cadecairos yes, precisely.  A bit unusual but that's what Abigail and I worked out as best.

(Just FYI, work is underway on a MZLA-Thunderbird privacy policy, and down the road we'll want to link to that, but for now, Mozilla's privacy policy is the one still in effect.)
