### ISSUE TITLE
[https://donate.mozilla.org] Footer: add copy for CC license + link to Press Center Page

### ISSUE THREAD

**Issue by taisdesouzalessa** [mozilla/donate-wagtail#1072]
Implementation ticket for footer changes.

**Impacted sites:**
[Donate site](https://donate.mozilla.org)

**Changes:**
1. Removed "License" copy
2. Added Cookies as we have in our other web properties. [Link here](https://www.mozilla.org/privacy/websites/#cookies)
3. Removed "Donate" link since this is the Donate page
4. Organized items by alphabetical order
5. Added "Press Center" copy. Link for [Press Center here](https://foundation.mozilla.org/press-center/)
6. Added "Most content available under a Creative Commons license." Link for [Creative Commons license page is here](https://foundation.mozilla.org/about/website-licensing/)

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/22157921/87986464-02d87e80-ca92-11ea-980b-49193481c0a3.png">

---

**🗒  Design -> Dev Handoff Checklist**
(Feel free to remove items that are not applicable.)

- [x] Design has been finalized
- [x] Link to original design ticket [#4868](https://github.com/mozilla/foundation.mozilla.org/issues/4868)
- [x] Link to InVision. [Link here](https://mozilla.invisionapp.com/share/PJXWEC7BU86#/425165974_Footers-Donate).
- [x] Design changes been merged into the master Sketch file
- [x] Desktop and mobile mockups are included

cc: @TheoChevalier - updates we will be doing to our English Footers

**Comment by benhohner** [comment]
@taisdesouzalessa is this still relevant?

**Comment by taisdesouzalessa** [comment]
Yes, the changes recommended above were not implemented in the live site yet.
