### ISSUE TITLE
Add/update stock donation info on donate website

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate-wagtail#1081]
We now (actually) have a solution in place to accept donations of stock through Northern Trust.  

So, a couple changes to the "Ways to Give" and Donate FAQ pages, as follows.  These changes should be localized across all languages (we can also accept gifts of securities that are traded on NON-U.S. markets).

- [x] 1. Ways to Give Page, https://donate.mozilla.org/ways-to-give/

New Section: goes after SEPA, but before “Check (via postal service)”

Header: Donation of Stock/Securities

Body text: The Mozilla Foundation is happy to accept your gift of publicly-traded stocks or bonds through our brokerage account at Northern Trust Securities.  Please contact Major Gift Officer Jesse Ward at jessew@mozillafoundation.org to initiate the process.

- [x] 2. FAQ Page, https://donate.mozilla.org/faq/

Question 15, “Do you accept donations of stocks or bonds?” 

Answer: Yes, we generally accept gifts of publicly traded stocks and bonds, and will consider other gifts of securities on a case-by-case basis. Please contact Jesse Ward at jessew@mozillafoundation.org for more information. (You should consult your tax adviser on the extent to which you may deduct charitable contributions of certain securities and the documentation you need in order to claim a deduction.)

**Comment by phildexter** [comment]
Can we get this one done ASAP please?

**Comment by Pomax** [comment]
@WillatMozFdn I assume these are only for dontate.moz, not tb?

**Comment by Pomax** [comment]
Also, the FAQ page is in the CMS, you have edit rights for those but I don't know how the new wagtail-localize system works, so that's something I'm going to have to defer to @TheoChevalier.

**Comment by WillatMozFdn** [comment]
@pomax that's correct.  Only MoFo can take stock donations.

**Comment by TheoChevalier** [comment]
For the FAQ part, @WillatMozFdn feel free to edit https://donate.mozilla.org/admin/pages/5/edit/ directly then ping me when you’re done and I will propagate the changes to all locales. Otherwise, I can take a stab at it tomorrow morning

**Comment by WillatMozFdn** [comment]
Great, thank you Theo @TheoChevalier , I'm on it!!

**Comment by TheoChevalier** [comment]
Translation is ongoing for both pages, this can safely be closed
