### ISSUE TITLE
give thunderbird broken

### ISSUE THREAD

**Issue by EdorianDark** [mozilla/donate-wagtail#1103]
### Describe the bug
While donating I came to an 500 server error.
### To Reproduce
1. go to https://give.thunderbird.net
2. choose an amount and visa
3. gave my details (here were some javascript errors about eval in the developer tools console)
4. after giving my mail adress I clicked on receave mails.
5. the 500 server error

### Expected behavior
not a server error

### Screenshots
![image](https://user-images.githubusercontent.com/5777938/90313741-3da5c900-df0f-11ea-9c70-8bdf10e50e15.png)

### Desktop (please complete the following information):
 - OS: Windows 10
 - Browser Firefox
 - Version 80, Developer 

### Why here and not on give
I reported it here, since on give.thunderbird.net there was no possibility to report bug.

**Comment by ryanleesipes** [comment]
Can verify that this is happening. It is when you are trying to sign up for the MailChimp newsletter. I'm not sure how to determine what the issue is here, perhaps we need a new API key?

**Comment by cadecairos** [comment]
I'm opening a Bugzilla bug to identify the correct post format for mailing list signups

**Comment by cadecairos** [comment]
The user-facing error has been handled, but the MailChimp request needs to be fixed.

**Comment by jamilasnell** [comment]
@tomusher would you be able to assist with fixing the mailchimp request?

**Comment by KalobTaulien** [comment]
This looks like it's been remedied already. The only variable it's looking for is the `POST_DONATE_NEWSLETTER_URL` environment variable. And it's being set in all the thunderbird sites (review apps, staging and production). 

If this fails on us again, we can always check Sentry for an error titled "Thunderbird newsletter POST failed". We have this chunk of code looking for OK responses from MailChimp: 

````python
if not res.ok:
    sentry_logger.error(
        'Thunderbird newsletter POST failed',
        extra={'status': res.status_code},
        exc_info=True
    )
