### ISSUE TITLE
Recurring donations missing campaign URL + site values passed to Kount

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate-wagtail#1140]
Just realized that when someone set up a recurring Foundation donation (and likely MZLA too), certain pieces of information are not being passed where they need to be.

1) Donation form URL is missing from Salesforce ... this is important for me to analyze the results from any particular fundraising campaign.  Example (note the empty donation form URL field at lower left): 
![image](https://user-images.githubusercontent.com/23637882/92590938-09ea6480-f26b-11ea-8149-a833f9e23c30.png)

(in salesforce here: https://mozillasalescloud.lightning.force.com/lightning/r/Opportunity/0064O00000nxlUTQAY/view )

2) possibly related, the "MOFO" vs. "TBIRD" tag is not being passed over to Kount for recurring transactions ... making it difficult to sort, and have worked by the appropriate donor care person, any suspect transactions.

**Comment by WillatMozFdn** [comment]
@cadecairos ... urgency update: two other pieces of information, device ID and IP address, are also not being passed to Kount.  This makes the transaction look VERY suspicious to Kount (loss of about 50-60 points on the Omniscore) and we erroneously blocked 5-10 otherwise-legitimate transactions yesterday.  (Which = loss of income from people willing to set up recurring donations, plus unneeded donor care cases to resolve.)

**Comment by cadecairos** [comment]
@WillatMozFdn Is this for the initial monthly donation or subsequent ones?

**Comment by cadecairos** [comment]
I can also confirm that the `donation_url` value is properly set in the message we send to Basket for processing into a Salesforce record.

**Comment by WillatMozFdn** [comment]
@cadecairos yes, this is for the initial monthly donation.  Correct, we wouldn't have (nor do we need) info on the follow-up transactions ... it's just the first one we care about.

**Comment by WillatMozFdn** [comment]
If we are sending donation_url correctly ... why is it missing from my donation above?  That one was a new monthly donation I set up yesterday morning.  Happy to set up another one if we need a test case....

**Comment by cadecairos** [comment]
>     1. possibly related, the "MOFO" vs. "TBIRD" tag is not being passed over to Kount for recurring transactions ... making it difficult to sort, and have worked by the appropriate donor care person, any suspect transactions.

Braintree's systems are in charge of processing recurring charges - I'm not sure how we'd get that custom field sent along. might be something to bring up with our support rep.

**Comment by cadecairos** [comment]
nooooooooooooot quite ready to call this fixed.

**Comment by WillatMozFdn** [comment]
sorry Chris, just got some time to come back to this today.  Will dive in a bit more first thing tomorrow, but ... overall we're not concerned with donations 2, 3, 4 etc. ... those won't be fraudulent and not having a URL on those in Salesforce is no biggie.  Really, it's just the first one we need to focus on here ... getting the URL on there in Salesforce so we can track campaign performance, and (this might be a Kount issue) carrying over the device ID and IP address from the initial (zero-dollar) check so that Kount doesn't dock them 50 points on the omniscore.

**Comment by cadecairos** [comment]
I've deployed a change that ensures all recurring donations, including the initial one, will have that donation URL.

I'm thinking the Kount issue is a Braintree/Kount problem, as I've observed it working (Kount fraud check) for adding a card to the vault, but not when the subscription charge is actually processed.

**Comment by phildexter** [comment]
Going to create a new ticket to capture the Kount issue with recurring transactions. The other 2 issues are closed here.
