### ISSUE TITLE
Kount missing information

### ISSUE THREAD

**Issue by cadecairos** [mozilla/donate-wagtail#1151]
ref: #1140 

We're not getting device data or custom tags passed to Kount for fraud checks on recurring transactions.

We should talk to Braintree about this, since recurring transactions aren't processed directly by our systems.

cc/ @WillatMozFdn

**Comment by jamilasnell** [comment]
Hi! @WillatMozFdn & @stephaniemcv Do either of you know who would be the right person to work on this issue? A person who is in charge of talking to Braintree?

**Comment by WillatMozFdn** [comment]
Hey @jamilasnell that's me, but can we put this project on the back burner for now?  We're able to manage things without this info being passed for the moment, and diving in on this will take more hours than I have right now in the run-up to giving Tuesday....

**Comment by jamilasnell** [comment]
No worries @WillatMozFdn! I shall ice-box it!

**Comment by jamilasnell** [comment]
This needs to be added into an upcoming sprint @benhohner

**Comment by KalobTaulien** [comment]
@WillatMozFdn Do you know if this is still relevant after the stuff that's happened the last few weeks? I'm wondering if this is something on the Kount-side or our codebase-side. Thoughts?

**Comment by WillatMozFdn** [comment]
This is NOT still relevant (we made some changes to Kount in the interim that mean we don't need this info any longer) and the ticket can be closed.
