### ISSUE TITLE
Image Pixelated on Donor Page

### ISSUE THREAD

**Issue by phildexter** [mozilla/donate-wagtail#1170]
@jamilasnell commented on [Thu Sep 24 2020](https://github.com/mozilla/foundation.mozilla.org/issues/5303)

### Describe the bug
Header image on donor page is pixelated. May be due to cropping of the image 

### To Reproduce
1. Go to https://donate.mozilla.org/en-US/guardiangiving/
2. Pixelated image is the header on the page![Screen Shot 2020-09-24 at 11.53.15 AM.png](https://images.zenhubusercontent.com/5f592fe47f30fa8d24d93d20/95712b91-a222-4005-8c25-246ed0d6de5a)

 - Browser FireFox/Safari

**Comment by phildexter** [comment]
Help text to help the user.

**Comment by taisdesouzalessa** [comment]
Image w/ filter applied here: https://drive.google.com/file/d/12YIOGXuSt4vRMlRsRb3l_VaWfKj0aPX9/view?usp=sharing

@mmmavis, please let me know if you need any adjustments. Tks!

**Comment by jamilasnell** [comment]
Also, here is the original image! https://assets.mofoprod.net/donate/images/fellows2019_ver2.original.jpg
