### ISSUE TITLE
Restore check donation information to donate website

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate-wagtail#1179]
**Describe the bug**
Our current donation website, last updated in the depths of the pandemic, does not provide information on how to send us a check.  We ARE now going into the office and processing checks (albeit less regularly than before) so this information should be re-posted, on both the Thunderbird and MoFo donate pages.

**To Reproduce**
1. Go to https://donate.mozilla.org/en-US/ways-to-give/#check or https://donate.mozilla.org/en-US/faq/ or https://give.thunderbird.net/en-US/ways-to-give/#check , and try to find instructions to send us a check.   You can't.

**Expected behavior**
Mailing address available for donors to send checks.

**Additional context**
A. On https://donate.mozilla.org/en-US/ways-to-give/#check ... please remove current three lines of text and replace with ...

**UPDATE October 2020:** The Mozilla Foundation is happy to accept your donation (made payable to "Mozilla Foundation") via check; however please note that processing and acknowledgment of your gift may be delayed by changes to our office procedures due to the COVID-19 pandemic. You can send checks to: 

Mozilla Foundation, attn: Donor Care
2 Harrison Street, Suite 175
San Francisco, CA 94105

Please include your email address on the memo line of your check to help us track and attribute your gift.

Please also note that the Mozilla Foundation can **only** accept checks in U.S. dollars drawn on a U.S. bank, and **cannot** accept contributions for MZLA/Thunderbird. (Contributions to MZLA/Thunderbird via check can be made by following [these instructions](https://give.thunderbird.net/en-US/ways-to-give/#check).)

B. on https://donate.mozilla.org/en-US/faq/ , fourth item down, delete the current two lines there, change headline to "Where do I send a check (updated October 2020), and replace with same verbage as in A. ^^ above.

C. On https://give.thunderbird.net/en-US/ways-to-give/#check , delete current three lines of text, and replace with:

**UPDATE October 2020:** MZLA/Thunderbird is happy to accept your donation (made payable to "MZLA Technologies") via check; however please note that processing and acknowledgment of your gift may be delayed by changes to our office procedures due to the COVID-19 pandemic. You can send checks to: 

Mozilla Foundation, attn: MZLA/Thunderbird Donor Care
2 Harrison Street, Suite 175
San Francisco, CA 94105

Please include your email address on the memo line of your check to help us track and attribute your gift.

Please also note that MZLA/Thunderbird can **only** accept checks in U.S. dollars drawn on a U.S. bank.

**Comment by mmmavis** [comment]
Hi @WillatMozFdn , I've updated the FAQ page on CMS (https://donate.mozilla.org/en-US/faq/). Fixes for Ways to Give pages are currently under PR review, and should be live in the next prod push.
