### ISSUE TITLE
Standardize default amounts and ordering for primary donation currencies

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate-wagtail#1181]
**Describe the bug**
Right now our defaults for ordering suggested donation amounts are high-to-low, but this actually goes counter to research I just learned about from the NextAfter NIO Summit.  Also, our suggested amounts vary quite considerably in the primary seven currencies that constitute the bulk of our donations.  So we'd like to standardize these.

**Expected behavior**
Consistent suggested donation amounts, ordered low to high, in primary seven currencies.

**Additional context**
For the following seven currencies ...

USD
AUD
CAD
CHF
EUR
GBP
NZD

... we would like to order suggested donation amounts from low to high, and use the following values as suggested amounts:

One-time: 10, 20, 30, 60
Recurring: 5, 10, 15, 20

Thank you.

**Comment by phildexter** [comment]
Hi @WillatMozFdn  - should the default change also? Also should we keep the defaults on the numbers they are right now? (e.g. for UK it defaults to £5. However, £5 will move position on the page when we make this change. Is that ok?

**Comment by WillatMozFdn** [comment]
yes, default amounts displayed should change for all seven of those currencies, to the values specified (10,20,30,60 for one-timers, and 5,10,15,20 for recurrings).  Let's keep the suggested (i.e. pre-highlighted) option as the second-lowest (20 for one-time, and 10 for recurrings).  I recognize that this is a big jump up for GBP, which is the highest value currency we accept ... but as we come into the end of the year, people are more generous & willing to give more ... and also, we would like to discourage £5 (and $5, etc.) donations, or at least make it a tiny bit more difficult; a lot of fraudsters give 5 (and 3) and making that number NOT one of the suggested options will help us some on the anti-fraud front as well.

**Comment by WillatMozFdn** [comment]
This came from Chris shortly before he left, hopefully of use.  Seems like it's just a matter of editing this file and changing some values in the 'presets' section for each currency ... 

> Yeah I think the defaults are committed to the repo
> 
> (on a per-currency basis)
> 
> https://github.com/mozilla/donate-wagtail/blob/e3762bb5b0e7be8b7bda2a896620b165c46ea373/donate/payments/constants.py#L20-L458

**Comment by jamilasnell** [comment]
@WillatMozFdn is this still relevant? If so, what is the deadline on this action as we would like to start planning on tackling this. Thank you!

**Comment by phildexter** [comment]
Hi @jamilasnell, this one is still relevant and needed, so planning for it soon would be great.

**Comment by WillatMozFdn** [comment]
agreed with Phil here, @jamilasnell  -- this one's active and we'd like to get it done soon.

**Comment by jamilasnell** [comment]
@KalobTaulien & @Pomax let's discuss this in Monday's stand!

**Comment by Pomax** [comment]
this is probably easiest to solve by explicitly sorting in https://github.com/mozilla/donate-wagtail/blob/2e012721a3c0e4d5bd29289015c00aa6ea62e6a5/donate/core/models.py#L77-L112

**Comment by Pomax** [comment]
@WillatMozFdn should we sort low-to-high in all instances or are there languages where research showed we want to keep high-to-low for those?

**Comment by WillatMozFdn** [comment]
@pomax please do sort low-to-high in all instances.  The research I saw from NextAfter was EN-based, but no reason to believe that's not true in other languages as well.  Thanks!

**Comment by WillatMozFdn** [comment]
Re-opening this one.  The default amounts & ordering seem to be unchanged on our default page of https://donate.mozilla.org ... can anyone fix this please?  @KalobTaulien @jamilasnell

**Comment by Pomax** [comment]
It got merged, let me have a look at whether staging got promoted

**Comment by Pomax** [comment]
prod push finished.
