### ISSUE TITLE
Update links in navigation bar

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#1226]
Just noticed the navigation bar on donate is not following the one on the Foundation site any more, we should probably update that.

@kristinashu any concern if I update the current one to match the Foundation site?
Also cc @WillatMozFdn I assume having the What We Do / What We Fund pages up here won’t hurt ;)

Current:
![Screenshot_2020-11-16 Donate now Donate to Mozilla](https://user-images.githubusercontent.com/1294206/99262220-9be78e00-2815-11eb-9132-1da7ec3e565f.png)

Foundation site:
![Screenshot_2020-11-16 Fellow Research AI Systems at Borders Threaten Human Rights](https://user-images.githubusercontent.com/1294206/99262381-d05b4a00-2815-11eb-9bb2-a6ba4698fad2.png)

**Comment by kristinashu** [comment]
Good point Theo! Yes, please match the main foundation site's nav.
