### ISSUE TITLE
Detail page

### ISSUE THREAD

**Issue by nicklee** [mozilla/donate-wagtail#13]
**Design / Wireframe:**

Desktop: https://redpen.io/jc07fc459ff5f3fe81
Tablet: https://redpen.io/gpa264abeea7f4c799
Mobile: https://redpen.io/ykdc92900c06af901c

**Components that form this template:**

- [x] Detail form
- [x] Legal text

**Comment by nicklee** [comment]
Designs:

Desktop: https://redpen.io/skc2914b634e141270
Tablet: https://redpen.io/gpa264abeea7f4c799
Mobile: https://redpen.io/pk3fa92bc99a0ddc32

**Comment by nicklee** [comment]
MR here https://github.com/mozilla/donate-wagtail/pull/90

**Comment by beccaklam** [comment]
Sorry @philwakefield not sure exactly what you need from me here?

**Comment by philwakefield** [comment]
What should the user see and do when they click 'change amount'. This is currently un-styled in above link and assumes the right functionality.

**Comment by beccaklam** [comment]
Example of change amounts dialogue: https://redpen.io/ju45b724a9d5bd3cfe
<img width="337" alt="Screen Shot 2019-07-25 at 4 16 01 PM" src="https://user-images.githubusercontent.com/20977376/61905645-8ac78f00-aef7-11e9-81d9-62d68c55a63f.png">

**Comment by nicklee** [comment]
Thanks! We've just implemented this, shall post a staging link once it's all merged in.

**Comment by nicklee** [comment]
This is all done, only outstanding item i'm aware of is outputting a "per month" value to the change amount area when the user is doing a monthly donation. For example "You are donating $ 17 per month", is this something you're able to do @solarissmoke ?

**Comment by solarissmoke** [comment]
Yep - see https://github.com/mozilla/donate-wagtail/pull/133
