### ISSUE TITLE
Research Spike: Connect SQS to Cinchy 

### ISSUE THREAD

**Issue by benhohner** [mozilla/donate-wagtail#1368]
We need to send certain donation and newsletter subscription event data to Cinchy.com our new data warehouse (will get go/nogo by Wed, March 31)

- [ ] investigate how donate, fo'mo petitions, Amazon SQS, basket, braintree, and Salesforce are connected (ask ben for code references)
- [ ] Wait for confirmation on Wed, March 31 about whether we need to create a AWS lambda function to post to Cinchy API or connect to the Cinchy connector

**Comment by jamilasnell** [comment]
All of this work is pretty much done. There is a ticket made for the work that is left to be done.
