### ISSUE TITLE
Better handling of Paypal failures

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#137]
Our currently handling of Paypal failures is to render a page with "Something went wrong! Please try again later", which isn't particularly helpful to the user. 

I am not sure what the best UX here is, but I think we should probably send the user back to the landing page and display an error message there.

**Comment by solarissmoke** [comment]
Passing this to @beccaklam who is going to put together a design for this error message.

**Comment by beccaklam** [comment]
Designs for PayPal Error Message updated in this redpen: https://redpen.io/p/qf140664ca9fa398bb

@nicklee I also changed the error messaging on the details page. I decided error messages that were about an overall process might be better in a call-out box of sorts:

**PayPal Error**

![Screen Shot 2019-08-07 at 10 16 16 AM](https://user-images.githubusercontent.com/20977376/62630210-80949000-b8fc-11e9-90a1-85f3eb71d85b.png)

**Details Page Error**

![Screen Shot 2019-08-07 at 10 16 01 AM](https://user-images.githubusercontent.com/20977376/62630211-80949000-b8fc-11e9-9bfa-9f67f75ae862.png)

**Comment by alanmoo** [comment]
@solarissmoke I see the project status- can this be closed?

**Comment by solarissmoke** [comment]
Yep! There is some styling work required but I think there's a separate ticket to track that.
