### ISSUE TITLE
Create IAM role for SQS prod

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/donate-wagtail#1393]
Ensure we're ready to switch over to prod in May, make sure the SQS credentials are set up for prod, and coordinate a launch (push to prod of ) with other MoCo and Cinchy teams.

**Comment by benhohner** [comment]
Create #1393 for follow up

**Comment by jamilasnell** [comment]
Closing this as Tom has done this already. The credentials are in the Cinchy vault in One Password.
