### ISSUE TITLE
Consider adding JavaScript validation to the second donate page. 

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/donate-wagtail#1395]
On the second page when filling out your personal information, if the email address doesn't validate it refreshes the page and loses credit card info. 

We shouldnt store the credit card info, but we can add JavaScript validation to the page so it doesn't refresh and the user doesn't need to re-enter their information. 

Having users re-enter their information, especially a credit card number which isn't memorized, could lead to donation dropoffs. 

We should look into adding JavaScript form validation before Django form validation kicks in for a better user experience. 

Steps to reproduce: 
1. Go to: https://donate.mozilla.org/en-CA/card/single/?source_page_id=415&currency=cad&amount=20
2. Fill out fake data, but don't use a real email address. Use `test` with no `@` symbol in it. 
3. Submit the form. 
4. Page should refresh with missing data causing the user to re-enter everything.

**Comment by kristinashu** [comment]
The update Kalob is suggesting sounds amazing! I f-ing hate it when that happens. 

Yup, as long as it doesn't introduce any new styles then it sounds good from the design perspective.
