### ISSUE TITLE
Update Thunderbird Help Text

### ISSUE THREAD

**Issue by benhohner** [mozilla/donate-wagtail#1398]
Update help text in Thunderbird

https://github.com/mozilla/donate-wagtail/blob/1c3c0a24731fd0e5395b03852d92ab8cb67ac8b1/donate/templates/pages/core/contributor_support_page_master.html

- [x] @kristinashu approve final copy
- [ ] update copy (see below for copy)

**Comment by kristinashu** [comment]
I've mocked this up [here](https://redpen.io/zfb16e76c6547000b1). Just waiting for final approval on copy.

![Thunderbird-Donor-Help](https://user-images.githubusercontent.com/1068783/114944769-0caec880-9dfd-11eb-9c0b-8aa0628c7b1f.png)

**Comment by kristinashu** [comment]
@TheoChevalier Stephanie Lowry [requested](https://airtable.com/tbljPmOCkK9JShaTS/viwpFvt3FxiVannif/recmYt1DKSxYNRL5t?blocks=hide) some copy updates. Looks like the original copy was localized so would you please be able to gather translated text for the new copy?

**Comment by TheoChevalier** [comment]
Hey @kristinashu, I can get translations going as soon as the code changes are merged in master (everything is automated)

**Comment by TheoChevalier** [comment]
For the title, since it’s stored in Wagtail, I’ve updated it to "Donor Help" myself and synced the pages to get the translation started for this string.

**Comment by kristinashu** [comment]
Awesome, thank you Theo! @benhohner this is now ready for implementation.

**Comment by benhohner** [comment]
@kristinashu thanks, will likely go out next Sprint!

**Comment by KalobTaulien** [comment]
All done! One thing I was unsure of though was if the new text should only be applicable on the thunderbird website or on both thunderbird _and_ the main donate site. It's one code base for both. Currently, the text will show up on both websites. I can adjust that so it only shows up on thunderbird though.

**Comment by kristinashu** [comment]
It should only be for the Thunderbird page. Does the main site even have this contact form? I only see a mailto link on donate.mozilla.org

**Comment by benhohner** [comment]
@kristinashu We're copying the Thunderbird form to Donate at @stephaniemcv's request because the email address is getting spammed. So I think it's a valid question, do we want similar copy for the Donate site as we have on Thunderbird or do we want a different message?

**Comment by kristinashu** [comment]
Ah ok. What type of spam is it getting? If it's all Thunderbird related then it could be the same copy but if it's Firefox or something else then it should be different.

**Comment by stephaniemcv** [comment]
donate@mozilla.org is an old email address and at this point it's getting all the fun traditional spam - single lads and ladies looking for love, medicinal offers, money schemes etc. This is why we want to switch from MoFo donors emailing donate@ to create a help case in Salesforce to submitting a form on a webpage to create a case. So the content on this second form should be tweaked to reflect that if you're a MoFo donor, fill out this form to open a help case.

**Comment by kristinashu** [comment]
Ok that makes sense Steph, thanks! I've opened a new ticket here https://github.com/mozilla/donate-wagtail/issues/1425. Can you please review it and make sure that's what you have in mind?
