### ISSUE TITLE
Global header/footer

### ISSUE THREAD

**Issue by nicklee** [mozilla/donate-wagtail#14]
**Design / Wireframe:**

Desktop: https://redpen.io/qmb0c00a7348799ffe
Tablet: https://redpen.io/ng6b764da5350b6e79
Mobile: https://redpen.io/jtc87960cd6f960231

Notes: Header code can be taken from existing site's repo, as it's unchanged https://donate.mozilla.org/en-US/ . Footer TBC

**Comment by nicklee** [comment]
Initial setup for this has been included here:
https://github.com/mozilla/donate-wagtail/pull/32

It isn't currently clear if the footer will be the same as the current site, but have made the assumption that it will be.

Still need to work on header navigation once the nav has been built in the BE, but this can be tackled later on.

**Comment by alanmoo** [comment]
Reasonable assumption on the footer; if it does vary, it very likely won't be significant.

**Comment by philw-torchbox** [comment]
Blocked by decision on multilingual and final design

**Comment by nicklee** [comment]
As per: https://torchbox.slack.com/archives/CKG36UDCG/p1562832842197100

We're going to hardcode the navigation and it'll only be avaliable in English (as per the current site). So the burger menu should be hidden if the language isn't English.

**Comment by nicklee** [comment]
Navigation has now been hardcoded in, this is in the master branch. We'll have to handle the menu only showing for English languages at a later date when the BE is done.

**Comment by nicklee** [comment]
Header footer and links need to be updated to `{% trans "Example" %}` allowing us to localise them if needed

**Comment by nicklee** [comment]
Updated with translations, and to look like the designs. Only part left to address is the email newsletter component that sits within the footer. I did some rough base styling for this yesterday but understand that this is being developed on another of Mozilla's sites so we can potentially just port it over, with this in mind I haven't spent time refining what's there.

Soo we should be good to close this issue once it's been reviewed.

**Comment by alanmoo** [comment]
@nicklee, I think the newsletter signup is as close as it's going to get in terms of re-usability, given the different CSS being used across donate and our other sites. I'd say grab the markup and appearance from the footer on [the Foundation site](https://foundation.mozilla.org/en/), but make the signup action itself hit the Basket Newsletter endpoint with a newsletter of `mozilla-foundation`. [This file](https://github.com/mozilla/foundation.mozilla.org/blob/master/source/js/basket-signup.js) may be useful, and [here](https://basket.readthedocs.io/newsletter_api.html#news-subscribe) is the relevant Basket documentation.
