### ISSUE TITLE
Currency amounts internationalization

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#140]
Not sure if this is already scoped/planned as part of another ticket, so filing it just to make sure.

Amounts + currency strings everywhere on the website will need to be formatted using `Intl.NumberFormat` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat

This API will handle the currency symbol formatting, but also convert numbers to the appropriate script and pick separators (decimal, thousands, etc).

Example in Arabic, where numbers are converted to the Arabic script
![image](https://user-images.githubusercontent.com/1294206/62238860-b81aae00-b3cb-11e9-8c51-4dbfc1b9d697.png)

I think the current website uses a npm package, but that package relies on this API ultimately (which is definitely the way to go)

This API would also solve #93 (commented in there with the relevant example + method)

**Comment by TheoChevalier** [comment]
@solarissmoke Thanks for the PR! I had a look on staging, the JS part seem to work great, but I think there are issues with moneyed (or I didn’t test correctly)

With this query for instance, paying in KRW from the French page, 
https://donate-wagtail.mofostaging.net/fr/card/single/?source_page_id=3&currency=krw&amount=22320
I’m getting `₩22,320` while I should see `22 320 ₩` (which is what you get when accessing https://donate-wagtail.mofostaging.net/fr/ and switching currency to KRW)

Side question, what’s moneyed’s source of data? It seem pretty much homemade, no?
If that helps, Babel seem to provide similar features, and be regularly updated to include latest CLDR data http://babel.pocoo.org/en/latest/api/numbers.html

**Comment by TheoChevalier** [comment]
Ah, just noticed you filed #163 a while ago, this seem to be the issue I’m hitting

**Comment by solarissmoke** [comment]
Hey @TheoChevalier 

> Ah, just noticed you filed #163 a while ago, this seem to be the issue I’m hitting

No, that's a different issue to do with overriding the suggested donation _amounts_. The point you have raised is separate. I think you're quite right that babel is a better choice here than moneyed, and will be very easy to swap out. I think that will solve the issue and will let you know once done.

**Comment by solarissmoke** [comment]
I think this is all working as expected now, so closing this issue - so that we can track any edge cases on new tickets.
