### ISSUE TITLE
Create a copy of the Thunderbird Help form for Donate

### ISSUE THREAD

**Issue by benhohner** [mozilla/donate-wagtail#1402]
We need to duplicate the support form from Thunderbird into Donate.
- [ ] Get form ID from @stephaniemcv 
- [ ] Duplicate code

**Comment by Pomax** [comment]
Note that this template already exists, as https://github.com/mozilla/donate-wagtail/tree/master/donate/templates/pages/core/contributor_support_page_master.html, with the TB-specific override found in https://github.com/mozilla/donate-wagtail/tree/master/donate/thunderbird/templates/pages/core/contributor_support_page.html

**Comment by TheoChevalier** [comment]
Closing this ticket in favor of #1425 which has additional steps to complete this work
