### ISSUE TITLE
[Thunderbird] Audit environment vars in heroku to see which are being used and which are not. 

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/donate-wagtail#1405]
Ive noticed we're getting into higher numbers of environment variables in the donate stack. 

I think it would be a good idea to audit the env vars by checking which ones are used in the source code and removing unused variables. 

We may want to consider this for thunderbird and foundation as well. Along with possibly documenting what they are being used for.

**Comment by danielfmiranda** [comment]
Tagging @tomusher so he can give the variables a look as well

**Comment by danielfmiranda** [comment]
Closing this ticket as we have created #1440 as a follow up ticket
