### ISSUE TITLE
Research: Update email-sending during testing

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/donate-wagtail#1407]
At the moment, we have a env var called "is_testing" in continuous-integration.yml which is used to make the test suite skip sending a donation email while testing. 

While this works at the moment, we believe that there is a better way to implement this. Please research to see if there is a way we can keep the test suite from sending email receipts without the need of an env var

**Comment by benhohner** [comment]
@danielfmiranda can you ping @pomax to get his advice on this?
