### ISSUE TITLE
Research the script that was written for Stripe to Braintree migration

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/donate-wagtail#1417]
We need to find the old script that migrated subscriptions from Stripe to Braintree, and figure out how it works because we have subscribers that need to be migrated still.

Background: In 2019 there was a mass migration of donors from Stripe to Braintree, as Braintree supports more payment methods. The migration was mostly (?) successful, but certain imports failed. We need to finish migrating the remaining donors into Braintree.

Stripe can export user data (including credit card info) and through a cryptographically secure process, transfer the user data to Braintree. The only caviat is that subscription data does not get transferred in the process. The script, theoretically should:
1. Find all users with active subscriptions on Stripe
2. Create the exact same subscriptions in Braintree

Look into donate.payments.tasks.MigrateStripeSubscription

- [x] Report location of script
- [ ] Write a testing plan for how to verify the script works

**Comment by Pomax** [comment]
@cadecairos was gracious enough to fill me in on some of the details:

> iirc, when stripe did their behind the scenes “pci compliant” transfer of payment and customer data to Braintree the identifier for the cards was supposed to be identical across both platforms. When we migrated with the code I wrote we ran into some number of cases where the id didn’t match (potentially a data formatting issue since the data was cab formatted) there was also a problem with MasterCards issued I Europe, and cards that expired in the time between export and migration (edited)
> Last convo I had with Will or Steph about it seemed to point to manually trying to recoup those recurring donations

So even if https://github.com/mozilla/donate-wagtail/blob/master/donate/payments/tasks.py#L466-L532 runs as a "rolling migration" as it were, the fact that we have no proper `id` match means this is probably still a manual task, and I don't even know if this is something we can even do (because I don't know if there's any way for us to match Stripe ids to BT ids without access to PII that lets us reconstruct the relation)

**Comment by benhohner** [comment]
Note: need to verify if Braintree accepts Amex cards
See: https://sentry.prod.mozaws.net/share/issue/0b8b3acfc28a4d74b10e3f1107ac27cb/

**Comment by jamilasnell** [comment]
Move the outcome of this into the other ticket (other ticket # is known to @benhohner)
