### ISSUE TITLE
Document ENV Variables 

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/donate-wagtail#1419]
Document all of the new and existing env variables for the application.
Please include the default value, and the possible choices for the variable.

**Comment by benhohner** [comment]
@to look at script
Look through flake8 to see if there's a rule we can enable?

**Comment by benhohner** [comment]
@Pomax 
Pomax to look at script
Look through flake8 to see if there's a rule we can enable?

**Comment by danielfmiranda** [comment]
Please see this spreadsheet to see the results of the audit: https://docs.google.com/spreadsheets/d/1uJoOH1eqf8rPo9MdOaV_ozZ8thdlCWpZoKTOvu8yrmM/edit?usp=sharing 

Let me know if there are any questions. Thank you!

**Comment by danielfmiranda** [comment]
Tagging @tomusher so he can give the variables a look as well

**Comment by tomusher** [comment]
Looks good @danielfmiranda 

The various `HEROKU_` variables are set by the [dyno metadata feature](https://devcenter.heroku.com/articles/dyno-metadata) - so if you remove them, Heroku will just re-add them. No harm in keeping these around.

The `SCOUT_` variables are parsed by the scout library, not directly by the Django application.

**Comment by danielfmiranda** [comment]
Thanks for the feedback @tomusher! 
Going to mark this issue as closed, as we have another ticket for updating/removing env vars after the switchover is complete.
