### ISSUE TITLE
Perform switchover, disabling basket email sending and enabling donate email sending (May 25th)

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/donate-wagtail#1420]
Perform switchover, disabling basket email sending and enabling donate email sending (when in doubt, sending 2 emails is better than none)

We need to switch our env vars (as temp "feature flags") to enable sending acoustic emails and disabling basket-sent emails. 

**Note** Don't do this until at least May 25th.

**Comment by danielfmiranda** [comment]
Closing this ticket as Ben had updated the env variables!
