### ISSUE TITLE
Create a Donor Help contact page

### ISSUE THREAD

**Issue by kristinashu** [mozilla/donate-wagtail#1425]
Follow up from https://github.com/mozilla/donate-wagtail/issues/1398

- [x] Update "Send us an email." text on https://donate.mozilla.org/ template to "Contact us." which would link to a new form page.
- [x] Create a new form page at https://donate.mozilla.org/help/ which would be similar to https://give.thunderbird.net/help but the intro copy could say:
> If you need help with a donation to the Mozilla Foundation, please fill out this form and a donor care representative will get back to you as soon as possible.
- [x] Make this template the Mozilla one (adding the intro above) https://github.com/mozilla/donate-wagtail/tree/master/donate/templates/pages/core/contributor_support_page_master.html and move the TB specific copy to https://github.com/mozilla/donate-wagtail/tree/master/donate/thunderbird/templates/pages/core/contributor_support_page.html as overrides
- [x] Make sure the /help/ page exists in production
- [x] Make sure to use a different Salesforce Form IDs for Thunderbird and Donate (@stephaniemcv to provide a dedicated ID) (Applied in #1434)
- [x] Edit questions on https://donate.mozilla.org/en-US/faq/ to replace donate@mozilla.org with the form. (Théo can do, with a review from @WillatMozFdn)
- [ ] Localize CMS updates (Théo)
- [x] Localize template updates (Théo)

**Comment by TheoChevalier** [comment]
#1402 is basically a duplicate, so I consolidated everything in this ticket and added a couple steps to update + localize the FAQ page

**Comment by stephaniemcv** [comment]
I think the copy for the MoFo page should say "If you need help with a donation to Mozilla Foundation...". I believe we've been using the word 'contribution' for Tbird gifts because they a corporate donations vs gifts to MoFo are non-profit donations. However, @stephanielowry should have final approval on the copy.

**Comment by stephanielowry** [comment]
Thanks @stephaniemcv 
I agree with you. We use "donate" and "donation" throughout all of the MoFo documentation and site, except for the footer on the receipts and at the bottom of the donation form it says "Contributions go to the Mozilla ...". Maybe add the word "the" as well, as we typically have it as the Mozilla Foundation.

**Comment by kristinashu** [comment]
Thank you both! I've update the first comment to reflect these copy changes so it will be:

> If you need help with a donation to the Mozilla Foundation, please fill out this form and a donor care representative will get back to you as soon as possible.

**Comment by TheoChevalier** [comment]
The form is live and seem to work (Will tested and got a case created in SFNP). The FAQ page has been updated in English to point to the form, but I’m hitting Heroku’s 30s timeout to synchronize the copy changes to all locales…

**Comment by TheoChevalier** [comment]
Still hitting the timeout, but it somehow made it through! https://github.com/mozilla-l10n/mozilla-donate-content/commit/7765d4d36308dc4010f587edf38f9d7810633a2f
