### ISSUE TITLE
[Thunderbird] Perform post-switchover update of ENV VARS

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/donate-wagtail#1440]
Related Issue: #1405 

Since we have preformed the audit of Env variables that we use and do not use, please update the environment variables regarding thunderbird in the donate stack. 

The results of the audit can be found on this sheet https://docs.google.com/spreadsheets/d/1vwpuSairzRLrp_syKT-cXGVsL9MHdEZIAC7SDpys5Js/edit?usp=sharing.

**Comment by danielfmiranda** [comment]
Hi @tomusher! 

In the comment of this ticket is an audit we preformed of env vars in the thunderbird donate site, I was wondering if you could give it a second look, and let us know which of the items with red cells we are OK/not-OK to remove? 

Thank you!

**Comment by tomusher** [comment]
No problem - I've added some notes on the document.

**Comment by danielfmiranda** [comment]
Thanks Tom for making the updates to the document! 

I will begin removing the ones that are confirmed OK to remove, and will mark them as well on the spreadsheet

**Comment by danielfmiranda** [comment]
Preformed Audit - Closing
