### ISSUE TITLE
🔥 Donate deploys are hitting their memory limit 🔥

### ISSUE THREAD

**Issue by Pomax** [mozilla/donate-wagtail#1457]
The donate staging and production deployments are consistently riding above the 512MB memory limit, and we should figure out why, because it's adversely affecting service, which adversely affects our bottom line =)

looking at Scout, there are some calls that apparently lead to 80MB in memory allocations, let's figure out what those are?

**Comment by benhohner** [comment]
Putting this here for issue context: 
* it looks like the number of pages somehow is causing more memory usage in wagtail.
* Currently the donate version is 2.2.13. There are a number of bugfixes/performance optimizations in later wagtail versions, so we might want to look at upgrading wagtail to latest. 
* Kalob will begin memory profiling the donate site with silk and pympler
* We might also want to look at increasing memory as a last resort solution

**Comment by Pomax** [comment]
Kalob's conjected that the main culprit might be modeltranslation, where a single page effectively retrieves all languages at the same time, so pages may end up being "seven times their size in-memory".

**Comment by KalobTaulien** [comment]
Suggestion from Tom:

> Remove the uses of `lru_cache` which don't seem to be doing a lot but will be keeping references to the objects in the arguments around

**Comment by Pomax** [comment]
It looks like landing the PR that stops the redis queue from logging messages unless `DEBUG=True` (which for prod should never be the case) has gotten us back down to a baseline well below 512MB (averaging around 330MB), so I'm going to call that the probably reason, and we should be good for the foreseeable future.
