### ISSUE TITLE
Implement A/B testing on the donate site

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/donate-wagtail#1468]
We need to implement A/B testing on the donate site. 

This will include needing to test how it works behind cloudflare. 

**Note**: If we're using Cloudflare, we'll want to look into this as well 👉  https://github.com/torchbox/wagtail-ab-testing#running-ab-tests-on-a-site-that-uses-cloudflare-caching

## Criteria 
- [ ] Implement if not already added as a project dependency 
- [ ] Test it works behind cloudflare 
- [ ] Measure what we see in google analytics vs. a/b testing (there is currently a discrepancy between the two where we get more traffic than what Google Analytics picks up on)

**Comment by jamilasnell** [comment]
Iceboxing this until the next person in charge of Donate raises this issue again.

**Comment by jamilasnell** [comment]
Don't know who owns this property so we are closing this.
