### ISSUE TITLE
[Thunderbird] After donating, when opting in for email updates, the server timesout and signups arent submitted

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/donate-wagtail#1471]
Original ticket edited: 

**Describe the bug**
When submitted a donation to Thunderbird, and then signing up for the newsletter, the page timesout after 30s and leaves the user with a "maintenance" page. 

**To Reproduce**
1. Donate to Thunderbird
2. Opt in (check the box) for email updates
3. Submit form
4. Should subscribe to Mailchimp (but takes a while to process) but ends up going to a maintenance page that says "Thank you for your interest" 

#### First
- [x] Check if this bug still exists. 
#### Then 
- [ ] ~The maintenance page _really_ should not say "Thank you for your interest" as that can be quite misleading.~
- [ ] We need to figure out why the request timed out and fix it. 
  - [ ] (Could be Mailchimp taking forever or could be our backend taking a long time) 
- [x] @benhohner to test this out in production

**Comment by Sancus** [comment]
Hey, if you need any help with this or anything else Thunderbird/donate related, you can contact me on Matrix in #maildev: https://chat.mozilla.org/#/room/#maildev:mozilla.org -- or just @ me on GitHub.

**Comment by benhohner** [comment]
@KalobTaulien Just donated to Thunderbird using credit card. Can confirm that after donating when opting in to the newsletter and clicking okay, the site times out then redirects to the maintenance page.

**Comment by KalobTaulien** [comment]
Can confirm it times out on localhost too. 

The problem lies with the request we're making to the form. Mailchimp provides form URLs but we _should_ be using the Mailchimp API (mailchimp3 on pypi). 

@benhohner I need a few things to work with the Mailchimp API:
1. The Mailchimp userame,
2. The Mailchimp secret key (API key)
3. The list ID of the list we want to subscribe users to.
