### ISSUE TITLE
Delete nav hamburger & most footer links from donate page 

### ISSUE THREAD

**Issue by KalobTaulien** [mozilla/donate-wagtail#1491]
We need to delete the hamburgler and most foot links from the donate page. 

See this [Airtable base for more information](https://airtable.com/tbljPmOCkK9JShaTS/viw9sdUJiIjCYpn0Y/rec9lfWpcwgenu0ZA?blocks=hide)

## Acceptance criteria 
- [x] Determine if those components should be deleted from _every_ page or just the main long-form page (page 2 of the donate process) 
- [x] Delete hamburger menu 
- [x] Remove most footer links

**Comment by KalobTaulien** [comment]
Hey @kristinashu do you know if we're deleting the hamburger menu and most footer links from _every_ page or just the long-form page? This will determine how long and complex this will get.

**Comment by kristinashu** [comment]
I don't know anything beyond what is in the Airtable link but I suspect Will wants it removed from every page, I can ask him tho. Also just to clarify, what do you mean by long-form page? What would _every_ page be?
