### ISSUE TITLE
Payment page

### ISSUE THREAD

**Issue by nicklee** [mozilla/donate-wagtail#15]
**Design / Wireframe:**

Desktop: https://redpen.io/wc32042c29a9469ca3
Tablet: https://redpen.io/htf5aa93e00a71214e
Mobile: https://redpen.io/sr0030705d1be8c65f

**Components that form this template:**

- [ ] Steps (Payment active)
- [ ] Payment form
- [ ] Partner logo (multiple)
- [ ] Legal text

**Comment by philwakefield** [comment]
Payment is now part of the details page
