### ISSUE TITLE
Delay in receipt sending past a certain hour

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/donate-wagtail#1500]
**Describe the bug**
According to some of the people testing the new receipt sending, there is a delay in receiving the thank you receipt especially if you make a donation in the evening. 

**Expected behavior**
The thank you receipt should be sent shortly after the user has made the donation. 

Possible Causes: 
Our timezone on the server and braintrees timezone?

IIRC this issue has been resolved, however we are creating this ticket to verify.

**Comment by stephaniemcv** [comment]
FYI I hit a similar bug to this in Braintree staging the evening of  6/14 for both recurring and one-time donations I was testing. While I got the receipts in the evening, the data didn't pass into Cinchy because the status of the transactions in Braintree didn't change from "Submitted to Settlement" to "Settled" until the next day.

**Comment by stephaniemcv** [comment]
Spoke with @stephanielowry and verified that this issue is still occuring on recurring subscriptions and one-time transactions.

**Comment by stephaniemcv** [comment]
Example from Braintree:
Transaction created 6/12 but not active until 6/13. Email receipt sent at  Jun 13, 6:14 AM.

![image](https://user-images.githubusercontent.com/11812272/122299196-e8ce3880-ceba-11eb-815d-093f43ca45ed.png)

**Comment by stephaniemcv** [comment]
Additional info from Fundraising team:

@WillatMozFdn contacted Braintree on 5/26. Message and their reply below.

> May 26, 2021, 9:20 AM CDT
> Name: Will Easton
> Business Email: will@mozillafoundation.org
> Business Name: Mozilla Foundation
> Message: We're seeing long delays (12+ hours) in new subscriptions ... they go into “pending“ status for quite some time. Examples: subscription ID b73dbp (which has now gone active) and subscription ID 69hvqj (still pending). This causes problems & donor/customer dissatisfaction, as we don't/can't send a confirmation email until the subscription goes active ... and a long delay like this causes the donor/customer to write in to us in confusion, thinking that their recurring donation has not gone through. What is the source of these long delays and how can we reduce them to a minimum? THANK YOU.
⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼⎼

>  Shaquille E. (Braintree)
> May 26, 2021, 12:55 PM CDT
> 
> Hi Will,
> Thanks for reaching out. I'm Shaquille with Braintree Technical Support, happy to help.
> I noted in the subscription examples provided the subscription was created with a specified start date in the future. This creates a subscription that remains [Pending](https://developers.braintreepayments.com/guides/recurring-billing/overview#pending) until the first billing date when the customer is charged and the subscription becomes [Active](https://developers.braintreepayments.com/guides/recurring-billing/overview#active). Do note, you can [create a subscription to start billing immediately](https://developers.braintreepayments.com/reference/request/subscription/create#set-start-date). This revision can be made [to the plan](https://articles.braintreepayments.com/guides/recurring-billing/plans?_ga=1.255129614.743433448.1608653591#updating-a-plan) that subscriptions are based on, or in the [subscription.create()](https://developers.braintreepayments.com/reference/request/subscription/create) call itself.
> 
> I hope this clarifies things. Please feel free to reach back out with any further questions.
