### ISSUE TITLE
Some countries without Post-Code still have Post-Code set as required.

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/donate-wagtail#1518]
**Describe the bug**
Based on feedback from a user, they have attempted to make a donation with Hong Kong set as the country, which removes the post code field from view and should make the field not required so the user can submit their donation.

However, if you fill out the form and attempt to make a donation, you will recieve an error message, and when changing to country with post code, will see that it is still expecting a post code. 

**To Reproduce**
1. Go to the donation homepage
2. Fill out the form
3. Submit the form

**Expected behavior**
It should allow the user to submit their donation without a post code

**Comment by danielfmiranda** [comment]
Interestingly, testing this on my local machine works as expected without a bug. 

However, I am able to recreate the bug on staging. 

I believe that the bug is in the back-end of the application, as all the front end is doing in regards to post code is removing the input from view. The back end is the portion that does the validation and will return a message if post-code is necessary.

I wonder if something when deployed is preventing the list from being loaded, thus making post code required for all countries?

**Comment by danielfmiranda** [comment]
Hi Everyone, here are some findings after troubleshooting this issue:

- I can confirm that this issue is only reproducible in staging or prod. Whenever I try to reproduce this issue in my local machine, the error does not occur.
- I have added some print statements to see if the file "donate/payments/forms.py" was able to load the file "post-codes-list.json" and it appears that the error is caused by the python file having trouble finding and loading it. 
- As an attempt to fix this, I have tried the following paths to the file:
1. ".**/source/js/components/post-codes-list.json**" - which works on my local machine
2. "**../source/js/components/post-codes-list.json**" - does not work on local machine or heroku review apps as this is too far back in the directory. 
3. "**source/js/components/post-codes-list.json**" - Works again on local machine, not on heroku.

@Pomax I was wondering if you knew if there was something that is heroku specific that can be preventing the python file from reaching the post-codes-list information? Thanks in advance!

**Comment by Pomax** [comment]
If I repeat the STR on staging, I see the dev console throw an error about `https://www.google-analytics.com/j/connect`, and looking at the CSP_CONNECT_SRC, there is `https://www.google-analytics.com/connect`, so let's set that to include that `/j/` and see what that does.

**Comment by Pomax** [comment]
That fixed the CSP warning, but not the original error.

**Comment by Pomax** [comment]
This works perfectly fine locally, so let's see if the DOM/source can tell us anything.

**Comment by Pomax** [comment]
So the error is indeed on the zip code field, which we still include, but hide:

![image](https://user-images.githubusercontent.com/177243/127409059-012414cd-2071-4aeb-aac4-105a0a98e132.png)

**Comment by Pomax** [comment]
Looking at the error report:

![image](https://user-images.githubusercontent.com/177243/127409094-a4276c05-b740-4805-8b98-7966b1770405.png)

**Comment by Pomax** [comment]
So, it would appear that the form on staging/production still thinks that for Hong Kong, zip code is required. Let's find out where that information is encoded.

**Comment by Pomax** [comment]
constants.py:
```python
    {
        'abbrev': 'HN',
        'name': 'Honduras',
        'postal': '[0-9]{5}',
    },
    {
        'abbrev': 'HK',
        'name': 'Hong Kong',
    },
    {
        'abbrev': 'HU',
        'name': 'Hungary',
        'postal': '[0-9]{4}',
    },
```
post-codes-list.json:
```js
  {
     "abbrev":"HN",
     "name":"Honduras",
     "postal":"[0-9]{5}"
  },
  {
     "abbrev":"HK",
     "name":"Hong Kong"
  },
  {
     "abbrev":"HU",
     "name":"Hungary",
     "postal":"[0-9]{4}"
  },
```

**Comment by Pomax** [comment]
checking the actual heroku file system: 
```bash
~/donate/payments $ ls constants.py -asl
16 -rw------- 1 u52220 dyno 13579 Jul 22 00:04 constants.py
```

**Comment by Pomax** [comment]
that... is too small. That file is supposed to be 34kb

**Comment by Pomax** [comment]
`source/js/components/post-codes-list.json` encodes this as:
```json
  {
     "abbrev":"HN",
     "name":"Honduras",
     "postal":"[0-9]{5}"
  },
  {
     "abbrev":"HK",
     "name":"Hong Kong"
  },
  {
     "abbrev":"HU",
     "name":"Hungary",
     "postal":"[0-9]{4}"
  },
```

**Comment by Pomax** [comment]
We load this data in `donate/payments/forms.py` as:
```python
# # Loading a JSON list of countries and their respective post code formats if applicable,
# # from the source/js directory.
try:
    with open('./source/js/components/post-codes-list.json') as post_code_data:
        COUNTRY_POST_CODES = json.load(post_code_data)
except Exception:
    COUNTRY_POST_CODES = None
```
After which we have the `PostalCodeMixin` mixin:
```python
    def clean(self):
        cleaned_data = super().clean()
        postal_code = cleaned_data.get('post_code', '')
        country = cleaned_data.get('country', '')
        # If we cannot import post-code data, default to it being required.
        if COUNTRY_POST_CODES is None:
            self.check_post_code(postal_code)
        # Checking if the country uses post-code by finding it in JSON data.
        elif 'postal' in next(country_obj for country_obj in COUNTRY_POST_CODES if country_obj["abbrev"] == country):
            self.check_post_code(postal_code)

    def check_post_code(self, postal_code):
        if postal_code == "":
            raise forms.ValidationError({
                'post_code': _('This field is required.')
            })
```

**Comment by Pomax** [comment]
```bash
$ python
>>> import json
>>> with open('./source/js/components/post-codes-list.json') as post_code_data:
...     COUNTRY_POST_CODES = json.load(post_code_data)
... 
>>> country = "HK"       
>>> for country_obj in COUNTRY_POST_CODES:
...     if country_obj["abbrev"] == country:
...         print(country_obj)
... 
{'abbrev': 'HK', 'name': 'Hong Kong'}
```

**Comment by Pomax** [comment]
```bash
>>> if 'postal' in next(country_obj for country_obj in COUNTRY_POST_CODES if country_obj["abbrev"] == country):
...     print(f'{country} has a postal code requirement')
... 
IS has a postal code requirement
>>> country = "HK"
>>> if 'postal' in next(country_obj for country_obj in COUNTRY_POST_CODES if country_obj["abbrev"] == country):
...     print(f'{country} has a postal code requirement')
... 
```
So it should be reasonably evident that this code does what it's supposed to. HK does not have a `postal` attribute, and so `check_post_code` should not be kicking in.

**Comment by Pomax** [comment]
There is currently nothing that tells us whether or not the postal code data get read properly or not, so let's add in an investigatory print statement that will tell us whether, at dyno startup, we were able to read in the postal code data at all.

**Comment by Pomax** [comment]
A brief test: Bahrain, country code BH, also does not have a postal code. If the postal code data did not load on the python side, we would expect to see that fail too.

**Comment by Pomax** [comment]
it indeed fails:

![image](https://user-images.githubusercontent.com/177243/127411337-2bd957ca-a190-4b0b-987b-89158a501540.png)

**Comment by Pomax** [comment]
One more, just to make doubly sure. Jamaica, code JM, does not have a postal code requirement either.

**Comment by Pomax** [comment]
![image](https://user-images.githubusercontent.com/177243/127411425-3c7d9e13-0db6-413c-b99f-6138ac18f920.png)

**Comment by Pomax** [comment]
Trying pythoh on heroku shows that loading this file indeed fails:
```bash
Running bash on ⬢ donate-wagtail-staging... up, run.8918 (Standard-1X)
Generating SSH config
Done!
~ $ python
Python 3.7.8 (default, Sep 29 2020, 17:54:30)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> try:
...     with open('./source/js/components/post-codes-list.json') as post_code_data:
...         COUNTRY_POST_CODES = json.load(post_code_data)
... except Exception:
...     print('could not load postal code data')
... 
could not load postal code data
```

**Comment by Pomax** [comment]
Let's gather some evidence: https://github.com/mozilla/donate-wagtail/pull/1535
