### ISSUE TITLE
Update donor support forms to reflect more language picklist options

### ISSUE THREAD

**Issue by benhohner** [mozilla/donate-wagtail#1557]
In both Mozilla and Thunderbird donate support forms, update the HTML to support the expanded list of languages:

@stephaniemcv can you please paste the updated HTML into a comment in this issue.

**Comment by stephaniemcv** [comment]
Language:<select  id="00N4x00000O6Pzw" name="00N4x00000O6Pzw" title="Language"><option value="">--None--</option><option value="Chinese Simplified">Chinese Simplified</option>
<option value="Czech">Czech</option>
<option value="Danish">Danish</option>
<option value="Dutch">Dutch</option>
<option value="English">English</option>
<option value="French">French</option>
<option value="German">German</option>
<option value="Italian">Italian</option>
<option value="Japanese">Japanese</option>
<option value="Other">Other</option>
<option value="Polish">Polish</option>
<option value="Portuguese">Portuguese</option>
<option value="Russian">Russian</option>
<option value="Spanish">Spanish</option>
</select><br>
