### ISSUE TITLE
Add `description` to RQ queueing instructions

### ISSUE THREAD

**Issue by Pomax** [mozilla/donate-wagtail#1564]
RQ will logs the job `description` on success, which if unset seems to default to the job arguments, meaning it will log a huge braintree string on success. We should be able to pass a `description` kwarg to our `queue.enqueue` calls, to make sure that we only log short and sweet text.

**Comment by jamilasnell** [comment]
@tomusher Want to make sure that this is still on your radar! Thank you

**Comment by tomusher** [comment]
Sorry for not commenting here - this is fixed in #1567
