### ISSUE TITLE
Braintree Signatures Polluting Logs

### ISSUE THREAD

**Issue by benhohner** [mozilla/donate-wagtail#1566]
**Describe the bug**
Braintree signatures are being logged.
For some reason the string:
`donate.payments.tasks.process_webhook({'bt_signature': <massive amounts of text>})`
is being logged which is consuming our logstash bandwidth and polluting logs, also possibly polluting logs with PII.

**To Reproduce**
1. Go to Logstash
2. Search for bt_signature

**Expected behavior**
User information derived signatures shouldn't be logged. 
Let's determine why this was implemented in the first place, and if we can replace it with a better message or get rid of the statement all together.

**Comment by Pomax** [comment]
May be related to https://github.com/mozilla/donate-wagtail/issues/1564

**Comment by tomusher** [comment]
This should be fixed by #1567
