### ISSUE TITLE
Upsell template

### ISSUE THREAD

**Issue by nicklee** [mozilla/donate-wagtail#16]
**Overview:**

Asks the user to upgrade their one off donation to a monthly donation. Step 4 (Landing/Campaign > Details > Payment > Upsell) of the process, could potentially be optional, would only show for user that selected a one off payment. 

**Design / Wireframe:**

Desktop: https://redpen.io/gtf39ea26c965f9605
Tablet: https://redpen.io/opc85e9f5502e7ed3f
Mobile: https://redpen.io/hz1a87f231444df639

**Components that form this template:**

- [x] Title
- [x] Introductory text
- [x] Upsell form

**Comment by solarissmoke** [comment]
Note, we have different upsell templates for card and Paypal. 

We are going to have to adjust the designs for the Paypal upsell @beccaklam because we have to have a Paypal-generated button there to initiate the authorisation flow.

**Comment by nicklee** [comment]
We need to update the "amount" label to "Yes, I will give", as per the designs, is this something you can do @solarissmoke? Other than that we should be good on the FE side of things here:

https://github.com/mozilla/donate-wagtail/pull/124

**Comment by nicklee** [comment]
We also need to ensure the step on the Yes, I will give field is set to 1 instead of 0.01

**Comment by solarissmoke** [comment]
Yep, I will update the label tomorrow.

**Comment by solarissmoke** [comment]
> We also need to ensure the step on the Yes, I will give field is set to 1 instead of 0.01

This would mean changing from decimal to integer on the field. I think we need to confirm whether decimal amounts are allowable, or whether we only allow whole numbers for monthly donations. @alanmoo?

**Comment by alanmoo** [comment]
Just to confirm somewhere permanent: Yes, decimals for monthly and one-time. The step set to integers is probably best though.
