### ISSUE TITLE
give.thunderbird.net certificate expired

### ISSUE THREAD

**Issue by Sancus** [mozilla/donate-wagtail#1600]
As the title says. Looks like the DigiCert certificate on this has expired.

https://give.thunderbird.net/

**Comment by jzinner** [comment]
Attempting to enable Automated Certificate Management per: https://devcenter.heroku.com/articles/automated-certificate-management

**Comment by jzinner** [comment]
Resolved - migrated to Automated Certificate Management in heroku.
