### ISSUE TITLE
Changing Language on Donate Page

### ISSUE THREAD

**Issue by Pomax** [mozilla/donate-wagtail#1603]
@jamilasnell commented on [Tue Dec 14 2021](https://github.com/mozilla/foundation.mozilla.org/issues/8011)

We have a request to change language on the donate page. "Bitcoin" is listed in the "in the other ways to give" section. 

That page links to a mana page and then eventually a form. We need to update the language on all these pages to show that we accept a diversity of crypto currencies through Bitpay (not just Bitcoins). Ideally, we'd simply add the BitPay button next to the PayPal button.

![image.png](https://images.zenhubusercontent.com/5f592fe47f30fa8d24d93d20/371e9435-8fe4-42cd-855e-0dd85d41faa9)

Listed it as high priority in order to get this done before code freeze.

---

@jessedward commented on [Wed Dec 15 2021](https://github.com/mozilla/foundation.mozilla.org/issues/8011#issuecomment-995065833)

When we have more time, adding the bitpay payment mark (https://brand.bitpay.com/7b6hnbyxw/p/76b712-payment-mark/b/600f40), similar to PayPal, will be most helpful in securing more cryptocurrency donations. In the meantime, I'd like the text that says "Bitcoin" in the "other ways to give" section to say "BitPay (cryptocurrencies)". And instead of linking to the mana page, it should like directly to the bitpay payment form (https://bitpay.com/100257/donate). I also need some text updates to that payment form but tracking down who has access to that page since I'm not sure that is you.

---

@Pomax commented on [Wed Dec 15 2021](https://github.com/mozilla/foundation.mozilla.org/issues/8011#issuecomment-995212902)

I'll form a PR to update that term and the link in the mean time.

---

@Pomax commented on [Wed Dec 15 2021](https://github.com/mozilla/foundation.mozilla.org/issues/8011#issuecomment-995216834)

Note that there is also the "Bitcoin" section at the bottom on https://donate.mozilla.org/en-US/ways-to-give, and it looks like the FAQ page is a normal CMS page that staff can update themselves, mentioning bitcoin a several places.

**Comment by Pomax** [comment]
@jamilasnell @jessedward I have a PR up on https://github.com/mozilla/donate-wagtail/pull/1602 for putting in the code changes necessary, however, note that there are more places where bitcoin is mentioned, and that the FAQ page can (and should) be updated by staff with admin access to the CMS rather than by the dev team.

**Comment by jessedward** [comment]
@Pomax thanks for updating the donate page and flagging the changes needed in FAQs. If I don't have access to change that myself, I'll find someone that does. I'll also update the mana page that talks about crypto.

**Comment by Pomax** [comment]
nice - if you can let me know whether the text in https://donate.mozilla.org/en-US/ways-to-give/ can be updated (I assume just replacing `bitcoin` with `cryptocurrencies is enough), specifically the last sentence "Learn more about bitcoin donations [here]. To donate bitcoin, please [visit this link]." where the first link is our bitcoin-specific wiki page, I can make changes to that as well.

**Comment by Pomax** [comment]
@jessedward nice - if you can let me know whether the text in https://donate.mozilla.org/en-US/ways-to-give/ can be updated (I assume just replacing `bitcoin` with `cryptocurrencies is enough), specifically the last sentence "Learn more about bitcoin donations [here]. To donate bitcoin, please [visit this link]." where the first link is our bitcoin-specific wiki page, I can make changes to that as well.

**Comment by jessedward** [comment]
@Pomax thanks for catching this as well! Yes, changing to "cryptocurrencies" anywhere it says "bitcoin" would be great. The links are fine for the last sentence -- I just need to get each of those pages updated as well.

**Comment by Pomax** [comment]
PR landed, I'll do a prod push once staging has caught up

**Comment by Pomax** [comment]
prod push has been initiated - we probably want a new issue filed so we can triage and plan in any work around a dedicated crypto donate button.

**Comment by Pomax** [comment]
closing as done
