### ISSUE TITLE
temporarily remove/pause language referencing to crypto donation

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/donate-wagtail#1608]
Per conversation in ticket [#8011](https://github.com/mozilla/foundation.mozilla.org/issues/8011) on the foundation repo, we would like to temporarily remove references to crypto donations as well as remove the link for users to make donations.

**Comment by Pomax** [comment]
Previous PR: https://github.com/mozilla/donate-wagtail/pull/1602

**Comment by anilkanji** [comment]
Thanks @danielfmiranda - when will this change show up on the site?

**Comment by jessedward** [comment]
I've updated [the wiki page](https://wiki.mozilla.org/Donate_Bitcoin) with a note at the top saying we are pausing our acceptance of crypto. Let me know if I can help with anything else, though I don't think I have access to changing the language on any of the other pages.
