### ISSUE TITLE
Update crypto notices

### ISSUE THREAD

**Issue by Pomax** [mozilla/donate-wagtail#1619]
Steps required:

- [x] update page templates
  - https://github.com/mozilla/donate-wagtail/pull/1609
- [x] update wiki
  - wiki article on mozilla.org has a large notice at the top of the page
- [x] update FAQ page
  - copy updated to note we are not accepting bitcoin while we evaluate, see https://donate.mozilla.org/en-US/faq/
- [x] update localized copy
  - pending - full timeframe depends on the localization community.

**Comment by TheoChevalier** [comment]
I can safely check the last checkbox, as mentions of cryptocurrencies are now gone in all languages — it’s just some pages will show the updated content in English for a while until it’s translated
