### ISSUE TITLE
Review and update minimum donation amounts

### ISSUE THREAD

**Issue by jzinner** [mozilla/donate-wagtail#1633]
# Decision: Canceled without implementing #

@anilkanji made Product Decision that MoFo's donation ethos is pay as much as you can.  Anil indicated donations provided a source of email addresses to use for other Foundation initiatives, and that small amounts might provide repeat donations in future years. 

We my re-evaluate this decision in future years. 

### Product Management tasks: 

- [x] Ask Stephanie L. to run reports for number of donations for values under $10 for all the currencies we accept through `donate.mozilla.org` property within: ?? Braintree & Paypal
- [x] Find out how difficult to create report / how long to create
- [x] Ask Stephanie L. to run reports for number of donations for each $ value for the `give.thunderbird.net`  property within: ?? Braintree & Paypal
- [ ] Review reports (probably schedule meeting with Stephanie) and work together to figure out new minimum donation amounts.  This will be based on the total number of fraudulent transactions for various values and also the total number of actual donations that came in for those amounts.

- [ ] Review results with thunderbird representative Andre / Sancus (send contact through Slack).  To get his approval to increase the minimum donation amounts for give.thunderbird if we have to. Note: it is possible to set updated minimums for donate while not having to make changes to thunderbirds. 

This was originally requested by stephanielowry on Jan 28,2022 to make the sites less attractive to fraudulent / card testing people. 

Write the Implementation:

link to constants.py file where Currency minimums are set.  -  https://github.com/mozilla/donate-wagtail/blob/5e3fc1ce6e747e3eb2aefddc409b7f74196a81ee/donate/payments/constants.py#L23

**Comment by stephanielowry** [comment]
@danielfmiranda and all! 

Here's a link to the Google Doc data for under $10 for Nov/Dec for both MoFo and Tbird

If you need this broken down further, just let me know what you need! Thanks!

https://docs.google.com/document/d/1H33okP-0I72DO-5xsCrCyFGGxwmZlCIIFAxEqxklPqk/edit

**Comment by danielfmiranda** [comment]
Hi Stephanie, 

Thanks so much for getting that data to us! 

I have displayed the data in a table and graph format here, in case we would like to use it for our discussions:
https://docs.google.com/spreadsheets/d/1COy7j7DPAboi58ZFOERQkQoxi8WZP9pmoDkjF94mifo/edit?usp=sharing

<img width="937" alt="Screen Shot 2022-02-08 at 10 28 44 AM" src="https://user-images.githubusercontent.com/18314510/153052339-4821ec17-6236-4043-83e5-86ecef3a1b9e.png">

**Comment by stephanielowry** [comment]
Thanks @danielfmiranda for turning the data into such a nice table and graph! I would have been happy to do that if I would have known you needed it instead of just throwing it into a doc.

**Comment by danielfmiranda** [comment]
No problem @stephanielowry happy to help! Thanks again for getting the data to us

To provide an update: Now that we have the data, I am going to work with @jzinner to discuss next steps needed to take care of this ticket

**Comment by Sancus** [comment]
Just out of curiosity, what's the minimum amount being considered? $5? $10?

These donations seem to be a relatively tiny percentage of our total so I think it's reasonable to increase the minimum a bit.

**Comment by danielfmiranda** [comment]
Hi @Sancus! I believe those are the amounts being discussed at the moment, however, I did want to bring up that it is possible to update the minimum donation amount for the mofo donate site (the one experiencing fraud) and keeping the existing donation minimums for thunderbird if that is what the team would prefer.

**Comment by jzinner** [comment]
@Sancus @stephanielowry - Anil made the Product Decision not to move forward with increasing minimum donation amounts.  See the updated Issue description for more information.
