### ISSUE TITLE
Update message for "other amount" field

### ISSUE THREAD

**Issue by danielfmiranda** [mozilla/donate-wagtail#1634]
Donor Care is requesting that we show the minimum amount message on the "Other amount" field when the user clicks on the form input.

However, theres some discussion whether or not we should just show the minimum amount underneath the field constantly.

- [x] Reach out to design to see which format they think is best
- [ ] Implement suggestion

**Comment by danielfmiranda** [comment]
Hi @kristinashu! 

I was wondering if you could please help me with the design portion of this ticket:

It appears that the two suggested options to implement the "minimum amount" message are:

To have another string of text underneath the input field like so, where instead of a red error message it would instead say something like "Minimum amount is x"
<img width="728" alt="image" src="https://user-images.githubusercontent.com/18314510/152067706-bc5be239-e020-40a6-8c3b-e0f1af3c4fd6.png">

Or, to have the message appear when the user clicks on the input field like so:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/18314510/152068225-142299d3-158d-40de-8610-8df3a699d156.png">


I was wondering which one the design team wants me to go forward with and implement? 

Thank you!

**Comment by kristinashu** [comment]
Thanks for checking @danielfmiranda! My recommendation would be option 1 - always show the text below (text could be a dark grey). I'm concerned that option 2 could be jarring to people - they click into the box and then something expected changes. Does that help?

**Comment by danielfmiranda** [comment]
Hi @kristinashu thank you, that does help!
