### ISSUE TITLE
Adding try / except and retry for AWS SQS queue that feeds Cinchy

### ISSUE THREAD

**Issue by jzinner** [mozilla/donate-wagtail#1647]
Request asks is to add try / except and retry for SQS queue that feeds Cinchy.  

Since the donate-wagtail app doesn't communicate directly with Cinchy, the Python code is responsible for adding the message to the AWS SQS  queue.  

The code to investigate for possible try / except blocks is likely sqs.py

**Comment by danielfmiranda** [comment]
Moving this to blocked, meeting with Dan/Jacki/Pomax TBD
