### ISSUE TITLE
Display "processing" status indicators

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#165]
There is a noticeable lag between:

1. Paypal window closing and submission of form on the main page.

2. Hitting the "pay" button on card payments, and submission of the form.

We should provide some indication to the user that something is happening, to minimise the risk of them taking further actions. For the card button it should be possible just to disable it. For Paypal, we could display a message/overlay indicating that the payment is being processed. We may also want to hide the paypal button.

Passing to @beccaklam for initial design input.

**Comment by beccaklam** [comment]
Hi @nicklee and @solarissmoke sorry for the delay. I've dropped my designs into the redpen: https://redpen.io/p/qf140664ca9fa398bb
It's pretty simple, wondering if we could do a css animation for the loader? Like "Loader 3" in this codepen? https://codepen.io/ricardoolivaalonso/pen/JQYrxM
![Screen Shot 2019-08-13 at 11 38 28 AM](https://user-images.githubusercontent.com/20977376/62955346-e2eb0600-bdbe-11e9-857d-b455fc25a572.png)

**Comment by alanmoo** [comment]
Ah, I forgot about this one. @philwakefield While this isn't a launch blocker, it is an item I'm concerned could have impact on conversion.

@beccaklam Is there a live example of that loader somewhere that we could grab? While I think having something here is important, I don't want to miss out on this because of the need for an animation.

**Comment by beccaklam** [comment]
> Ah, I forgot about this one. @philwakefield While this isn't a launch blocker, it is an item I'm concerned could have impact on conversion.
> 
> @beccaklam Is there a live example of that loader somewhere that we could grab? While I think having something here is important, I don't want to miss out on this because of the need for an animation.

Yes: "Loader 3" in this codepen https://codepen.io/ricardoolivaalonso/pen/JQYrxM

**Comment by jamilasnell** [comment]
We just added this! Hooray!!!
