### ISSUE TITLE
Direct access to a localized page should override the detected browser locale

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#166]
For instance, using a French browser, if I access directly to https://donate-wagtail.mofostaging.net/pl/, the page locale (and associated currency) should ignore the browser locale and switch to Polish instead (and propose Złotys).

Of course, if I was accessing https://donate-wagtail.mofostaging.net/ instead, I should get redirected to https://donate-wagtail.mofostaging.net/fr/ and get EUR by default (this currently works as expected)

**Comment by solarissmoke** [comment]
Thanks for this. The language will work once we have translations in place (we don't yet). For currency we currently rely only on browser language, so I will make a change to prefer URL-based locale.

**Comment by solarissmoke** [comment]
@TheoChevalier what you've described here is a bit different from the [spec we originally had](https://github.com/mozilla/donate-wagtail/issues/1#issuecomment-509908160). Just want to confirm before I make the change that the new behaviour will be:

1. First determine user language/locale based on Accept-Language header, and use that to redirect the user to the appropriate URL prefix (e.g., `/fr/`).
2. Having done that, use the URL prefix to determine the default currency - e.g., if `/fr/` then default to euros.

Does this sound OK?
