### ISSUE TITLE
Migrate to SaaS Sentry - give.thunderbird.net

### ISSUE THREAD

**Issue by tbrlpld** [mozilla/donate-wagtail#1660]
Update this with learnings from https://app.zenhub.com/workspaces/mofo-engagement-585335eab729771d0736378d/issues/mozilla/foundation.mozilla.org/8806

Since this is the same repo as https://github.com/mozilla/donate-wagtail/issues/1659 only the configuration sets should need repeating.

**Comment by tbrlpld** [comment]
cc @cdanfon

**Comment by jzinner** [comment]
So since donate and thunderbird build off the same repo -> donate-wagtail.
The sentry behaviors of each should be the same.
So I cut over give-thunderbird-net to SaaS Sentry at 4:06pm CT
