### ISSUE TITLE
[DONATE] Update copy on donor care page

### ISSUE THREAD

**Issue by anilkanji** [mozilla/donate-wagtail#1668]
**As a donor care rep, I want to add copy to our donor help page so that supporters can find out to get the right kind of help from us**

Please edit donor [help page](https://donate.mozilla.org/en-CA/help/) with copy to be provided by @Stephanie Lowery

By end of May 2022

**Comment by tbrlpld** [comment]
@anilkanji I have moved the ticket to the donate repo and lined it up for next grooming session. Please let me know if this is urgent and needs to be pulled into the sprint.

**Comment by cdanfon** [comment]
Hey @danielfmiranda Any luck grooming this ticket?
