### ISSUE TITLE
Country code in URLs should be in uppercase

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#167]
This is likely already planned, but filing it as I couldn’t find an issue tracking this.

For locales with a country code, the country code should be written in capital letters.

For instance:
https://donate-wagtail.mofostaging.net/en-us/ should be https://donate-wagtail.mofostaging.net/en-US/
https://donate-wagtail.mofostaging.net/pt-br/ should be https://donate-wagtail.mofostaging.net/pt-BR/

etc

**Comment by solarissmoke** [comment]
I had a stab at this when setting up Django's defaul i18n, and it wasn't happy about it (it refused to recognise languages defined with uppercase country portion). I will have a deeper look to see what is required for us to get this to work.

**Comment by solarissmoke** [comment]
@TheoChevalier I've spent a lot of time looking into this. Django's internals make very strong assumptions about how language prefixes are structured, and these must always be lowercase. This is enforced at [a very low level](https://github.com/django/django/blob/9e38ed0536c7dc598a6c2c1bb774d0a8db3cdddc/django/utils/translation/__init__.py#L263-L269) in the internals of translation, and affects both i18n URLs and [translation](https://github.com/django/django/blob/7f19e3713598a37b0809b5434114140170d12e34/django/utils/translation/trans_real.py#L394). 

Could you explain the reason that you need the country portion to be uppercased?

Having looked at the internals, the best solution I can suggest if you absolutely need this is that we write middleware that redirects a URL in the format you describe (`/en-US/`) to one that Django will accept (`/en-us/`). I haven't been able to find a way to get Django to accept `/en-US/`.

**Comment by TheoChevalier** [comment]
Thanks for taking a (deep) look @solarissmoke, I didn’t know it was a Django requirement.

So, we need this for a few reasons, unfortunately.

The obvious one is that Mozilla projects are following ISO 3166-1 as a convention.
But the main reason is that there are links out there that are pointing to /en-US or /pt-BR. Some that we may be able to update with some work, like on mozilla.org, but others that we won’t, like in email receipts or web properties that we don’t control.
I’m also not sure how that change would play with Google Analytics. Or if the URL change would impact SEO.

Finally, I don’t know if this has an impact on the locale folders as well, but I also want to point out that Pontoon will require capitalized folder names, and won’t work with `pt-br`.

The good news is mozilla.org is a Django-based website, and it seems they have said middleware in place, so you may be able to leverage that code: https://github.com/mozilla/bedrock/blob/master/bedrock/base/middleware.py Is this what we need?

**Comment by solarissmoke** [comment]
> Is this what we need?

I think it is! You'll see that they have had to replace a very large chunk of the [URL resolution logic](https://github.com/mozilla/bedrock/blob/master/bedrock/base/urlresolvers.py) which I felt would require fighting a lot with Django. But it looks like we should be able to copy that wholesale - I will give it a go!

> Pontoon will require capitalized folder names

Django generates folders in the form `en_GB` - country portion is capitalised, but uses underscore and not `-`. Will that work for Pontoon?

**Comment by TheoChevalier** [comment]
> > Is this what we need?
> 
> I think it is! You'll see that they have had to replace a very large chunk of the [URL resolution logic](https://github.com/mozilla/bedrock/blob/master/bedrock/base/urlresolvers.py) which I felt would require fighting a lot with Django. But it looks like we should be able to copy that wholesale - I will give it a go!
> 

Hooray! :)

> > Pontoon will require capitalized folder names
> 
> Django generates folders in the form `en_GB` - country portion is capitalised, but uses underscore and not `-`. Will that work for Pontoon?

Yes! That will work, we’re doing just that for this project: https://github.com/mozilla/fxa-content-server-l10n/tree/master/locale

**Comment by solarissmoke** [comment]
Had a quick look at what is being on on the mozilla site, and there was a lot of work that went into this:

- https://github.com/mozilla/bedrock/blob/master/bedrock/base/middleware.py
- https://github.com/mozilla/bedrock/blob/master/bedrock/base/urlresolvers.py 
- https://github.com/mozilla/bedrock/tree/master/lib/l10n_utils

I think it merits some discussion as to whether copying all of this logic into this repo makes sense, or whether we should instead consider putting it in a reusable library. cc @philwakefield

**Comment by Pomax** [comment]
Hm, looking at https://github.com/django/django/tree/master/django/conf/locale Django should work just fine for things like `pt_BR` already, have we verified that a plain Django 2.2 doesn't already do "the right thing" out of the box here, with that Bedrock's code actually doing way more than necessary to get locales to look right in URLs?

**Comment by solarissmoke** [comment]
@Pomax the locale (translation) bit is fine - the problem is with the requirement to have capitals in the country portion of URLs - Django's URL routing doesn't support this and all that overriding appears to be necessary. I'm going to have another look at it this week, but don't think there is an easy fix.
