### ISSUE TITLE
Donate error in https://donate-wagtail.mofostaging.net/

### ISSUE THREAD

**Issue by cdanfon** [mozilla/donate-wagtail#1672]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://donate-wagtail.mofostaging.net/en-GB/'
2. See error below **Donate now** 'An error occurred. Please reload the page or try again later.'

**Expected behavior**
To be able to test donations in the staging site.
As stands the error prevents from filling out any card details in the next screen. 

**Screenshots**
<img width="1297" alt="Screenshot 2022-06-29 at 09 38 14" src="https://user-images.githubusercontent.com/102978346/176394066-6d9cac6c-4cc7-4e22-b89d-9184cbd4d871.png">

<img width="1297" alt="Screenshot 2022-06-29 at 09 49 47" src="https://user-images.githubusercontent.com/102978346/176396654-4742be4a-dd9a-42ac-9a7c-d706c921bbab.png">

**Desktop (please complete the following information):**
 - macOS Monterey
 - Browser: Chrome

**Comment by danielfmiranda** [comment]
Hi @cdanfon!

After some troubleshooting, I found that this was caused by the braintree environment variables being out of date, after copying them over from Braintree again the error is no longer there, and I am able to do test donations again 👍
