### ISSUE TITLE
DONATE | CSP Updates for Google Tag Manager

### ISSUE THREAD

**Issue by cdanfon** [mozilla/donate-wagtail#1673]
**Overview**
Content Security Policies are a common security device to prevent unintended content from being loaded into a website. Coincidentally, the whole purpose of Google Tag Manager is to load assets into a website.
So, in order to use Google Tag Manager in sites with a CSP in place, we need to make some slight changes to the GTM code added to sites, as well as add a few lines to the site security policy.

**Acceptance criteria**
- [ ] Update GTM code following instructions in this [document](https://docs.google.com/document/d/1IbfNfn0HUoJ94qDTWiwZjxWmy8ZzisyilGtxOhR5xNc/edit?usp=sharing)
- [ ] Update Content Security Policy following instructions in this [document](https://docs.google.com/document/d/1IbfNfn0HUoJ94qDTWiwZjxWmy8ZzisyilGtxOhR5xNc/edit?usp=sharing)
- [ ] Updates to be made both in staging and prod sites

**Cointainer IDs**
Foundation - GTM-MD3XGZ4
Donate - GTM-TCB2S5V
Mozfest - GTM-5TFTDCX

**Comment by cdanfon** [comment]
Hey @mtdenton this is the issue we've talked about during sprint planning today. Do you mind having a look at the issue and pasting here any questions/unknowns that need to be answered before we can carry out the work to complete this issue? Thanks!

**Comment by mtdenton** [comment]
If the code in the instructions above DO in fact generate nonces in both the CSP header and GTM script, then we're ready to rock. I'm wondering if it does in fact do that...

If not, and if we're using django-csp in Donate, here's some additional information on how to proceed with this:
https://django-csp.readthedocs.io/en/latest/nonce.html

We're also going to need to make some updates in GTM for certain tags (custom html come to mind). We'll need to pass along that nonce in a custom variable, dataLayer comes to mind.

**Comment by cdanfon** [comment]
@mtdenton Thanks for this! 

@danielfmiranda Is this something you can pick up as part of the Support duty please? We have some time booked with the Torchbox Digital Marketing team and unless this is up and running for them to test we will lose the time.

Thanks!

**Comment by cdanfon** [comment]
@mtdenton @danielfmiranda I've heard from our Digital Marketing team: 

The instructions above **won't** generate nonces.

The method to insert that into the GTM code would be up to you folks, GTM just needs to have that passed. It needs to be the same nonce both in the GTM snippet and in the script-src directive described right after in the document

Any questions shout!
