### ISSUE TITLE
catch exception ReadTimeoutError for Acoustic send

### ISSUE THREAD

**Issue by jzinner** [mozilla/donate-wagtail#1688]
## catch exception `ReadTimeoutError` for Acoustic send
During the Aug 4, 2022 Acoustic incident, the Papertrail logs (below) were captured off and a new uncaught exception was seen. 

> Aug 04 17:54:20 2022-08-04 17:54:20,028 [ERROR] requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='transact-campaign-us-6.goacoustic.com', port=443): Read timed out. (read timeout=10)
> Aug 04 17:54:20 urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='transact-campaign-us-6.goacoustic.com', port=443): Read timed out. (read timeout=10)
> Aug 04 17:54:20 acoustic_tx.send_mail(
> Aug 04 17:54:20 File "/app/donate/utility/acoustic/acoustic.py", line 138, in send_mail
> Aug 04 17:54:20 File "/app/donate/utility/acoustic/acoustic.py", line 115, in attempt_send_mail

## Expected behavior
Capture the exception `ReadTimeoutError` on line [140 of acoustic.py ](https://github.com/mozilla/donate-wagtail/blob/9b3d7b9b803f30d6db9352cb638083a8d82e6832/donate/utility/acoustic/acoustic.py#L140).  
For example:
`except (ConnectionError, ReadTimeoutError) as err:`

Also capture the exception message  (the `as err` above) and print it out if retries fail (in the else statement) so we continue to capture the context around the exceptions & since we will now processing more than one exception.

**Comment by cdanfon** [comment]
To be done as part of the support duty @danielfmiranda
