### ISSUE TITLE
 when opening TB with overdue tasks/events the calendar gets switched to readonly

### ISSUE THREAD

**Issue by eldersixpack13** [mozilla/donate-wagtail#1694]
**Describe the bug**
since switching to thunderbird-102.2.1-1.fc36.x86_64  I've the following error's/misbehavior:
when overdue task or events are pending and I open TB I get an reminder popup.
clicking "Dismiss All" switches the calendar to readonly, so I need to unselect the readonly flag in the calendar properties and restart TB in OFFline mode,  ... 

I need to mention I use a on the same box running radicale (radicale3-3.1.7-30.fc36) as a calendar provider.
all was flawlessly working before the update to TB 102.x !

**To Reproduce**
1. create a task/event in the past
2. close TB and open it again
3. in the reminder popup click "Dismiss all" => calendar switches to readonly
4. See screenshot (error box)

**Expected behavior**
opening TB with overdue task/event and "dismiss all" shouldn't set the calendar to readonly

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/83478572/188515870-4eb1c59e-9409-472c-a2ee-ed6fe419fec0.png)

**Desktop (please complete the following information):**
 - OS: Fedora 36

**Comment by TheoChevalier** [comment]
Hi,

This repository is only about the donation website, please do not file product-related bugs here. You can file Thunderbird bugs here: https://bugzilla.mozilla.org/enter_bug.cgi?product=Thunderbird

Thanks!
