### ISSUE TITLE
Thank you page

### ISSUE THREAD

**Issue by nicklee** [mozilla/donate-wagtail#18]
**Overview:**

Final step in the donation process, thanks the user for their donation and prompts them to share via their social networks.

**Design / Wireframe:**

Desktop: https://redpen.io/vr3ed558332f842713
Tablet: https://redpen.io/qgcd8ac4753ebe3c23
Mobile: https://redpen.io/dbf4cf795b2beec7c8

**Components that form this template:**

- [x] Title
- [x] Introductory text
- [x] Social share

**Comment by nicklee** [comment]
https://github.com/mozilla/donate-wagtail/pull/104

**Comment by nicklee** [comment]
Working on here https://github.com/mozilla/donate-wagtail/pull/124

**Comment by nicklee** [comment]
@beccaklam Am I correct in thinking this design is the final "thank you page"?

https://redpen.io/phbeb4557150be980e

The system currently outputs the following message:

Your transaction reference is: dqg47g

Not sure if we want to include this somewhere? perhaps just under the social links in small text?

**Comment by solarissmoke** [comment]
Just for context, this is the transaction ID generated by Braintree. It might be useful if a user needs to cancel or contact you about a payment (although I'm not sure how many users would retain it, unless you also include it in a thank you email).

**Comment by beccaklam** [comment]
@nicklee @solarissmoke It would probably be good to include it in the thank you email if the user wishes to change anything. But we could also include it on the last page, it would be good feedback that your transaction went through. What if we did a design like this? Similar to the 'change amounts' box:
![Screen Shot 2019-07-30 at 9 43 43 AM](https://user-images.githubusercontent.com/20977376/62134565-b3aca300-b2ae-11e9-9f3d-44fbf435b618.png)

cc: @alanmoo should we ask will and steph if they want to include the transaction ID in the thank you email?

**Comment by alanmoo** [comment]
We already pass the transaction ID to basket (where the emails get generated), though it’s usually a much larger string than your comp implies.

**Comment by nicklee** [comment]
Example on staging: https://donate-wagtail.mofostaging.net/en-us/thank-you/
