### ISSUE TITLE
Site-wide data models

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#19]
I propose to use site-wide settings to store the following:

- Legal footer text: rich text (required)
- Top navigation menu links: orderable sequence of link blocks that can link either to a page on site or to an absolute URL (required)
- Footer links: orderable sequence of link blocks that can link either to a page on site or to an absolute URL (required)
- Language code to currency mapping (as defined in #1).
- Currency information:
    - Code
    - Symbol
    - Allowed payment methods
    - Default donation amounts: for each currency, 4 default suggestion values for that currency.

It might be easier to store currency information in code instead - to make a call before starting work on this.

**Comment by solarissmoke** [comment]
I just realised that putting the legal footer text into a setting will complicate translations. If this text is not likely to change often then the simplest approach in my view is to hard-code it into the template, so that it can be translated in the normal way.

**Comment by alanmoo** [comment]
The top nav is only in English because the Foundation site itself is mainly only in English.

**Comment by solarissmoke** [comment]
I've been looking into how to store currency information, and feel that we're best off having a hard-coded dictionary very similar to [the current one](https://github.com/mozilla/donate.mozilla.org/blob/master/src/data/currencies.js). 

The rationale for this is that this data doesn't change frequently, and so it doesn't seem worth the cost of modeling in the database and making editable in Wagtail. 

@alanmoo @TheoChevalier does this sound OK to you?

**Comment by TheoChevalier** [comment]
@solarissmoke No issue on my side, thanks for asking :)

**Comment by solarissmoke** [comment]
Closing on the basis that we've ended up storing all of this information in code, so no site-wide models necessary at present.

**Comment by alanmoo** [comment]
Out of curiosity (because we might need it on our other Wagtail site) is there any documentation on best practices for site-wide model implementation?

**Comment by solarissmoke** [comment]
Yes - use `wagtail.contrib.settings`: https://docs.wagtail.io/en/v2.5.1/reference/contrib/settings.html
