### ISSUE TITLE
Set up sandbox accounts for payment processors

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#2]
We'll need sandbox accounts for:

1. Braintree
2. Paypal (merchant)
3. Paypal (buyer)

It might make sense for Mozilla to set these up and share access privately, so that you have these for development going forward.

**Comment by alanmoo** [comment]
What do we need the Paypal accounts for? I thought Braintree handled everything.

**Comment by solarissmoke** [comment]
@alanmoo Braintree wraps the Paypal API for us, but you still need to register your own Paypal Business account if you want to accept payment through Paypal: https://articles.braintreepayments.com/guides/payment-methods/paypal/setup-guide

Instructions for setting up linked sandbox accounts are here: https://developers.braintreepayments.com/guides/paypal/testing-go-live/python#linked-paypal-testing

**Comment by patjouk** [comment]
I'll probably be able to create a Paypal sandbox account but I can't do it for braintree (we're still waiting for approval).

**Comment by alanmoo** [comment]
Shouldn't we already have a Paypal sandbox, since we accept it now?

**Comment by patjouk** [comment]
I've created dedicated accounts for this contract. @solarissmoke do you have a keybase account so that I can send you the credentials?

**Comment by alanmoo** [comment]
Thread on configuration of the sandbox account to accept multiple currencies: https://mozilla.slack.com/archives/CKG36UDCG/p1569292998041600

**Comment by cadecairos** [comment]
The sandbox accounts are set up and wired to staging. additonal work can be filed as new issues.
