### ISSUE TITLE
Special case for URL routing/currency handling for some languages

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#202]
If my `Accept-Language` preference is for `es-MX`, I will get redirected to `es` because we don't have a Mexico-specific translation. But with this change, going to `/es/` means that the default currency suggested to the user will be EUR, not MXN, because we're only using the language prefix to determine this.

It looks like we have [a special case](https://github.com/mozilla/donate.mozilla.org/blob/9823bb7a671ede8a267e850faf00ff0f767db601/src/lib/get-messages.js#L5-L7) for this particular setup on the current site.

@TheoChevalier is this the only case that needs special treatment?

**Comment by TheoChevalier** [comment]
That’s correct, the snippet you highlighted is the only case on the current website
