### ISSUE TITLE
Campaign page model

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#21]
### Field spec

- Hero image: image field (required)
- Title: plain text (required)
- Lead text: plain text (required)
- ~Partner logos: orderable sequence of image fields (optional)~
- Default donation amount overrides: optional list of items mapping a currency to list of 4 suggested donation amounts. 

### Notes

- If a currency is not listed in the donation amount overrides, then we will fall back to the [global defaults](https://github.com/mozilla/donate-wagtail/issues/19).
- Legal text is fetched from global configuration (i.e., does not vary per-campaign).

**Comment by alanmoo** [comment]
Sounds good, other than the [partner logos](https://github.com/mozilla/donate-wagtail/issues/20#issuecomment-510226718)
