### ISSUE TITLE
Ensure correct Paypal account is used based on donation amount

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#211]
Apparently it's a well known workaround for Paypal's fees that it's useful to have two different accounts- one for smaller transactions, and one for larger ones. We previously implemented this [here](https://github.com/mozilla/donate.mozilla.org/blob/master/server/lib/paypal-account-switcher.js) and should do the same in this project.

**Comment by solarissmoke** [comment]
I'm not sure this is possible with Braintree @alanmoo - seems you can only associate one Paypal account with one Braintree account. Think this is one to discuss with Braintree.

**Comment by alanmoo** [comment]
@solarissmoke Where did we end up on this one? I know we discussed it in Slack, but I'm not finding any follow up on it. https://mozilla.slack.com/archives/CKG36UDCG/p1567001045004200

**Comment by solarissmoke** [comment]
@alanmoo I had suggested you talk to Braintree to confirm whether the "marketplace account" is the approach we need to take - were you able to do that? Once that is confirmed we'll need to ask him to help set up the sandbox to use this setup, so that we can test. There are code changes required as well.

**Comment by alanmoo** [comment]
According to that Slack conversation, it seemed like yes, but I've reached out again to confirm.

**Comment by alanmoo** [comment]
From Braintree:

>I believe you're referring to your PayPal Express accounts? With Braintree, it is possible to enable multiple PayPal accounts underneath a single Braintree gateway. Albeit, from a development perspective, it will require some custom work to direct transactions to each corresponding account (micro tx versus standard tx).

**Comment by solarissmoke** [comment]
@alanmoo your last comment adds to the confusion I'm afraid - would be good if we could get clarity from Braintree on specifically how to enable multiple Paypal accounts underneath a single gateway - i.e., what steps do we need to take to do this?

**Comment by solarissmoke** [comment]
Just to formally log the request on Slack:

In the sandbox, you can only associate a Paypal account with the whole Braintree account - not with individual merchant accounts. i.e., once you have associated a Paypal account it is used for all merchant accounts configured on the Braintree account. I cannot find a way to associate a different Paypal account to individual merchant accounts.

What would be really helpful is if you're able to configure your sandbox to link two different Paypal accounts as they describe? We can then make sure the code supports this.

**Comment by alanmoo** [comment]
I'm looking into this; I had some guidance from Braintree but the reality of the dashboard seems to not match that documentation.
