### ISSUE TITLE
Pass data from Braintree webhooks to Basket

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#216]
As per discussions on slack there is a need to collect some information from Braintree webhooks and relay this to Basket. 

## Information required

1. What information needs to be collected? For subscriptions, Braintree can send [a variety of different kinds of notifications](https://developers.braintreepayments.com/reference/general/webhooks/subscription/python#notification-kinds). Which of these are we interested in?

- Subscription cancelled.
- Subscription charged successfully.
- Subscription charged unsuccessfully.
- Subscription expired.

2. What is the data structure expected by Basket for each of the different kinds of event that we need to listen to?

**Comment by alanmoo** [comment]
@WillatMozFdn Can you comment on point 1? I'm guessing it's mainly `Subscription charged successfully` and I need to reach out to Braintree about refunds.

**Comment by WillatMozFdn** [comment]
@alanmoo ^^ that seems correct to me but I need to defer to our deity of data, Steph McVicker, on this one.  Can't seem to tag her ... is she not in this repo?

**Comment by alanmoo** [comment]
She is now. @stephaniemcv

**Comment by alanmoo** [comment]
Actually, looking at the function definitions in [this file](https://github.com/mozmeao/basket/blob/6228e47b6ea9c429161320ed33c2d96ff55344f3/basket/news/tests/test_tasks.py#L223), it looks like we've got hooks for a bunch of events. @pmac am I looking at the right thing?

**Comment by pmac** [comment]
Yes. Several different event types are sent to basket and we update the donation records accordingly.

**Comment by alanmoo** [comment]
Great. @solarissmoke does that section of code answer your question?

**Comment by solarissmoke** [comment]
Yes, thanks. Note that Braintree doesn't provide webhooks for refunds, so we will not be able to pass this information to Basket. The rest look fine.

**Comment by alanmoo** [comment]
Right. I've reached out to Braintree to ask if there's any way to get refund info into our CRM.

**Comment by alanmoo** [comment]
Found during QA: I'm not actually seeing "subscription charged successfully" webhooks hitting Basket. From the look of [this class](https://github.com/mozilla/donate-wagtail/blob/master/donate/payments/tasks.py#L61) it seems like that behavior isn't picked up.

@philwakefield

**Comment by solarissmoke** [comment]
@alanmoo Can you give me a specification for what data basket expects for successful charges? The [tests you had linked to earlier](https://github.com/mozmeao/basket/blob/6228e47b6ea9c429161320ed33c2d96ff55344f3/basket/news/tests/test_tasks.py#L223) don't include a test for successful charges, and I can't find anything else in the code base there that hints at what is required.

**Comment by solarissmoke** [comment]
This spec is especially required in the context of #459, because presumably you need more than just the transaction ID and event type if Basket has never seen this subscription before (i.e., it has no record of customer name/email etc).

**Comment by solarissmoke** [comment]
Never mind, I've found the code on the current site that gives me what I need.

**Comment by alanmoo** [comment]
We got a Sentry error on this on Staging/Sandbox. (I'll forward it to you via email as it's easier to read)

>ExceptionAttributeError: 'str' object has no attribute 'get' (1 additional frame(s) were not displayed) ...   File "rq/job.py", line 605, in perform     self._result = self._execute()   File "rq/job.py", line 611, in _execute     return self.func(*self.args, **self.kwargs)   File "donate/payments/tasks.py", line 111, in process_webhook     BraintreeWebhookProcessor().process(notification)   File "donate/payments/tasks.py", line 67, in process     return process_method(notification)   File "donate/payments/tasks.py", line 75, in process_subscription_charged_successfully     'campaign_id': last_tx.custom_fields.get('campaign_id', ''),

**Comment by solarissmoke** [comment]
@alanmoo this error confirms what I had suspected, that the transaction doesn't include the custom fields stored on the customer. I found a somewhat convoluted way to find the customer and grab the custom fields from there (#511), so this should work now. Could you please test again?

**Comment by alanmoo** [comment]
Yup, that seems to work!
