### ISSUE TITLE
Lock Wagtail edits of translated content

### ISSUE THREAD

**Issue by philwakefield** [mozilla/donate-wagtail#238]

**Comment by alanmoo** [comment]
@TheoChevalier is this still a thing?

**Comment by TheoChevalier** [comment]
I think this may be already done — right now editing localized pages only allows slug edition. Which we shouldn’t be able to update either. @kaedroho are we all covered here?

This shouldn’t be blocking anyway, as for now, we should all remember to only ever edit English.

**Comment by Pomax** [comment]
closing as highly out of date
