### ISSUE TITLE
QA: Analytics

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#259]
Master QA ticket for analytics.

If an item is not completely passing, file a new ticket and edit this post to link to it. For example:
- [ ] A thing that should work, but doesn't (#1234)

Any QA tickets that don't show a reference from a master issue will be closed.

- [ ] Google Analytics is functional and capturing data
- [ ] No PII is going into GA
- [ ] Logging and error handling (Are things hooked up to let us know when breakages happen?)
- [ ] OG sharing works as expected

@xmatthewx what else am I missing?

**Comment by xmatthewx** [comment]
Looks good. As long as we can see a link between referrals/ads --> landing page --> goal completion, I think we'll be golden.

**Comment by cadecairos** [comment]
We're not putting any PII in the URL, like we were on the old donate stack, so we're not going to run into a problem there.
