### ISSUE TITLE
Single to monthly payment upsell

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#26]
Implementation of a workflow to enable donors to set up a monthly payment having just completed a single payment.

### Technical notes

Braintree requires a slightly different approach for setting up subscriptions - specifically creating subscriptions requires [vaulting](https://articles.braintreepayments.com/control-panel/vault/overview) of a payment method.

The options here are:

1. Vault all payments (including single), so that we don't have to ask for this information again at point of upsell.
2. Don't vault single payments, in which case the user would have to go through the process of entering their details again at point of upsell.

(2) obviously makes for poor user experience, so I think (1) is the preferred option - we just need to investigate what the implications are of vaulting one-off payments (if any) and whether the Paypal flow for vaulting is more involved (if so there may be a more nuanced tradeoff that we need to make a decision on).

**Comment by philw-torchbox** [comment]
Agree option 2 is best user option so need to understand both implication of using Vaulting and priority of upsell to MoFo.

**Comment by philw-torchbox** [comment]
Not clear where the Upsell screen appears in the process as it appears to be a 2 step thank you for single payments i.e. Upsell (get info for ongoing payment) and then thank you (get email address). There is a risk here of significant drop off and not getting the email address. Need clarity fo the priority of the email address over Upsell for long term engagement.

**Comment by alanmoo** [comment]
@philw-torchbox I assume you meant option 1 in your first comment?

I believe we had a conversation elsewhere, but I confirmed with Will that the priority here is definitely the upsell. A lot of our donations come from our mailing list already, so many of the donors won't even see the ask for newsletter subscriptions. (As we hide the ask if someone comes in with a query string of `subscribed=true` and then code that into the links sent out in emails)

**Comment by solarissmoke** [comment]
I have been doing some due diligence on this while setting up the basic integrations. I don't see any issues with card upsell, but for Paypal a separate auth flow is required if you want to be able to set up a monthly subscription for a customer. Here is what the donor sees when making a single payment:

![image](https://user-images.githubusercontent.com/160227/61432661-caabd680-a939-11e9-8406-1f3a51ae81a3.png)

And here is what they see if we are setting up a subscription:

![image](https://user-images.githubusercontent.com/160227/61432774-19597080-a93a-11e9-9909-7e9214d1f878.png)

it is possible to use the latter flow for single payments (in which case upsell is easy), but this means the donor is giving consent for recurring payments even if they only intend to make a single payment. I think there is a risk of upsetting people with that. 

The alternative would be to ask the user to go through another auth flow at the point of upsell. They would already be logged in to Paypal at this point, so it wouldn't be a very lengthy process.

**Comment by alanmoo** [comment]
I double-checked my gut and confirmed with Will. Go with the alternative you presented: Different flow based on OTG and recurring, with a second auth flow for upsell.

**Comment by solarissmoke** [comment]
@alanmoo on the current site, monthly upsell is only displayed for a small number of currencies (those with `upgradeMonthly` [defined here](https://github.com/mozilla/donate.mozilla.org/blob/master/src/data/currencies.js)). Could you confirm whether the same logic applies here, and the basis for this? Is it because Stripe didn't support subscriptions in the other currencies?

**Comment by alanmoo** [comment]
I believe it was a technical limitation, but I'll confirm.

**Comment by alanmoo** [comment]
This was partially due to the fact that we could only accomplish upsells with Stripe, combined with effort to put it in place for other currencies. 

From Will:
>If we got it on USD, EUR, GBP, CAD, AUD and CHF, I think we'd have ~95% coverage of how our donors give.  (Not necessarily in number of donations, but in overall income, which in this case is more important.)

**Comment by solarissmoke** [comment]
From what I can see Braintree doesn't document any restrictions on which currencies you can set up subscriptions for - it's just that you have to manually set up a plan for each currency that you want to support. So technically it is possible for us to support all currencies.

@alanmoo what is your preference at this stage? Should we support all or limit to the ones listed by Will above?

**Comment by alanmoo** [comment]
Support all, if it's no more work than putting in default amounts. (Do you need those or is that configurable in an admin panel? Either way, I'll get that info for you.)

**Comment by solarissmoke** [comment]
The default amounts are [currently hard-coded](https://github.com/mozilla/donate-wagtail/blob/master/donate/payments/constants.py). 

Rather than having to define upgrade amounts for every single currency, I would suggest that we define a sensible set of defaults (i.e., for single payment of X, suggest monthly donation of Y, regardless of currency), and use these for any currency where `monthlyOverride` isn't specified. Does this sound OK to you?

**Comment by alanmoo** [comment]
Sounds good. Will is working on identifying what currencies from the list in #72 need overrides.

**Comment by alanmoo** [comment]
https://docs.google.com/spreadsheets/d/1QHgqfDkSkN_5rW2j4K1Xf5mNLK71tT4C9QREhmgqYxI/edit?usp=sharing

**Comment by solarissmoke** [comment]
@alanmoo I'm bringing the [discussion on #97](https://github.com/mozilla/donate-wagtail/pull/97#discussion_r307590833) here. Regarding minimum amounts, can you confirm:

1. Whether you want to skip monthly upsell entirely if the single amount was below some threshold? or

2. You want to upsell some predefined minimum amount if the single amount was low?

In either case I think we will need to specify a threshold for all currencies - or skip upsell entirely for those currencies where we don't have this specified.

**Comment by solarissmoke** [comment]
In addition to the above query @alanmoo , are there any other situations in which upsell should be skipped?

**Comment by WillatMozFdn** [comment]
Hey @solarissmoke ... 
A. No upsell at all if the one-time gift is below the one-time gift doesn't hit the minimum (in column M of that spreadsheet)
B. Yes, I can extend that spreadsheet tio those other currencies -- will get that filled out for you this morning;
C. Can't think of any other situations (other than didn't hit the minimum) where we should skip upsell.
Thanks!

**Comment by WillatMozFdn** [comment]
@solarissmoke on B above, that's now filled out, [here](https://docs.google.com/spreadsheets/d/1QHgqfDkSkN_5rW2j4K1Xf5mNLK71tT4C9QREhmgqYxI/edit#gid=0).
