### ISSUE TITLE
Website crashes when donating from a non-English browser

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#260]
STR:
- Download a non-English browser (e.g. a French build of Firefox Nightly https://www.mozilla.org/en-US/firefox/nightly/all/?q=french )

- Try to make a donation using fake data (here’s what I used)

![Screenshot_2019-09-23 Your information](https://user-images.githubusercontent.com/1294206/65435243-7e40b380-de20-11e9-99ea-fea2e8f783f8.png)
![Screenshot_2019-09-23 Your information(1)](https://user-images.githubusercontent.com/1294206/65435244-7e40b380-de20-11e9-9fe5-60d1d73e3e53.png)

You land on: https://donate-wagtail.mofostaging.net/fr/card/single/?source_page_id=3&currency=eur&amount=50

And the page says: “We’re sorry! Our server is acting up right now. Please try again soon.
Internal Server Error (500)”

Console output:
16:35:34,356 Échec du chargement pour l’élément <script> dont la source est « https://c.paypal.com/da/r/fb.js ». hosted-fields-frame.min.html:1:1
16:35:34,374 Error: https://c.paypal.com/da/r/fb.js failed to load. hosted-fields-frame.min.html:1:1499
16:35:34,447 POSThttps://donate-wagtail.mofostaging.net/fr/card/single/?source_page_id=3&currency=eur&amount=50
[HTTP/1.1 500 Internal Server Error 1886ms]

16:35:36,500 GEThttps://donate-wagtail.mofostaging.net/favicon.ico
[HTTP/1.1 404 Not Found 326ms]

**Comment by alanmoo** [comment]
(Théo mentioned he re-tested this without using the diacritic, and it still failed. So it seems like a separate issues from #260)

**Comment by solarissmoke** [comment]
I'm pretty sure this is the limitation mentioned on Slack - that Braintree is currently only set up to accept payments in USD or GBP. All other currencies will fail as you've described above.

**Comment by TheoChevalier** [comment]
Ah, wasn’t aware of this… Then yes, this is definitely the issue. Sorry for the false alarm!
