### ISSUE TITLE
Donation fails when data contains diacritics

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#261]
Trying to make a donation from a en-US browser (because of #260 ), with the following data:

![Screenshot_2019-09-23 Your information](https://user-images.githubusercontent.com/1294206/65439943-48073200-de28-11e9-84c7-d277b3ff4ef1.png)

The page reloads and the following error message appears:

<img width="777" alt="Capture d’écran 2019-09-23 à 17 34 20" src="https://user-images.githubusercontent.com/1294206/65440032-69681e00-de28-11e9-8406-2caa5cfa73e8.png">

Trying again, but replacing `é` with `e` in my firstname, and this time everything works properly. I assume the error occurs with more fields than just the firstname.

**Comment by TheoChevalier** [comment]
We will also want to test this against a bigger set of Unicode characters, not just the ones with diacritics

**Comment by solarissmoke** [comment]
I'm not able to reproduce this with unicode characters in either first or last name - both work fine. I suspect testing is being [confounded by using a currency that isn't set up yet](https://github.com/mozilla/donate-wagtail/issues/260#issuecomment-534357323) - suggest we resolve that first and then test again.

**Comment by TheoChevalier** [comment]
I can confirm this was related to the default currency not being USD/GBP, let’s close
