### ISSUE TITLE
Push transaction data to SQS

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#27]
Push data about completed transactions to SQS. 

### Information required

1. API for pushing data to SQS.
2. What information should be sent and its structure.

### Technical notes

My initial thoughts for implementation are that this should be done asynchronously via a worker process. 

There is an open question about how much resiliency is required in terms of retrying failed push, and whether we need to store basic transaction data (a Braintree reference number) in Wagtail as a fallback.

**Comment by philw-torchbox** [comment]
What are the implications of having to store the Braintree ref no? Is there a data protection or security concern by having this in our system?

**Comment by solarissmoke** [comment]
I don't think that storing the transaction reference should be a problem - doesn't tell you anything about the transaction itself.

**Comment by patjouk** [comment]
1. Our current donate platform talks to [SQS directly](https://github.com/mozilla/donate.mozilla.org/blob/master/server/lib/basket-queue.js). You might be able to use [boto3](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/sqs-example-sending-receiving-msgs.html) for that. Doing it asynchronously is a good idea.

2. [Basket has a donate process](https://github.com/mozmeao/basket/blob/master/basket/news/management/commands/process_donations_queue.py) that looks for different event types: `donation`, `crm_petition_data` (@alanmoo do we need this one?), `newsletter_signup_data`, and `DEFAULT` (probably a catch-all, I'll ask around). I couldn't find a doc for the message structure, so I'm asking people around. Meanwhile, we can get a good idea of what basket expects from the code:

- [donations](https://github.com/mozmeao/basket/blob/4d0668d4e5cb304e68b04bcc0d2b278d27b591e6/basket/news/tasks.py#L1076)
- [DEFAULT](https://github.com/mozmeao/basket/blob/4d0668d4e5cb304e68b04bcc0d2b278d27b591e6/basket/news/tasks.py#L970)

I'll add more if I manage to put my hands on some docs.

**Comment by solarissmoke** [comment]
Thanks. Yes, we will do this async. 

I think we can probably pick out the data structure from the code you've linked to, but it would be helpful to have a written spec that we can refer to. If you don't find any docs then I will write up a spec based on the code.

**Comment by alanmoo** [comment]
I've got a call tomorrow morning (US) that touches on the approach for this, so hopefully I'll have more details by Thursday.

**Comment by alanmoo** [comment]
Lucie's got a [PR open](https://github.com/mozilla/donate-wagtail/pull/88) to document  some Basket things, but for extra data that we're going to be sending from Braintree to Basket, you can define the keys that need to be added to the package and support for them will get added by the Basket team.

**Comment by solarissmoke** [comment]
Is there a possibility of setting up sandbox SQS/Basket instances so that we can test end-to-end data flows? Based on where we are currently, I should be able to have an initial pass at the SQS data push ready next week.

**Comment by alanmoo** [comment]
Is this still blocked?

**Comment by patjouk** [comment]
Yes, because there's the question of the "net amount" field. When we have an answer there, we will need to ask Pmac to do the necessary changes on basket side: I guess it will be easier to add a temporary event type so that both donate platforms can work side to side and do a switch on launch day.

**Comment by alanmoo** [comment]
Ok. I'm waiting to hear back from Braintree about that.

**Comment by alanmoo** [comment]
I think I've mentioned this elsewhere, but we're not going to be dealing with "net amounts" from Braintree, and the stakeholders are fine with that. Based on the API I [spec'd out](https://docs.google.com/document/d/1x7SF5XUPYYyEGkv3c1GxArIBiqfYby6eSobif5BSpsc/edit), we should be able to start passing data to Basket as it stands, and then improve Basket to be able to handle any new data that's coming in.

**Comment by solarissmoke** [comment]
Thanks. We should already be sending data to Basket (see https://github.com/mozilla/donate-wagtail/pull/203#issuecomment-523438477) but will need a bit of time/help from someone with access to the SQS queue and the Basket back end to help us verify that this is working correctly - we have no visibility on errors once the data is sent to SQS.

**Comment by alanmoo** [comment]
@cadecairos or @patjouk can one of you sync up with Samir to find a time for solving this?

**Comment by solarissmoke** [comment]
I'm going to close this on the basis that we are now successfully passing data to SQS - let's open new issues for specific data structure issues after you've tested.
