### ISSUE TITLE
Load Testing

### ISSUE THREAD

**Issue by cadecairos** [mozilla/donate-wagtail#270]
* https://locust.io
* Write script to simulate a user making a donation,
* set it up to run distributed
* Test some number of users (actual number TBD)

Test scripts will live in a different repo, to be created still.

**Comment by solarissmoke** [comment]
Note, we'll need to upgrade to standard dynos (currently on hobby) on Heroku before doing this.

**Comment by cadecairos** [comment]
OK. ran some load testing!

![image](https://user-images.githubusercontent.com/438003/65792880-ad159d00-e132-11e9-86e1-9858535fb98d.png)
 
Pretty bad results. I added auto scaling with Hirefire, and set the WEB_CONCURRENCY value on each dyno to 6 (6 gunicorn workers instead of just 1), and now I'm seeing some much better results:

![image](https://user-images.githubusercontent.com/438003/65800213-e73b6a80-e143-11e9-91b6-53e3d816849a.png)

There are a few weird hiccups in the graph, but things recovered, and the eventual point of failure was the Redis server reached it's connection limit (80).

So the take-aways here are:

- set `WEB_CONCURRENCY` to 6 (for standard 1x dynos)
- Scaling should be set with roughly this configuration: monitor the p95 request time, scale when it's above 5000, with a 5 minute scaling timeout.
- Ensure the redis add-on can accept enough connections. the Premium 1 plan provides 80 connections but that wasn't enough in this test (that said, I doubt we'll hit 65 requests/second)
