### ISSUE TITLE
Enable support for Braintree's advanced fraud tools

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#272]
We need AFT on for our account: https://developers.braintreepayments.com/guides/advanced-fraud-tools/configuration

**Comment by philwakefield** [comment]
@solarissmoke please confirm status of this. Not clear on ticket

**Comment by solarissmoke** [comment]
@philwakefield awaiting code review.

**Comment by solarissmoke** [comment]
This is now in place. You can test on sandbox using the [test card number provided here](https://developers.braintreepayments.com/guides/advanced-fraud-tools/testing-go-live/python) - which should result in a failed payment.

There are some important notes to be aware of [about testing in production](https://developers.braintreepayments.com/guides/advanced-fraud-tools/testing-go-live/python#test-transactions-in-production).
