### ISSUE TITLE
Fixing Footer UI on Donate

### ISSUE THREAD

**Issue by beccaklam** [mozilla/donate-wagtail#273]
The footer on the donate site is looking good but there are still some tweaks to the UI that need to be made:

**Image for reference:**
<img width="1253" alt="Screen Shot 2019-09-27 at 11 31 45 AM" src="https://user-images.githubusercontent.com/20977376/65781851-6ae06180-e11a-11e9-8d75-8cbd1aad1846.png">

**List of requirements**
- [x] background colour for the footer should be #000000 instead of #111111
- [x] Increase margin/padding below 'Protect the internet ...' to 24px
- [x] Increase margin/padding below 'Join our email list ...' to 24px
- [x] Increase margin/padding below email signup form field to 16px
- [x] The sign up button should share the same row as the form field and occupy 3 columns with 16px spacing between itself and the form field
- [x] _All_ text, except for links, should be white #ffffff at full opacity
- [x] All links should be #269 B7B9FA (as well as hover states for Donate, Legal, License, Participation Guidelines and Privacy)
- <img width="500" alt="Screen Shot 2019-09-27 at 11 32 32 AM" src="https://user-images.githubusercontent.com/20977376/65781901-88adc680-e11a-11e9-8f78-ecdecb68c6d2.png">
- [ ] The language picker is missing @alanmoo is that within scope of this project?

<img width="1253" alt="Screen Shot 2019-09-27 at 11 31 45 AM" src="https://user-images.githubusercontent.com/20977376/65781851-6ae06180-e11a-11e9-8d75-8cbd1aad1846.png">

For further reference, the footer on https://foundation.mozilla.org/en/ is exactly how the footer should be

**Comment by youriwims** [comment]
@beccaklam if the background color of the `footer` should be `#000000` instead of `#111111` can you add that to your list here as well? Let me know, then I can close #310.

**Comment by beccaklam** [comment]
> @beccaklam if the background color of the `footer` should be `#000000` instead of `#111111` can you add that to your list here as well? Let me know, then I can close #310.

Added that ☝️ to the list of requirements @youriwims :)

**Comment by youriwims** [comment]
Great, thanks! :)

**Comment by nicklee** [comment]
Fixed all of the above in https://github.com/mozilla/donate-wagtail/pull/392

**Comment by beccaklam** [comment]
@nicklee Footer is looking great! Some small tweaks:

## Desktop
- [ ] This is my fault, but on the sketch file the spacing _was_ 24px but on the foundation site it looks like we're using 16px spacing. Could you update it to that instead?
- [ ] Also the link in bottom right hand corner should be to foundation.mozilla.org and in the #b7b9fa colour

**Change to:**
![footer](https://user-images.githubusercontent.com/20977376/66142794-1cc4d580-e5d4-11e9-9e81-d94ef44d589d.jpg)

## Mobile
- [ ] The sign up button actually becomes full width below the sign up field form on mobile

**Current:**
![Screen Shot 2019-10-03 at 11 52 30 AM](https://user-images.githubusercontent.com/20977376/66142920-4da50a80-e5d4-11e9-9087-fd820df31f27.png)

**Change to:**
![Screen Shot 2019-10-03 at 11 48 03 AM](https://user-images.githubusercontent.com/20977376/66142940-572e7280-e5d4-11e9-895e-cf3378a6fd0e.png)
