### ISSUE TITLE
Add 'per month' label to buttons when monthly is selected

### ISSUE THREAD

**Issue by beccaklam** [mozilla/donate-wagtail#275]
# Changes needed:
- [ ] Can we also add 'per month' label to each donate button when 'monthly' is selected. I remember samir had demoed this behaviour before but on staging it seems to be gone 

## Current:
<img width="340" alt="Screen Shot 2019-09-27 at 2 13 04 PM" src="https://user-images.githubusercontent.com/20977376/65792069-f6fd8380-e130-11e9-83c8-f3f78c15af1b.png">

## Change To:

**Mobile:**
![Screen Shot 2019-09-27 at 2 10 28 PM](https://user-images.githubusercontent.com/20977376/65791939-b7cf3280-e130-11e9-8acb-975871940992.png)

**Desktop:**
![Screen Shot 2019-09-27 at 2 15 22 PM](https://user-images.githubusercontent.com/20977376/65792212-43e15a00-e131-11e9-93f7-f5b62abe4a40.png)

**Comment by TheoChevalier** [comment]
I’m expecting a lot of truncation issues with the proposed button layout, some amounts are quite longer.
Here’s an example:

![Capture d’écran - 2019-09-30 à 10 55 43](https://user-images.githubusercontent.com/1294206/65863776-0ff47780-e371-11e9-825e-25939d4d09e6.png)

**Comment by beccaklam** [comment]
@TheoChevalier Oh sorry Theo, the QA wasn't for having three buttons in a row vs two, it was to fix how the other amount form field was styled. I'll fix the comp to clear up any confusion though.

**Comment by TheoChevalier** [comment]
Gotcha @beccaklam , my bad! :)

**Comment by nicklee** [comment]
Fixed, the per month text was being added via js, but only when the currency was changed, not on initial load. I've now added it for the initial load.

**Comment by beccaklam** [comment]
Thanks @nicklee, it's looking good! Would we be able to style it with 'per month' sitting below the dollar amount? I'm afraid that there are some use cases where the button may 'break':
![Screen Shot 2019-10-03 at 10 46 28 AM](https://user-images.githubusercontent.com/20977376/66137428-12eaa480-e5cb-11e9-99e1-914ffde97efe.png)

So like this:
![image](https://user-images.githubusercontent.com/20977376/66137455-1d0ca300-e5cb-11e9-9bfa-4875b0378448.png)

**Comment by nicklee** [comment]
Per month has been moved to a seperate line in https://github.com/mozilla/donate-wagtail/pull/414

**Comment by beccaklam** [comment]
Looks great! Thank you!
