### ISSUE TITLE
Fix Change Amount Button

### ISSUE THREAD

**Issue by beccaklam** [mozilla/donate-wagtail#276]
# Changes needed:
- [ ] The change amount button was originally designed to be the full width of the change amount field. However, I'm thinking we could style it closer to how we handle the footer with the button being on the same row as the form field. The button's width should be about 30% of the whole div with 16px spacing between itself and the form field:
<img width="631" alt="Screen Shot 2019-09-27 at 3 29 50 PM" src="https://user-images.githubusercontent.com/20977376/65796840-ab9ca280-e13b-11e9-9223-3ce560b2899a.png">

**Comment by mmmavis** [comment]
Hey @kristinashu , I'm trying to find tickets for Daniel to work on. The live page looks different than Becca's screencap from 2019. Is this ticket still valid?

1. Go to https://donate.mozilla.org/en-US/card/monthly/?source_page_id=3&currency=usd&amount=20&monthly-amount-other-input=
2. Click on "Change Amount"

<img width="777" alt="image" src="https://user-images.githubusercontent.com/2896608/111518526-62ffed00-8713-11eb-93ac-446c8cf2e226.png">

**Comment by kristinashu** [comment]
Her screencap is how she wants it to look (not how it currently looks on prod). So yes, it still seems relevant to move the button inline with the field.

**Comment by mmmavis** [comment]
Got it!

**Comment by danielfmiranda** [comment]
Hi @kristinashu!

I had a question about the layout for these buttons on mobile, should it remain inline like so?

<img width="363" alt="Screen Shot 2021-03-29 at 8 50 55 PM" src="https://user-images.githubusercontent.com/18314510/113031609-c5a9ad80-9143-11eb-81d0-c37954186791.png">

Or, should it be full width like so:

<img width="363" alt="image" src="https://user-images.githubusercontent.com/18314510/113031944-233dfa00-9144-11eb-956b-e8c3362c109e.png">

Thank you!
