### ISSUE TITLE
UI fixes for Android main donate page

### ISSUE THREAD

**Issue by beccaklam** [mozilla/donate-wagtail#278]
# Changes needed:
- [ ] The radial buttons on Android seem to be lacking some definition? Tested on browser stack on a Galaxy S7:
![Screen Shot 2019-09-30 at 10 41 33 AM](https://user-images.githubusercontent.com/20977376/65889311-1124a500-e36f-11e9-9146-f43bc96b490d.png)

The colours don't have to match exactly but can we have it look more closely to this:
![Screen Shot 2019-09-30 at 10 43 57 AM](https://user-images.githubusercontent.com/20977376/65889420-39ac9f00-e36f-11e9-9d06-41d6173f9bd1.png)

**Comment by philwakefield** [comment]
@nicklee investigate browser behavior

**Comment by nicklee** [comment]
Fixed

**Comment by nicklee** [comment]
![Screenshot 2019-10-04 at 13 09 44](https://user-images.githubusercontent.com/298766/66206529-43ecd700-e6a8-11e9-8277-f5ff9ff5dfac.png)

**Comment by beccaklam** [comment]
@nicklee Have these changes been merged? I don't see ☝️ on an S7 on Firefox in Browserstack

**Comment by nicklee** [comment]
@beccaklam  Ah firefox, I believe we tested it in the samsung default browser, that could be the issue, back me to check.

**Comment by benhohner** [comment]
Verify if still exists

**Comment by danielfmiranda** [comment]
Hi @benhohner after looking into this issue, I believe it has been resolved. 

Here is a screenshot from firebox browser for android:
<img width="351" alt="image" src="https://user-images.githubusercontent.com/18314510/112069034-52db7980-8b28-11eb-99c5-0d12d8719358.png">

Here is how it looks for default android browser/chrome as well: 
<img width="351" alt="image" src="https://user-images.githubusercontent.com/18314510/112069151-8d451680-8b28-11eb-915a-77a7cba1292e.png">

Devices also tested (android default browser/firefox):

- Galaxy s7/s8/s10/s20/s21
- Pixel 5/4
- OnePlus 8
