### ISSUE TITLE
Town does not get auto-filled

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#279]
<img width="790" alt="No-autofill" src="https://user-images.githubusercontent.com/1682681/65889319-1550c280-e36f-11e9-8311-8d729553cdbe.png">

Using autofill (Safari 12.1.2, MacOS 10.14.6), filling in from my touch bar doesn't autofill the city.  It does work on the existing donate stack in Safari, and autofill does seem to work in Firefox on donate-wagtail though.

Could this be related to the field being called "town", not "city"? (@beccaklam @WillatMozFdn @TheoChevalier any opinions on that?)

**Comment by WillatMozFdn** [comment]
This field definitely should not be called "town" ... perhaps that's a nice localization point for EN-GB users if we can get to it later, but, "City" is the far-better-known term for US donors (where ~70% of our donations come from), and is the field label currently in use on our donate page (and also that of virtually every other nonprofit donation page I've seen in recent memory).  TLDR, please change this label to "City."

**Comment by TheoChevalier** [comment]
> This field definitely should not be called "town" ... perhaps that's a nice localization point for EN-GB users if we can get to it later, but, "City" is the far-better-known term for US donors (where ~70% of our donations come from), and is the field label currently in use on our donate page (and also that of virtually every other nonprofit donation page I've seen in recent memory). TLDR, please change this label to "City."

This string is `en-US` only, and we’re only writing source copy in en-US anyway. en-GB localizers are responsible for changing it to “Town” for the en-GB locale if they see fit.

I’ll go ahead and change the label copy, however this will probably not fix the issue described above, as the field name and Label are different things. And I’m guessing Safari relies on the former.

**Comment by alanmoo** [comment]
Yeah, I recognize this could be out of our control but wanted to flag it in case it's not.

**Comment by beccaklam** [comment]
The designs had city, so not sure where town came from! I have no opinions on this 🤷‍♀

**Comment by philwakefield** [comment]
@alanmoo we will change the label and field name to 'City'

**Comment by solarissmoke** [comment]
We have changed the field name to `city`, which should now work with autocomplete. As noted above the label can be controlled for specific locales by changing the translations for those locales.
