### ISSUE TITLE
Make 'other amount button' full width

### ISSUE THREAD

**Issue by beccaklam** [mozilla/donate-wagtail#280]
# Changes needed:
- [ ] Can we make the 'other amount' form field the full width of the buttons above?
![Screenshot_2019-09-30 Fighting Back Against Misinformation](https://user-images.githubusercontent.com/20977376/65889876-facb1900-e36f-11e9-82bd-a6d57dd0aed7.jpg)

**Comment by nicklee** [comment]
This one depends on how many fields are used, in my example I have 4, so it aligned nicely. Feels like this one might need more thought?

<img width="1378" alt="Screenshot 2019-10-03 at 14 50 50" src="https://user-images.githubusercontent.com/298766/66133679-fd877180-e5ee-11e9-9575-cc52e3583d58.png">

**Comment by beccaklam** [comment]
Hmm, good point and this seems related to #283. It appears that using four donate options fixes both problems and that Alan is suggesting that if the donation team wants to use 3 options we do some special CSS for them then. @alanmoo am I getting this right? If so I'll close this ticket.

**Comment by alanmoo** [comment]
More like we should have a general behavior for what happens with the options and code for that. I.E. Does a dangling preset amount button get bigger? Does the custom amount one shrink?

**Comment by beccaklam** [comment]
@alanmoo @nicklee I think it may be preferable to do a mix of both depending on the view if possible:
If a preset amount is dangling we expand the largest amount:
![Screen Shot 2019-10-04 at 10 48 45 AM](https://user-images.githubusercontent.com/20977376/66217395-367a2180-e695-11e9-920a-8eeb216cd119.png)
Shrinking the custom amount would cause spacing issues if it's already this tight in english:
![Screen Shot 2019-10-04 at 10 51 37 AM](https://user-images.githubusercontent.com/20977376/66217440-4abe1e80-e695-11e9-9b9c-fc8340639d9e.png)

On desktop I would prefer if the custom amount expanded:
![Landing Page Monthly Copy 5@2x](https://user-images.githubusercontent.com/20977376/66217473-5e698500-e695-11e9-85e1-9132ba467daa.jpg)

Making one of the preset amounts larger looks a little odd:
![Landing Page Monthly Copy 4@2x](https://user-images.githubusercontent.com/20977376/66217510-70e3be80-e695-11e9-88e0-c307afcc9929.jpg)

But if the logic has to effect the same element I would choose the preset amount expanding for both mobile and desktop. Thoughts? Opinions? Other solutions?

Also not sure if this is in scope of torchbox to do or if we can do this ourselves @alanmoo ? Not sure what other fish there are to fry right now.

**Comment by alanmoo** [comment]
This is all useful; I'm not familiar enough with CSS grid to know what we can do here, or if this actually requires switching this section to use flexbox. Either way, I agree, it seems like something we shouldn't burn cycles on right now, as the short solution of "don't do that" works fine for now. But I'll leave this open for visibility.
