### ISSUE TITLE
Hamburger button in main nav needs to be centered

### ISSUE THREAD

**Issue by beccaklam** [mozilla/donate-wagtail#282]
# Changes needed:
- [ ] Hamburger button in the nav should be centered to mozilla logo

Current:
![Screenshot_2019-09-30 Fighting Back Against Misinformation(1)](https://user-images.githubusercontent.com/20977376/65890700-4e8a3200-e371-11e9-8f06-b76da7bda93d.png)

Change to:
![Screen Shot 2019-09-30 at 10 57 36 AM](https://user-images.githubusercontent.com/20977376/65890648-33b7bd80-e371-11e9-9638-280dcd5db858.png)

**Comment by nicklee** [comment]
Fixed https://github.com/mozilla/donate-wagtail/pull/394

**Comment by beccaklam** [comment]
@nicklee Looks good on Firefox and Safari browser. On iOS, Android and Chrome desktop the hover is doing a strange thing where the hamburger remains #666666 even after I've clicked out of the x and have moved my mouse off of the icon?

<img width="1280" alt="Screen Shot 2019-10-03 at 11 16 49 AM" src="https://user-images.githubusercontent.com/20977376/66140109-8abace00-e5cf-11e9-81a1-eed73f5214e9.png">

![Screen Shot 2019-10-03 at 11 14 58 AM](https://user-images.githubusercontent.com/20977376/66140123-8f7f8200-e5cf-11e9-822c-3837289bfe97.png)

<img width="333" alt="Screen Shot 2019-10-03 at 11 19 05 AM" src="https://user-images.githubusercontent.com/20977376/66140162-a1612500-e5cf-11e9-9cc8-e8038d497c3e.png">

**Comment by nicklee** [comment]
yep, this is the focused state that is used for people who navigate via keyboard. When you click onto it, it'll be in focus until you click something else.

**Comment by beccaklam** [comment]
Ah I see, ok we'll leave it be then!
