### ISSUE TITLE
UI fixes for iOS and Android campaign page

### ISSUE THREAD

**Issue by beccaklam** [mozilla/donate-wagtail#283]
# Changes needed:
- [ ] ~Can we ensure that we always have at least 4 donate options so we don't end up with an empty space above the 'other amount' form field?~
- [ ] 'Donate now' sticky bar should disappear once the visa and paypal button appear

![Screen Shot 2019-09-30 at 11 22 57 AM](https://user-images.githubusercontent.com/20977376/65892695-bbeb9200-e374-11e9-9db1-bc5720cabc79.png)

**Comment by philwakefield** [comment]
item 1 - this is editable on Wagtail. Recommend this is discretion of page editor. @alanmoo  We could enforce this if needed but would be restrictive.
item 2 - will investigate fix

**Comment by alanmoo** [comment]
Item 1 was a feature request from the start. Agreed, we shouldn't do anything about this. If it's a case the donation team wants to use, we might adjust the CSS to do something for the odd item, but I think that's outside the scope of this ticket.

**Comment by alanmoo** [comment]
I've edited the first comment. Let's close this ticket once the sticky bar problem is fixed.

**Comment by Pomax** [comment]
closing as out of date
