### ISSUE TITLE
Email on thank you page should autofill from credit card form

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#284]
https://donate-wagtail.mofostaging.net/en-US/stay-in-touch/

The email address from credit card payments should carry over and pre-fill the form.

**Comment by solarissmoke** [comment]
@alanmoo this should be working now.

**Comment by alanmoo** [comment]
I notice when I hit that URL in the first comment directly, it already had my email from a previous transaction. How is that being stored? (I want to make sure we're not retaining data unnecessarily.)

**Comment by solarissmoke** [comment]
@alanmoo current (default) session expiry is after 2 weeks.
