### ISSUE TITLE
Fix 'other amount' field on iOS

### ISSUE THREAD

**Issue by beccaklam** [mozilla/donate-wagtail#286]
# Changes needed:
- [ ] Currently the 'other amount' form field on iOS has rounded corners and a drop shadow. Please fix to match the design below.
- Another instance of this bug is detailed in #290 

**Current:**
![Screen Shot 2019-09-30 at 11 25 22 AM](https://user-images.githubusercontent.com/20977376/65894282-7f6d6580-e377-11e9-8ea0-16555e224b2d.png)

**Change to:**
![Screen Shot 2019-09-27 at 2 10 28 PM](https://user-images.githubusercontent.com/20977376/65894319-8d22eb00-e377-11e9-8c81-6ac1945d1af0.png)

**Comment by beccaklam** [comment]
This could also be related to #290

**Comment by nicklee** [comment]
Fixed in https://github.com/mozilla/donate-wagtail/pull/395

**Comment by beccaklam** [comment]
Looks good!
