### ISSUE TITLE
Post-Paypal indicator

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#287]
When making a Paypal transaction (desktop), there's a moment when the modal/extra window closes and you're looking at the main donation page with no significant indication that anything is happening. My instinct is that there should be _something_, perhaps a dimmed fullscreen overlay with a message in the middle, but I'll leave that to @beccaklam to make the call.

**Comment by beccaklam** [comment]
Samir had previously created a ticket for this and I dropped some designs in there: #165
