### ISSUE TITLE
Fix button and form field heights

### ISSUE THREAD

**Issue by beccaklam** [mozilla/donate-wagtail#288]
- [x] The donate button height should match the height of the form fields above. The form fields should all have consistent heights (they seem to vary). They should all be 60px.
<img width="625" alt="Screen Shot 2019-09-27 at 3 35 12 PM" src="https://user-images.githubusercontent.com/20977376/65797160-83fa0a00-e13c-11e9-968b-859c48801034.png">

**Comment by nicklee** [comment]
Updated in https://github.com/mozilla/donate-wagtail/pull/405

**Comment by beccaklam** [comment]
This looks good!
