### ISSUE TITLE
Disable certain payment options for certain currencies

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#29]
Add the ability to disable certain payment options for certain currencies - e.g., to disable Paypal for AED. 

A list of supported payment methods for each currency will be maintained as part of the data for that currency, and this will be used to determine which options are visible to the user on the landing/campaign pages.

### Information required

1. Is it possible to control which card types are accepted on a per-transaction basis in Braintree (I haven't been able to find documentation that suggests it is)?

Side note - support for Amex has to be [explicitly requested](https://articles.braintreepayments.com/get-started/payment-methods#credit-cards).

**Comment by alanmoo** [comment]
I'm confused about the information required. We currently use the currency to change the graphic showing which cards are accepted, and then hand (pre-)donors to the Stripe checkout, which (I believe) will simply accept whatever card types it accepts for that currency. Can you give an example of how the required information fits into the flow?

**Comment by solarissmoke** [comment]
I think you've already answered my question! I wasn't sure whether you somehow tell stripe which cards to accept - i.e., you pass that information to Stripe when initialising payment. It looks like it is the other way around - i.e., we are just displaying options based on what we know the processor will accept in a given currency.

**Comment by nicklee** [comment]
Functionality to hide the paypal button for certain languages has been done here:

https://github.com/mozilla/donate-wagtail/pull/118

Is there anything else we need to look at disabling? I think there was discussion around hiding the AMEX logo in the button?

**Comment by alanmoo** [comment]
Yes, we should be hiding the Amex logo on currencies where it's not accepted.

**Comment by nicklee** [comment]
Great thanks @alanmoo, this has now been added to staging https://donate-wagtail.mofostaging.net

**Comment by solarissmoke** [comment]
This is all set up now, so closing. We will need to do a thorough pass on all currencies as part of pre-launch testing.
