### ISSUE TITLE
Fix form fields on iOS

### ISSUE THREAD

**Issue by beccaklam** [mozilla/donate-wagtail#290]
# Changes needed:
- [x] Half the form fields on iOS are rounded with drop shadow, please change to match the form fields of the country selector and below:
- This could be related to #286

![Screen Shot 2019-09-30 at 11 38 49 AM](https://user-images.githubusercontent.com/20977376/65893947-e3dbf500-e376-11e9-96be-1c3ff48ea941.png)

**Comment by nicklee** [comment]
Fixed https://github.com/mozilla/donate-wagtail/pull/395

**Comment by beccaklam** [comment]
Looks good!
