### ISSUE TITLE
Use minified paypal JS

### ISSUE THREAD

**Issue by cadecairos** [mozilla/donate-wagtail#291]
we're loading these scripts:

- `https://www.paypalobjects.com/api/checkout.js`
- `https://www.sandbox.paypal.com/webapps/hermes/static/js/button.js?build=x`

but we can load the minified versions instead:

- `https://www.paypalobjects.com/api/checkout.min.js`
- `https://www.sandbox.paypal.com/webapps/hermes/static/js/button.min.js?build=x`

**Comment by solarissmoke** [comment]
We have switched to using minified `checkout.js`. We don't have control over the `button.js` script that is loaded by Paypal's own JS - presumably that will be minified when not using the Paypal sandbox.
