### ISSUE TITLE
Explore moving CSS below the fold

### ISSUE THREAD

**Issue by cadecairos** [mozilla/donate-wagtail#293]
According to PageSpeed, page loads are slowed by nearly a second waiting for CSS to load. If we move them to the body, will that cause any visual issues while the page loads?

**Comment by nicklee** [comment]
We might be best to revisit this once the production FE tooling setup has been implemented, ensuring the css is minified (https://github.com/mozilla/donate-wagtail/issues/294).

**Comment by Pomax** [comment]
closing as out of date
