### ISSUE TITLE
Minify CSS

### ISSUE THREAD

**Issue by cadecairos** [mozilla/donate-wagtail#294]
Our CSS isn't minified:

- https://donate-wagtail-staging.herokuapp.com/static/_css/main.compiled.bc8a35520fd6.css
- Some random paypal CSS, I think it's the button?

**Comment by nicklee** [comment]
I've updated tooling to minify css for dev and prod, we have source maps so didn't see a reason to only minify on production. MR opened for review.

**Comment by nicklee** [comment]
Deployed
