### ISSUE TITLE
Gracefully handle incorrect query params

### ISSUE THREAD

**Issue by cadecairos** [mozilla/donate-wagtail#297]
I was able to trigger a 5xx error by manually changing the amount value in the URL bar: https://donate-wagtail-staging.herokuapp.com/en-CA/card/single/?source_page_id=3&currency=cad&amount=99999999999999999999999999999999999999

Let's try to handle that gracefully, i.e. overriding it to a predetermined max value (on that note, I shouldn't be able to donate a billion dollars: https://donate-wagtail-staging.herokuapp.com/en-CA/card/single/?source_page_id=3&currency=cad&amount=1000000000)

**Comment by cadecairos** [comment]
This also seems to be an issue with the `source_page_id` param.

**Comment by philwakefield** [comment]
Point 1 - agree
Point 2 - we do not recommend setting a max as this would have to be set for every currency.

**Comment by cadecairos** [comment]
On our old donate platform we configured max amounts in our Form/Stripe/backend to help reduce fraud. This may no longer be necessary with Braintree, so lets not worry about that now and get those other error cases handled.

**Comment by solarissmoke** [comment]
We've added some validation both client- and server-side to guard against silly amounts, and added logic to avoid exceptions if they do somehow get through (#380). The source_page_id issue is fixed in (#353).

**Comment by cadecairos** [comment]
looking good on staging! thanks @solarissmoke!
