### ISSUE TITLE
Post-payment email sign up

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#30]
Provide the option for the user to sign up to the newsletter after they have completed payment.

### Information required

1. Where should the form data be sent (SQS)?

**Comment by alanmoo** [comment]
@patjouk Can you share the SQS we use for Basket on donate prod/staging presently? (I'm not sure if that should be shared via github or not)

**Comment by patjouk** [comment]
I'm adding more details on #27 but yes, that data goes to SQS too, to be processed by basket: https://github.com/mozmeao/basket/blob/master/basket/news/management/commands/process_donations_queue.py#L24 and https://github.com/mozilla/donate.mozilla.org/blob/master/src/components/signup.js#L38-L41

**Comment by solarissmoke** [comment]
This looks straightforward enough - thanks.

**Comment by patjouk** [comment]
good news: this is actually documented in basket docs: https://basket.readthedocs.io/newsletter_api.html#news-subscribe

Here is an example of a message we're currently sending:
```
      { format: 'html',
        lang: 'en-US',
        newsletters: 'mozilla-foundation',
        trigger_welcome: 'N',
        source_url: 'https://donate.mozilla.org/',
        email: 'bob@bob.org',
        country: undefined }
```

**Comment by solarissmoke** [comment]
@alanmoo I think it was mentioned briefly somewhere, but I can't find a record of it: I believe you need the ability to skip the newsletter step (e.g., if someone is already signed up to the newsletter). Was this to be done by setting a query argument on the landing page - and is there a particular argument you want us to use?

**Comment by alanmoo** [comment]
Correct. If they arrive on the donate site with ‘subscribed=1’ don’t ask for newsletter signups.

**Comment by solarissmoke** [comment]
Closing on the basis that newsletter signups are now in place - let's open new issues for specific data structure issues after testing.
