### ISSUE TITLE
iOS: "Next field" button doesn't jump from expiration date to CVV

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#300]
Tapping the down arrow (above the 1 button) doesn't jump to the CVV field when focused on the expiration date field.

![image](https://user-images.githubusercontent.com/1682681/65901821-fd853880-e386-11e9-87c3-54159244a677.png)

[Example page](https://donate-wagtail.mofostaging.net/en-US/card/single/?source_page_id=3&currency=usd&amount=3)

**Comment by nicklee** [comment]
Unfortunately this is part of the form that's controlled by braintree. It looks like they're making two input fields look like one (day and month), the second has a tabIndex of 0, but it needs to be -1 to prevent the user from selecting it. 

Do we have a contact at braintree that could fix this?

**Comment by alanmoo** [comment]
Ah. I'll pass this ticket along to our technical contact there.

**Comment by alanmoo** [comment]
I'm going to close this for now. If I hear back about it being possible, I'll re-open.
