### ISSUE TITLE
Attempted to log into Paypal with wrong credentials, trapped on screen

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate-wagtail#301]
In Paypal popup/new window, purposely used incorrect Paypal password. Didn't click the X on the popup box and stuck on the black overlay screen. The "Click to Continue" link doesn't work. 

Found the second widow. Clicked the X, taken back to main screen but text of "Payment Cancelled" is hard to read on light red box.

Firefox, Windows 10

![2019_09_30_PP_newwindow](https://user-images.githubusercontent.com/11812272/65903881-74680480-e37a-11e9-8414-0028afc5a3e3.JPG)
![2019_09_30_Trapped-on-black-PP-screen](https://user-images.githubusercontent.com/11812272/65903885-76ca5e80-e37a-11e9-97c0-935f7f2e5a13.JPG)
![2019_09_30_PaymentCancel](https://user-images.githubusercontent.com/11812272/65903889-78942200-e37a-11e9-94dd-98313ed46246.JPG)

**Comment by solarissmoke** [comment]
1. The "click to continue" only does anything if the popup window opened by Paypal has somehow been closed (if it is open, but doesn't have focus, then nothing happens). This is controlled by Paypal and not something we can modify unfortunately.

2. Error message styling is handled in a separate ticket.

**Comment by stephaniemcv** [comment]
Good to know. Thanks!
