### ISSUE TITLE
Fix form fields on Android

### ISSUE THREAD

**Issue by beccaklam** [mozilla/donate-wagtail#303]
# Changes needed:
- [ ] Like iOS, the Android form fields above the country selector have rounded edges when the style should have a border radius of 0. The country selector and the credit card fields appear to have the correct styling. Please fix so that the border radius is 0 for all form fields.

![Screen Shot 2019-09-30 at 2 45 00 PM](https://user-images.githubusercontent.com/20977376/65906818-30ccc500-e391-11e9-822c-340aae34f59c.png)

**Comment by nicklee** [comment]
Fixed

**Comment by beccaklam** [comment]
This looks good!
