### ISSUE TITLE
Add aria roles for nav children

### ISSUE THREAD

**Issue by youriwims** [mozilla/donate-wagtail#304]
### Issue: [Certain ARIA roles must contain particular children](https://dequeuniversity.com/rules/axe/3.3/aria-required-children?application=msftAI)

**Element path:** `.primary-nav__container`

**Snippet:** `<ul class="primary-nav__container" role="menubar">`

**How to fix:** 
Fix any of the following:
- Required ARIA children role not present: menuitem

====

More Info:

Title: WCAG 1.3.1: Certain ARIA roles must contain particular children (.primary-nav__container)
Tags: Accessibility, WCAG 1.3.1, aria-required-children
Environment: Chrome version 77.0.3865.90
Comments: n/a

**Comment by youriwims** [comment]
Please add this `role="menuitem"` to the `<a>` in the nav items.

![Screen Shot 2019-10-02 at 11 38 40 AM](https://user-images.githubusercontent.com/36484608/66059066-685e7d00-e509-11e9-8c48-fd56b1836a4a.png)

**Comment by nicklee** [comment]
Done in https://github.com/mozilla/donate-wagtail/pull/385
