### ISSUE TITLE
Lack of error state styling

### ISSUE THREAD

**Issue by beccaklam** [mozilla/donate-wagtail#305]
# Changes needed:
We are missing error state styling on:
- [ ] Chrome (desktop, iOS, Android)
- [ ] Safari (desktop, iOS) 
- [ ] Firefox on iOS
- [ ] The error state on Firefox desktop also does this weird thing where the error message is sticky and so looks out of place if I scroll. Is there a way to fix this?

![Screen Shot 2019-09-30 at 3 06 56 PM](https://user-images.githubusercontent.com/20977376/65908273-1516ee00-e394-11e9-88ab-8f94b370ced6.png)

Original error state designs:

**Mobile:**
![Screen Shot 2019-09-30 at 2 17 16 PM](https://user-images.githubusercontent.com/20977376/65908322-37107080-e394-11e9-9015-f45304b49178.png)

**Desktop:**
![Screen Shot 2019-09-30 at 2 17 31 PM](https://user-images.githubusercontent.com/20977376/65908333-3e377e80-e394-11e9-968d-eba63624cf5c.png)

**Comment by philwakefield** [comment]
@nicklee please verify that browser errors use standard styling and server errors are styled correctly.

**Comment by nicklee** [comment]
The messages you're seeing are the browser defaults for "Required" fields. I've disabled the browser validation in favour of server side validation, which is styled up as per your designs. Worth noting that it's slightly different to the design as we only have one space for error messages, and this is below the field, as per the screenshot.

<img width="1585" alt="Screenshot 2019-10-04 at 15 13 01" src="https://user-images.githubusercontent.com/298766/66214408-8cf95700-e6b9-11e9-9d21-bb176ac7cb9a.png">

MR here https://github.com/mozilla/donate-wagtail/pull/410

**Comment by beccaklam** [comment]
Ah I see, yes I had a feeling it was browser presets. I think I'm okay with that, as long as the user is directed to what they need to do. @alanmoo do you have any thoughts on this?

**Comment by alanmoo** [comment]
I'm generally in favor of letting the browsers do their thing, as the experience might differ based on platform. That being said, I don't have a strong enough opinion on this specific case to push for any changes.

**Comment by beccaklam** [comment]
Sorry @nicklee, did you say you had overridden the presets? I couldn't see it on staging.

**Comment by nicklee** [comment]
@beccaklam yep, if you visit https://donate-wagtail.mofostaging.net/en-US/card/single/?source_page_id=3&currency=usd&amount=50 and click donate without filling anything out, you should be able to see it.

**Comment by TheoChevalier** [comment]
@nicklee Where is this “This field is required” string coming from? I don’t seem to be able to find it in the templates

**Comment by nicklee** [comment]
@TheoChevalier My understanding is that this is django forms doing its thing (forms.py), but @solarissmoke will be able to confirm. It's output by:

```{% if field.errors %}
        <div class="form-item__errors">
            {{ field.errors }}
        </div>
    {% endif %}``` 

inside form_field.html

**Comment by TheoChevalier** [comment]
It would be great if we could override this, as I doubt Django will have translations in all the locales we support

**Comment by beccaklam** [comment]
@TheoChevalier Do you have an opinion on whether we should override browser presets or let them be?

**Comment by solarissmoke** [comment]
> It would be great if we could override this, as I doubt Django will have translations in all the locales we support.

I think the solution here is just to supply translations for this string in our `locale` directory (i.e., manually add this string to the `.po` files). Django will pick up these translations.

**Comment by TheoChevalier** [comment]
> > It would be great if we could override this, as I doubt Django will have translations in all the locales we support.
> 
> I think the solution here is just to supply translations for this string in our `locale` directory (i.e., manually add this string to the `.po` files). Django will pick up these translations.

We can’t do that, the `.pot` file is built from scratch at each string export, anything we add manually will be removed

**Comment by Pomax** [comment]
closing as out of date
