### ISSUE TITLE
Improve donate footer links color contrast

### ISSUE THREAD

**Issue by youriwims** [mozilla/donate-wagtail#306]
### Issue: [Text elements must have sufficient color contrast against the background](https://dequeuniversity.com/rules/axe/3.2/color-contrast?application=AxeChrome)

**Element path:** `.donate-form__footer`

**Snippet:** _multiple instances_
<img width="305" alt="Screen Shot 2019-09-30 at 3 20 19 PM" src="https://user-images.githubusercontent.com/36484608/65909109-df730480-e395-11e9-9c18-ce9d741962d7.png">

**How to fix:**
Fix any of the following:
-  Increase `font-size`
- Increase `font-weight`

====

More Info:

Comments: Given that this text can be as small as 12px on mobile, it may be worth looking into either increasing font-weight or size if we want to keep the `#595CF3` link color on the white background.
Resources: https://webaim.org/resources/contrastchecker/?fcolor=595CF3&bcolor=FFFFFF

**Comment by nicklee** [comment]
@beccaklam would be good to get your opinion here, are you happy to move to a bold weight on mobile?

**Comment by beccaklam** [comment]
My apologies, I included the wrong colour in the designs.

**Comment by benhohner** [comment]
Swap to $dark-blue (#0D10BF)
