### ISSUE TITLE
Fix alignment of consent text and consent checkbox on iOS

### ISSUE THREAD

**Issue by beccaklam** [mozilla/donate-wagtail#307]
# Changes needed:
- [ ] Email signup check box should be on the left side of the disclaimer text not above (this appears on both the upsell and email sign up page)

**Current:** 
![Screen Shot 2019-08-09 at 5 42 52 PM](https://user-images.githubusercontent.com/20977376/62810864-6bbb2680-bacd-11e9-9cbc-553a570307d6.png)

**Change to:**
![Screen Shot 2019-08-09 at 5 42 59 PM](https://user-images.githubusercontent.com/20977376/62810873-71b10780-bacd-11e9-8b72-c7a7803fb310.png)

**Comment by Pomax** [comment]
closing as out of date
