### ISSUE TITLE
Consent checkbox missing on Android

### ISSUE THREAD

**Issue by beccaklam** [mozilla/donate-wagtail#308]
# Changes needed:
- [ ] On Android, on Firefox and Chrome, the consent box is missing on the upsell and email sign up page. Is there a way to add it back in?

![Screen Shot 2019-09-30 at 3 23 42 PM](https://user-images.githubusercontent.com/20977376/65909479-c1f26a80-e396-11e9-8a48-cb210d53f25e.png)

**Comment by alanmoo** [comment]
I'm not sure we need a checkbox here, this might be a language thing. Like adding "By clicking yes, ..." covers us?

@WillatMozFdn thoughts?

**Comment by Pomax** [comment]
closing as out of date
