### ISSUE TITLE
Fix hover state of social buttons

### ISSUE THREAD

**Issue by beccaklam** [mozilla/donate-wagtail#311]
# Changes needed:
- [ ] Social button hovers should be inverted, so white text on black background
https://foundation.mozilla.org/en/style-guide/ <-- gives examples for all our button states (and much more!)
- [ ] On desktop the four social buttons should be laid out in a row instead of two stacked on top of each other (example in style guide link provided above)

**Current:**
![Screen Shot 2019-09-30 at 3 54 47 PM](https://user-images.githubusercontent.com/20977376/65911541-cc166800-e39a-11e9-8cf2-27eb703459f4.png)

**Change to:**
![Screen Shot 2019-09-30 at 3 57 16 PM](https://user-images.githubusercontent.com/20977376/65911692-fe27ca00-e39a-11e9-816d-b8ae2185acb1.png)

**Comment by nicklee** [comment]
Updated in https://github.com/mozilla/donate-wagtail/pull/404

**Comment by beccaklam** [comment]
This looks good!
