### ISSUE TITLE
Make email textbox's focus state more noticeable 

### ISSUE THREAD

**Issue by youriwims** [mozilla/donate-wagtail#312]
### Issue: Focus state not clear

**Element path:** `#email-newsletter`

**Snippet:** `<input type="text" name="email-newsletter" id="email-newsletter" placeholder="Enter email address">`

<img width="457" alt="Screen Shot 2019-09-30 at 3 55 33 PM" src="https://user-images.githubusercontent.com/36484608/65911778-20214c80-e39b-11e9-89cc-a3884331077a.png">

**How to fix:**
Fix any of the following:
- Increase border on focus to `2px`

====

More Info:

Comments: n/a

**Comment by nicklee** [comment]
Updated in https://github.com/mozilla/donate-wagtail/pull/403
