### ISSUE TITLE
Refine Campaign Header Spacing (P2)

### ISSUE THREAD

**Issue by beccaklam** [mozilla/donate-wagtail#314]
# Changes requested:
- [x] Can we add 8px margin or padding beneath the header image and 8px margin or padding between the header and paragraph text in the hero content container?
![Screen Shot 2019-08-13 at 4 50 22 PM](https://user-images.githubusercontent.com/20977376/62976383-7554cf00-bdea-11e9-9913-f889d2c83b33.png)

### Tablet
- [x] Can we make the max-width for the text inside the header image 90% instead of 60%?
![image](https://user-images.githubusercontent.com/20977376/62976135-efd11f00-bde9-11e9-855a-d5a1c4a14710.png)

**Comment by nicklee** [comment]
Styling tweaks done in MR: https://github.com/mozilla/donate-wagtail/pull/402

**Comment by beccaklam** [comment]
Looks great!
