### ISSUE TITLE
Update aria roles for radio button group

### ISSUE THREAD

**Issue by youriwims** [mozilla/donate-wagtail#315]
### Issue: [ARIA role must be appropriate for the element](https://dequeuniversity.com/rules/axe/3.2/aria-allowed-role?application=AxeChrome)

**Element path:** `.donate-form__tab-options`, `#tab-1`, `#tab-2`

**Snippet:**  _multiple instances_
1. `<form class="donate-form__tab-options tabs__container" role="tablist">`
2. `<label for="one-time" class="tabs__label tabs__item--selected js-tab-item" role="tab" aria-controls="tab-panel-1" aria-selected="true" id="tab-1">`
3. `<label for="monthly" class="tabs__label js-tab-item" role="tab" aria-controls="tab-panel-2" id="tab-2">`

**How to fix:**
  Fix any of the following:
- ARIA role `tablist` not allowed for tab group
- ARIA role `tab` not allowed for tab items

====

More Info:

Comments: Roles [`radiogroup` and `radio`](https://www.w3.org/TR/2017/WD-wai-aria-practices-1.1-20170628/examples/radio/radio-1/radio-1.html) may be more appropriate.
Resources: 
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role
- https://www.w3.org/TR/wai-aria-practices/#tabpanel

**Comment by nicklee** [comment]
done here: https://github.com/mozilla/donate-wagtail/pull/385

**Comment by youriwims** [comment]
@nicklee if it's not too much, can we remove `role="tabpanel"` from `#tab-panel-1` and `#tab-panel-2` since we've removed `tab` & `tablist` roles and we're using `aria-labelledby` to associate those elements with their selected radio button?
