### ISSUE TITLE
Revise semantic structure for header elements

### ISSUE THREAD

**Issue by youriwims** [mozilla/donate-wagtail#316]
### Issue: [Banner landmark must not be contained in another landmark](https://dequeuniversity.com/rules/axe/3.2/landmark-banner-is-top-level?application=AxeChrome)
**Element path:** `.header`,`.newsletter-signup__header`,`.footer-links__header`

**Snippet:** _multiple instances_

**How to fix:**
>By default, the HTML5 `<header>` element has an identical meaning to the banner landmark, unless it is a descendant of `<aside>`, `<article>`, `<main>`, `<nav>`, or `<section>`. [MDN]

Fix the following:
-  reorganize semantic structure to make non-banner `<header>` elements child of one of the above tags
- ensure banner `<header>` element is not inside another banner element
```
<header class="app__header">
    <header class="header">
```

====

More Info:

Comments: n/a
Resources: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Banner_role

**Comment by nicklee** [comment]
I've updated the .header to a div, retaining app__header as the header.

**Comment by youriwims** [comment]
There are also 2 headers in the footer `.newsletter-signup__header` & `.footer-links__header` can we fix those as well? An easy fix would be to update their parent `<div>` to one of the following:  `<aside>` or `<section>`.

**Comment by nicklee** [comment]
oops, missed those, shall get this updated

**Comment by youriwims** [comment]
Cool, thanks!

**Comment by nicklee** [comment]
I've updated the two header tags to divs, hope that's OK

**Comment by youriwims** [comment]
Yep, that works as well. 👍

**Comment by youriwims** [comment]
Everything looks good on staging.
