### ISSUE TITLE
Fix autocomplete attribute values

### ISSUE THREAD

**Issue by youriwims** [mozilla/donate-wagtail#320]
### Issue: [Autocomplete attribute must be used correctly](https://dequeuniversity.com/rules/axe/3.3/autocomplete-valid?application=msftAI)

**Element path:** `#braintree-hosted-field-number #credit-card-number`, `#braintree-hosted-field-expirationDate #expiration`, `#braintree-hosted-field-cvv #cvv`

**Snippet:** _multiple instances, see above_

**How to fix:**
Fix any of the following:
- Autocomplete value is inappropriate for these types of input

====

More Info:

Comments: n/a
Resources: 
- https://www.w3.org/TR/html52/sec-forms.html#autofilling-form-controls-the-autocomplete-attribute
- https://www.w3.org/WAI/WCAG21/Understanding/identify-input-purpose.html

**Comment by nicklee** [comment]
My understanding is that we don't have control over these fields, we simply have placeholders that are then replaced via braintree's scripts. @solarissmoke can you confirm?

**Comment by solarissmoke** [comment]
Yes, we don't have the ability to modify these hosted fields which are rendered inside an iframe by Braintree. Something to raise with Braintree perhaps.
