### ISSUE TITLE
Some locales are not supported

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#332]
The following locales don’t seem to be supported:

https://donate-wagtail.mofostaging.net/ach/
https://donate-wagtail.mofostaging.net/lg/
https://donate-wagtail.mofostaging.net/lo/
https://donate-wagtail.mofostaging.net/ms/
https://donate-wagtail.mofostaging.net/uk/

It may be Django expecting a different locale code

This one is also broken, but returns a 5xx error instead of a 4xx one:

https://donate-wagtail.mofostaging.net/es-XL/

**Comment by solarissmoke** [comment]
Fixed in #356 - leaving this open until we've verified it works on staging, as these translations have to be compiled for Django to find them.

**Comment by TheoChevalier** [comment]
All the links above are now working on staging (thanks to Chris, `compilemessages` is now run on staging for each deployment)

We can safely close this one, thanks!
