### ISSUE TITLE
disclaimer for monthly donations should appear only when monthly radio button is selected

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate-wagtail#337]
"Monthly donations are charged each month on the same day that you donate today, and will continue until you cancel. To cancel, email us at donate@mozilla.org. "

... that should only display when the monthly radio button is selected.  Not when one-time is selected.  This also applies to PayPal as well.

**Comment by nicklee** [comment]
Updated PR 357

**Comment by alanmoo** [comment]
@WillatMozFdn can you confirm this works as expected?

**Comment by WillatMozFdn** [comment]
It does, @alanmoo , thanks!  There's one key feature missing, though, not sure if this has been filed elsewhere.  Compare the behavior of ...

https://donate.mozilla.org/?frequency=monthly

with

https://donate-wagtail.mofostaging.net/en-US/?frequency=monthly

We're planning to send campaigns asking folks directly to sign up as monthly donors; if we lose this key feature from our current setup, that becomes significantly harder.  Is there some other query parameter I'm missing that will trigger pre-selection of the monthly option?  Or maybe it's a page-level setting in Wagtail along with default amounts ... ??

**Comment by solarissmoke** [comment]
@WillatMozFdn @alanmoo this is addressed in https://github.com/mozilla/donate-wagtail/pull/408.
