### ISSUE TITLE
Upsell box on desktop (PC) - amount should be in decimal form, up/down arrows are way too small, and some text changes

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate-wagtail#338]
Two problems noted in the upsell after a larger donation (working on a PC with Firefox) (plus some text changes):

a. amounts are displaying in the box as "5", "7" etc. ... those should be "5.00", "7.00" etc. as they are currency values

b. The triangles at right to move the amount up or down are microscopic in my view, can we enlarge them -- or drop them completely?

c. text changes:  
1. Bold the sentence "Could you add a monthly donation starting next month?" 
2. Add colon after "Yes, I will give" so it reads "Yes, I will give:"
3. Add a period at the end of "I authorize Mozilla Foundation to charge my card in the amount shown above and to continue doing so each month until I cancel"

![image](https://user-images.githubusercontent.com/23637882/65994582-adc76f80-e461-11e9-9164-a91043f1f6e0.png)

**Comment by philwakefield** [comment]
item b is standard browser behaviour. We can implement a custom JS number field but this is significant work to develop and test and will increase maintenance. We recommend accepting the browser default display for this field.

**Comment by solarissmoke** [comment]
With regard to point (a):

- Some currencies (e.g., Japanese Yen) don't have decimal places, so we cannot render them unconditionally. 
- Other currencies do, but it doesn't necessarily make sense to show them given that the value is negligible (e.g., Indonesian Rial) - here I think it would be counterproductive to render decimal places.
- The form will currently render decimals if the suggested value is not an integer. 

On this basis I think the current behaviour is a good way to handle the general case. If you do want to render decimals then I think this might have to be configured per-currency. I would argue however that the decimals don't improve usability.

Please let us know what approach you'd prefer to take here.

**Comment by alanmoo** [comment]
@WillatMozFdn It seems you're concerned that it's not clear we're talking about currency. Samir makes a lot of good points about the decimal though; If there were a way to work in the currency symbol to the design, would that would satisfy your concern?

**Comment by solarissmoke** [comment]
Also, note that there is a separate ticket to add the currency symbol to this input - I think that would help a lot as far as making it clear what the number represents goes.

**Comment by nicklee** [comment]
Text has been updated in https://github.com/mozilla/donate-wagtail/pull/400

Believe that covers everything in this ticket.

**Comment by TheoChevalier** [comment]
@WillatMozFdn Should the string “Yes, I will give:” be added to the card upsell screen as well? Currently this string is only present in the PayPay upsell screen

**Comment by WillatMozFdn** [comment]
@TheoChevalier yes, it should be present for both Paypal and credit card donations, thank you.  

Also, related to that -- the sentence of "I authorize Mozilla Foundation to charge my card monthly...."  only needs to be present for credit card donations, not Paypal (it's a card networks requirement; Paypal has their own separate disclosure once you go in there) ... and indeed, doesn't make sense for Paypal since we're not charging their card.

**Comment by nicklee** [comment]
I've just done the following to the upsell pages:

 - added "Yes, I will give" to card upsell
 - Removed authorize text from paypal
 - added "per month" text to paypal donation amount field
 - added currency symbol before value on both paypal and card

All in https://github.com/mozilla/donate-wagtail/pull/406

**Comment by Pomax** [comment]
closing as out of date
