### ISSUE TITLE
Fix Footer form heading

### ISSUE THREAD

**Issue by youriwims** [mozilla/donate-wagtail#341]
### Issue: Improper Heading

**Element path:** `newsletter-signup__heading heading heading--dark-bg heading--bottom-margin heading--secondary`

**Snippet:** `<h2 class="newsletter-signup__heading heading heading--dark-bg heading--bottom-margin heading--secondary">Protect the internet as a global public resource</h2>`

**How to fix:**
Fix the following:
- replace heading element with `<div>`, `<p>`, `<span>`, or something similar.
  - apply styles using `.h2-heading` [class](https://foundation.mozilla.org/en/style-guide/)
- add an id to `<label for="email-newsletter">`
- add `aria-labelledby=" _insert above id name here_"` to `<div class="newsletter-signup__container">`
- Verify in Accessibility dev tools that form's new 'heading' is ' Join our email list to take action and stay updated!' & all styles are still the same

====

More Info:

Comments: n/a
Resources: 
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#Labeling_section_content

**Comment by nicklee** [comment]
Updated, haven't worried too much about the styling of this as we have a seperate issue to tweak the footer. 

Originally we were going to reuse mozilla's code for the footer so this was never polished. Seems we're now just updating the original code that was doe.

**Comment by youriwims** [comment]
Ah, makes complete sense 👍 So happy to see this a11y work getting done—thanks so much @nicklee !

**Comment by youriwims** [comment]
Looks good.
![Screen Shot 2019-10-03 at 2 02 10 PM](https://user-images.githubusercontent.com/36484608/66152042-8e0d8400-e5e6-11e9-8e41-5d9d367fccc7.png)
