### ISSUE TITLE
Fix footer links heading

### ISSUE THREAD

**Issue by youriwims** [mozilla/donate-wagtail#342]
### Issue: Improper Heading

**Element path:** `footer-links__heading heading heading--bottom-margin heading--dark-bg heading--secondary`

**Snippet:** `<h2 class="footer-links__heading heading heading--bottom-margin heading--dark-bg heading--secondary">More about us</h2>`

**How to fix:**
Fix either of the following:
- put social icons and footer links list in same container as heading, 'More About Us'
- follow the same `id`/`aria-labelledby` approach in #341 

====

More Info:

Comments: n/a
Resources:
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#Labeling_section_content

**Comment by nicklee** [comment]
Updated via the id/aria-labelledby route

**Comment by youriwims** [comment]
Much better.
![Screen Shot 2019-10-03 at 2 07 07 PM](https://user-images.githubusercontent.com/36484608/66152266-1e4bc900-e5e7-11e9-8599-f92ebf4aaa74.png)
