### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by philwakefield** [mozilla/donate-wagtail#347]

**Comment by nicklee** [comment]
Do we just need the code snippet for this one?

**Comment by solarissmoke** [comment]
No, there is a fair bit of integration required - I'm working on it.

**Comment by alanmoo** [comment]
Where are we on this? I don't want to launch a test run of the site without any analytics next week.

**Comment by solarissmoke** [comment]
I think we're waiting for Chris to test, but @philwakefield will advise.

**Comment by cadecairos** [comment]
This is done
