### ISSUE TITLE
Translation functionality

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#35]
This is a broad description of the translation functionality/workflow that we need to implement - which we can then break into specific tasks for implementation. My understanding of the key requirements and flows as follows - subject to review from the Mozilla team.

Translations will be provided by [Pontoon](https://pontoon.mozilla.org/), which operates on git repositories - i.e., it pulls translatable strings from a repository and will push translated strings back to it.

### Code/template string translations

These will be handled in the normal way. Django will generate `.po` files which Pontoon will read and update with translations when they become available.

### CMS content

CMS content in Wagtail will be made translatable using the `wagtail-translation` package (work in progress). This package provides a framework for generating translatable pages and a UI for managing those pages within Wagtail. It provides a mechanism for extracting text from page content into a series of translatable strings.

We will need to develop a way for these translatable strings to be relayed to/from Pontoon via a repository that Pontoon can push/pull from.

**Comment by TheoChevalier** [comment]
The description above looks good to me, I’ll add additional information in case it helps figuring this out.

Supported file formats: https://mozilla-pontoon.readthedocs.io/en/latest/index.html Note that having different file formats in the same repository is supported, so we could have .po files for template strings, and files in a different format for CMS content.

Folder structure: https://mozilla-pontoon.readthedocs.io/en/latest/user/localizing-your-projects.html#folder-structure

One of our projects using .po files (accounts.firefox.com): https://github.com/mozilla/fxa-content-server-l10n
- As you can see, we can store the l10n content in a separate repository from the code repository, if necessary.

Current production setup in Pontoon for donate.mozilla.org: https://pontoon.mozilla.org/projects/fundraising/

When we want to test things up, I can easily set up a dummy project on the staging instance https://mozilla-pontoon-staging.herokuapp.com/

**Comment by solarissmoke** [comment]
Closing on the basis that translation functionality is now in place - let's open new tickets for specific issues.
