### ISSUE TITLE
Country list is not localized

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#358]
I’m pretty sure there is a library somewhere that could localize the country names dropdown for us. Those strings may even already be in Django default translations?

<img width="886" alt="Capture d’écran 2019-10-02 à 15 20 20" src="https://user-images.githubusercontent.com/1294206/66047530-37417500-e528-11e9-92ad-6cc7937e9293.png">

**Comment by solarissmoke** [comment]
There is an easy fix for this - I'll sort it tomorrow.
