### ISSUE TITLE
“Country” field is not localizable

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#362]
This field is not wrapped for localization, and I can’t find it anywhere. It seems it’s imported?

`from django_countries.fields import CountryField`

![Screenshot_2019-10-02 Your information](https://user-images.githubusercontent.com/1294206/66053341-707ee280-e532-11e9-9759-e4c31fb30678.png)

**Comment by solarissmoke** [comment]
This will be fixed by the change required for #358.
