### ISSUE TITLE
Create clear error state of 'Other Amount' <input>

### ISSUE THREAD

**Issue by youriwims** [mozilla/donate-wagtail#363]
### Issue: Donate home 'Other Amount' <input> has no error state for empty, invalid inputs.

![error-id](https://user-images.githubusercontent.com/36484608/66054222-ab1c5700-e501-11e9-8649-c1a6a58bea49.gif)
**How to fix:**

- Please add clear error ui changes that align with payment form error states instead of page refreshing

====

More Info:

Comments: Sorry that gif is so slow, I have no clue why.
Resources: Related to #343
cc @philwakefield

**Comment by benhohner** [comment]
Validate if still exists
