### ISSUE TITLE
Stronger thank you message

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate-wagtail#371]
This is a nice to have request.
Would like to see the thank you message here be a better thank you that ties the donor's gift to the impact and work Mozilla is striving for. 
Also would like to see wording to differentiate between between a single transaction id and recurring subscription id.

![2019_10_03_Thankyou](https://user-images.githubusercontent.com/11812272/66089088-00c12580-e53b-11e9-97be-fa76bfdbbc80.JPG)

**Comment by Shivansh2407** [comment]
Can I help fix this?Please explain me what to do.

**Comment by solarissmoke** [comment]
The transaction reference was not in the original designs IIRC - it was just something we had added to aid with testing - think it's worth checking with @beccaklam whether there was a decision on whether or not to keep it?

In either case I think your point about a stronger message is valid and might be worth addressing before launch.

**Comment by beccaklam** [comment]
@solarissmoke @stephaniemcv I don't think Steph is saying to remove the transaction id, just that it would be nice to have wording that differentiates a one time donation from a monthly. @stephaniemcv I think we would need to get someone to write that copy. @WillatMozFdn do you have anything in mind?

**Comment by WillatMozFdn** [comment]
Thanks for bringing this one up, Steph!  We do not need a differentiation here between one-time and recurring; Legal has never asked for that in the current setup and seems like it would take some additional programming, so ... let's not do that.

Also, transaction ID not needed -- it will be in their emailed donation receipt.  I don't want to present it to them here and make them feel like they need to write it down ... when it's already on the way to them via email.

I do want to improve what's there, though ... let's go with ...

> From all of us at Mozilla, **thank you**! We'll put your donation right to work protecting the web as a global public resource, open and available to all.  We're sending you a thank-you note; if you don't receive that in a few minutes please check your junk or spam folders, or drop us a note at donate@mozilla.org for a replacement.

(Can that fit?  If not, let me know and I'll edit.)

**Comment by TheoChevalier** [comment]
Fixed in #440
