### ISSUE TITLE
Paypal button slow to render

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate-wagtail#373]
On Chrome (windows) the Paypal button takes a while to appear on first load and refresh. Looks very odd popping in suddenly.

**Comment by solarissmoke** [comment]
Not sure we have any control over the delay - Paypal button is rendered by Paypal's JS, which is slow. It's possible it will improve in production when we're not using their sandbox. We _could_ wait for paypal to load before rendering any buttons, but I am not sure that is much of an improvement.

**Comment by nicklee** [comment]
I'd noted this previously as it was annoying me too. I'd done some initial investigation on how we could potentially speed it up, but unfortunately couldn't find anything, as like Samir has mentioned, it's all down to the third parties js rendering it.

**Comment by stephaniemcv** [comment]
Gotcha. Thank you for investigating!

**Comment by alanmoo** [comment]
It seems _better_ on production. Not perfect, but certainly better.

**Comment by alanmoo** [comment]
Actually, it looks like there are some [optimizations we can take](https://developer.paypal.com/docs/checkout/troubleshoot/performance/#instant-render). I'm re-opening this for addressing at some point.

**Comment by jamilasnell** [comment]
Not an issue anymore!
