### ISSUE TITLE
Non numbers in Other Amount box error notification

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate-wagtail#374]
If you include a symbol or letter in the Other Amount box and click the Paypal button, the bad value is erased and an error box appears below the footer. If you do the same steps but click the CC button, the value is erased and no error notification appears anywhere.

We need the error notification to be consistent and preferably higher up on the page, easy to see. *(Window/Chrome)

![2019_10_03_ISE_500_symbol_in_other_amount](https://user-images.githubusercontent.com/11812272/66089618-526aaf80-e53d-11e9-8d87-b01273cc573c.JPG)

![2019_10_03_ISE_500_symbol_in_other_amount_pp_error_low](https://user-images.githubusercontent.com/11812272/66089635-62828f00-e53d-11e9-9879-e8c8603e3b39.JPG)

**Comment by nicklee** [comment]
We've done the following:
 - Updated the field to a number field
 - Moved paypal error message above the form 
 - Clicking card payment button will now trigger a browser validation saying "Please enter a number"

Whilst they are still not consistent, this feels like an improvement. We're limited by the message that appears from Paypal.

**Comment by cadecairos** [comment]
This looks resolved.
