### ISSUE TITLE
rtl layouts

### ISSUE THREAD

**Issue by nicklee** [mozilla/donate-wagtail#38]
Ensure that all page designs work with right to left languages.

Recommend we do this by adding a class to the app div that then updates the layout accordingly, `app--rtl` sounds sensible to me.

This would ensure all text is set to align right, and that the layout is flipped.

Ideally we'd have a design illustrating how this works on one template, then we can interpret the rest, but it's not essential.

**Comment by nicklee** [comment]
Example of how this currently works here: https://donate.mozilla.org/he

**Comment by alanmoo** [comment]
cc @beccaklam

**Comment by nicklee** [comment]
Design now done for campaign page, Torchbox have sketch file

**Comment by nicklee** [comment]
Backend now done for this https://github.com/mozilla/donate-wagtail/pull/92

**Comment by nicklee** [comment]
Could do with testing this on all templates, earmarked for tomorrow along side browser testing
