### ISSUE TITLE
“Other amount” placeholder not localized after switching currency

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#387]
STR:
- Go to https://donate-wagtail.mofostaging.net/fr/
- Switch from EUR to USD (or any other)

→ The Other amount placeholder is not localized anymore.
I don’t understand why I can’t reproduce this issue locally, but it’s broken on staging
![Screenshot_2019-10-03 Donate now](https://user-images.githubusercontent.com/1294206/66122045-03755680-e5df-11e9-8029-544a6275d7b8.png)

**Comment by solarissmoke** [comment]
@TheoChevalier I _think_ your browser is using old cached assets. Please force a refresh with Ctrl + Shift + R (or equivalent on your OS), and see if that resolves the issue? If it does, then it's probably also worth making sure you can't find a way to trigger it again later.

**Comment by TheoChevalier** [comment]
I had tried with another browser to make sure it was not a caching issue (where I never opened the site), and was also able to reproduce on other devices as well. However, I wonder if there has been changes related to this this morning, because now I can’t reproduce anywhere 🤷‍♂️

**Comment by TheoChevalier** [comment]
Or it may have been a caching issue on the server side. Anyway, this looks safe to close!
