### ISSUE TITLE
Research: making postcode optional

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#415]
Many regions don’t use ZIP/Postal codes at all: https://en.wikipedia.org/wiki/List_of_postal_codes

If Braintree doesn’t require it, we should make it optional in the form.

In Stripe, when you select a region that do not use this, for instance Ivory Coast, the postcode field disappears. 

- [x] Check if Braintree or risk assessment plugin requires Zip code
- [x] Check if salesforce requires Zip code field
- [x] Is there a library that makes this easy?
- [ ] Can we make the field disappear if there is no post code?
- [ ] If not, make field optional

**Comment by danielfmiranda** [comment]
Hi everyone, after some research here is what I found:

**Check if Braintree or risk assessment plugin requires Zip code:**
After taking a look at the docs for braintree, it appears that they give the users the option to make the zip/postal code optional. For example, this [article](https://developers.braintreepayments.com/reference/general/validation-errors/all/python#code-81808) explaining the different AVS response codes show that there is one that will return "Postal code enabled" which will return only if you have the zip/postal code set as required.

**Check if salesforce requires Zip code field**
I was unable to find a concrete answer, however after reading a couple of support articles it appears that the answer is leaning towards not required. 

For example, there is this [document](https://help.salesforce.com/articleView?id=sf.fields_useful_validation_formulas_account_address.htm&type=5) which shows the developer how to require validation of zip code if the user is from canada or the US. This leads me to believe that postal code and zip are optional fields as well.

**Is there a library that makes this easy?**
There are python libraries for zip code, however, it does appear that a majority of the libraries are for only US zip codes or a specific region. 

The most promising one that I can find, that would work with international post codes would be [pgeocode](https://pgeocode.readthedocs.io/en/latest/generated/pgeocode.Nominatim.html)
 

**Can we make the field disappear if there is no post code?**
**If not, make field optional**
I believe we could, but I would like to ask the other developers  @Pomax @KalobTaulien @mmmavis  to chime in on this topic, as I am not sure if doing so would affect user experience/ accesibility.

**Comment by benhohner** [comment]
@danielfmiranda Thanks for the research! I've found this https://gist.github.com/jamesbar2/1c677c22df8f21e869cca7e439fc3f5b/ which is a JSON list of countries, whether they have a post code, and their formats. As with any squishy human geopolitical thing, these change fairly frequently trending towards more countries supporting Post Codes. We could use the list to build a feature that makes the post code field disappear when the user selects a country without a post code.

@kristinashu thoughts on behaviour for if a user selects a country without a post code?
My thoughts:
- Country has post code: post code mandatory
- Country has no post codes: hide post code field

Both: Overall, I think the current priority of this feature is low as it's probably better to wait until the CRM/Cinchy migration is complete before we change what type of data is flowing through the donate stack. Let's discuss UX then pick this up after the migration is complete in May or June.

**Comment by kristinashu** [comment]
I like your proposal!

> Country has post code: post code mandatory
> Country has no post codes: hide post code field

**Comment by danielfmiranda** [comment]
Closing this research issue and opened new issue [#1397](https://github.com/mozilla/donate-wagtail/issues/1397)
