### ISSUE TITLE
Enable and test recaptcha on staging

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#432]
Recaptcha is not currently configured on staging and hasn't been through QA - think it's worth enabling and verifying that all payment flows still work.

**Comment by alanmoo** [comment]
Agreed, I thought we had this already... or is it just not enabled?

**Comment by solarissmoke** [comment]
It's not enabled (we need to set API keys).

**Comment by cadecairos** [comment]
I've set up recaptcha for staging and production, and confirmed that things are working on staging by setting my user agent string to `Googlebot/2.1`, which triggers the captcha challenge.
