### ISSUE TITLE
Application monitoring / error logging

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#436]
I'm not sure what Mozilla's approach to logging and reporting on other projects is, but I think it is worth considering setting up some form of application monitoring and error logging on the site before launch (things like Sentry, Scout).

In particular it will be important to log and monitor Braintree payment errors, so that you have visibility on what the causes of payment failures are and can assess whether there are ways to prevent any of them.

**Comment by alanmoo** [comment]
Yes! We’ve been working on getting entry running.
