### ISSUE TITLE
Recurring subscription id recording as transaction id

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate-wagtail#456]
For both Paypal and CC recurring charges, Salesforce is recording no value in the PMT Subscription ID field and is instead recording the BT Subscription ID value in the PMT Transaction ID field

BrainTree view
![2019_10_14_BT_SubID_recording_as_TranID](https://user-images.githubusercontent.com/11812272/66774534-06920180-ee7f-11e9-9907-c5ad828c8b3f.JPG)

SFDC view
![2019_10_14_SFDC_SubID_recording_as_TranID](https://user-images.githubusercontent.com/11812272/66774545-0c87e280-ee7f-11e9-856c-8bbc2286825a.JPG)

(Windows 10/Chrome)

**Comment by alanmoo** [comment]
@stephaniemcv I think this has been fixed. Can you confirm?

**Comment by alanmoo** [comment]
This was fixed, but subscription IDs are no longer being captured at all. I've opened a PR to address this.
