### ISSUE TITLE
Missing data values when a customer subscribes to email after donating 

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate-wagtail#458]
Occurs on Paypal, CC, one-time, recurring, upsell transactions.
Not sure if this isn't getting passed to Basket dev or if Basket dev is failing.

Subscriber = TRUE
Mozilla Subscriber = TRUE (Basket slug mozilla-foundation)
Signup Source URL = url of form

(Windows 10 Firefox and Chrome)

**Comment by alanmoo** [comment]
Apparently #488 is the same issue, but I'll close this as the duplicate since it's a bit unclear.
