### ISSUE TITLE
Recaptcha error - Unable to submit donation

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate-wagtail#468]
Created a Thunderbird campaign page. Went to submit information for donation and received
 "ERROR for site owner: invalid domain for site key" on a Recaptcha flyout

![2019_10_16_Recaptcha_error](https://user-images.githubusercontent.com/11812272/66965084-bf01a600-f035-11e9-94d6-78f954be1101.JPG)

**Comment by TheoChevalier** [comment]
@MikkCZ Thanks for the heads up, I’m hitting that issue too now while it was working on Wednesday.
Editing the title as it’s affecting the main payment flow as well
cc @alanmoo @philwakefield

**Comment by alanmoo** [comment]
@cadecairos was working on recap the this week too

**Comment by cadecairos** [comment]
I wasn't aware we had this Heroku app wired up to the mofostaging domain. If we add this domain to the recaptcha app config in the recaptcha dashboard, it should work. @alanmoo  or @patjouk should be able to do this, otherwise I can take care of it on Tuesday.

**Comment by alanmoo** [comment]
This is fixed. Though @cadecairos why didn't Sentry catch this? Because it didn't trigger a JS error?

**Comment by cadecairos** [comment]
yeah, Sentry will only alert us on unhandled JavaScript exceptionsll
