### ISSUE TITLE
FieldDoesNotExist: ContentPage has no field named 'project'

### ISSUE THREAD

**Issue by cadecairos** [mozilla/donate-wagtail#469]
https://sentry.prod.mozaws.net/operations/donate-stage/issues/6485978/

public link: https://sentry.prod.mozaws.net/share/issue/69d3da0b8dda4651970d185a6360c3e3/

```
KeyError: 'project'
  File "django/db/models/options.py", line 565, in get_field
    return self.fields_map[field_name]

FieldDoesNotExist: ContentPage has no field named 'project'
(10 additional frame(s) were not displayed)
...
  File "django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "wagtail_localize/models.py", line 631, in update_synchronised_pages_on_publish
    update_fields[field.field_name] = field.get_value(instance)
  File "wagtail_localize/fields.py", line 9, in get_value
    return self.get_field(obj.__class__).value_from_object(obj)
  File "wagtail_localize/fields.py", line 6, in get_field
    return model._meta.get_field(self.field_name)
  File "django/db/models/options.py", line 567, in get_field
    raise FieldDoesNotExist("%s has no field named '%s'" % (self.object_name, field_name))
```

**Comment by cadecairos** [comment]
@TheoChevalier hit this unhandled exception attempting to publish an FAQ page as a `ContentPage`

**Comment by TheoChevalier** [comment]
Looks like content pages are missing a Mozilla/Thunderbird project dropdown?

**Comment by alanmoo** [comment]
They shouldn't actually need that dropdown though, as they aren't submitting anything.

**Comment by philwakefield** [comment]
Excuse my technical ignorance here but to clarify - is the issue the exception is unhandled and correct handling should be added? 
Would it be possible to add expected behaviour to ensure I am clear?

**Comment by TheoChevalier** [comment]
@philwakefield that’s pretty straightforward, let me clarify:

Actual behavior:
- Create a new Content page with random title + body text
- Hit “Publish”

→ It fails, with the error above

Expected: it doesn’t fail and the page gets properly created
