### ISSUE TITLE
Port footer signup behavior from Foundation site

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#482]
We should add the country/language picker from the newsletter signup in the footer of the Foundation site.

(It looks like this when you click on the email field)
<img width="611" alt="image" src="https://user-images.githubusercontent.com/1682681/67560823-8fc4f600-f713-11e9-8ad5-8738457e1137.png">

**Comment by TheoChevalier** [comment]
Implementation notes:
- Country field is fully optional (and doesn’t fall back to `US`)
- Language list should remain the same, `en, de, es, fr, pl, pt` even if we’re supporting many more locales here
- If the current page locale is one of the following, the corresponding language in the dropdown should be preselected: `de, es-*, fr, pl, pt-*`. And then fall back to `en` for all the other locales.
