### ISSUE TITLE
Possibility of accidentally donating one-time instead of monthly

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#484]
STR: 

1. Choose a monthly donation amount
2. Click credit card button
3. Hit the browser back button (verified in Firefox 71.0b3)
4. Observe the monthly radio is selected, but one-time payment boxes are active. Choosing one of these and moving forward again starts a one-time gift flow.

Expected behavior:
Hitting the browser back button should (ideally) keep monthly selected, with monthly options. Alternatively: the correct radio should be selected for one-time gift.

@philwakefield This feels like something your team would have the context to address, as I know there were other issues around this.

**Comment by benhohner** [comment]
Verify if still exists

**Comment by alanmoo** [comment]
I can confirm this still exists in Firefox and Chrome on Mac, but behaves as expected in Safari. (iPadOS Safari seems fine too.)
