### ISSUE TITLE
Production donations are not showing up in Salesforce

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#487]
When making a recurring donation, it seems the transaction is not being received properly by Basket. This does work on staging.

Observations:
* Post-donation newsletter signup has consistent behavior. (It doesn't fully work and sign up for a newsletter, but that's an unrelated issue)
* It appears from the logs that the message gets sent to the SQS the same way, and nothing is getting stuck in the queue production.

So I'm wondering if this is a Basket->Salesforce Prod issue. @pmac can you see if there's anything in basket with errors around the email `amooiman+recurring2@gmail.com`?

**Comment by pmac** [comment]
Is this instance hooked up to basket-prod?

**Comment by alanmoo** [comment]
The PR is hooked up to Advo.

**Comment by alanmoo** [comment]
Ack. Nope, wrong info. This is what I get for answering while in an airport and walking. Yes, production.

**Comment by pmac** [comment]
I do see some errors due to the `Payment_Source__c` getting an invalid value for the picklist `Braintree_Card`. Maybe that wasn't moved to prod SFDC or is the wrong value? Sound right @desiree-mofo ?

**Comment by desiree-mofo** [comment]
AFAIK, that's not a valid picklist value in Prod. Did braintree switch over to production this weekend?

**Comment by alanmoo** [comment]
Seems the picklist solved this.
