### ISSUE TITLE
Host og images on assets.mofoprod.net

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#504]
Hey @cadecairos , would you mind uploading those two images on assets.mofoprod.net for me please? Django is versioning the files, so I think we should hardcode the links in the og tags for FB/Twitter

https://github.com/mozilla/donate.mozilla.org/blob/master/assets/images/og.png
https://github.com/mozilla/donate.mozilla.org/blob/master/assets/images/thunderbird/TorontoSummit2014m.12923cab901787ca8681718646196167.jpg

**Comment by cadecairos** [comment]
Here you go @TheoChevalier:

https://assets.mofoprod.net/images/og.png
https://assets.mofoprod.net/images/thunderbird_team.jpg

**Comment by TheoChevalier** [comment]
Thanks Chris!
