### ISSUE TITLE
Monthly Paypal transactions are failing

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#514]
This may be fixed by #398 but Heroku's having issues today.

Attempting to make a monthly Paypal donation on staging (no matter the size) fails.

**Comment by alanmoo** [comment]
This still seems to be hanging. I'm awaiting landing of #500 so we can have better logging on staging.

**Comment by alanmoo** [comment]
It looks like this is due to recaptcha. @solarissmoke @cadecairos Any idea what to do here? I imagine Paypal doesn't need recaptcha?

**Comment by solarissmoke** [comment]
[PR to fix this](https://github.com/mozilla/donate-wagtail/pull/538). 

> I imagine Paypal doesn't need recaptcha?

You have implemented recaptcha for Paypal on the old site - I assumed there was a reason for this and so did the same here. Removing it will simplify things quite a bit, if you are confident that Paypal does its own checks that make recaptcha redundant.
