### ISSUE TITLE
CMS translations are not treated as richtext

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#553]
See the French translation of the intro on https://give.mozilla.org/fr/

`<b>` tags are visible 

![image](https://user-images.githubusercontent.com/1294206/68417144-2246aa00-0196-11ea-8154-e69f672943e7.png)

**Comment by TheoChevalier** [comment]
Same issue for links on https://give.mozilla.org/fr/ways-to-give

**Comment by TheoChevalier** [comment]
There’s probably just an extra conversion along the way, as `<` become `&amp;lt;`

**Comment by TheoChevalier** [comment]
@kaedroho Any idea where this might happen in `wagtail-localize-pontoon`?

**Comment by kaedroho** [comment]
By looking at the code, I think the issue most likely lies in `restore_html_segments` in wagtail-localize: https://github.com/kaedroho/wagtail-localize/blob/master/wagtail_localize/segments/html.py#L170-L177.

Just having a closer look now.

**Comment by kaedroho** [comment]
This should be fixed by: https://github.com/kaedroho/wagtail-localize/commit/c31cbd7f5bea4bb537b1b7b51795fad75f5cbfdf

I'll make a new release once CI passes

**Comment by kaedroho** [comment]
new version of `wagtail-localize` released. `0.3.1`. After installing this, you'll need to make an edit on that content in Pontoon to get it to re-sync and fix this issue.

**Comment by TheoChevalier** [comment]
Confirmed fixed on staging, thanks!

![image](https://user-images.githubusercontent.com/1294206/68491496-431d0700-024b-11ea-8858-16463704657a.png)
