### ISSUE TITLE
Prevent string duplicates in .po files

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#559]
When sync has been enabled again on staging with https://github.com/kaedroho/mozilla-donate-staging-content, strings got duplicated in .po files: https://github.com/kaedroho/mozilla-donate-staging-content/commit/dad4faf3f50e314932b61f722347f026ac0d5867#diff-65f41435e0a57396bd7836f2b57c5c60  

When committing, `wagtail-localize-pontoon` should make sure strings are unique in each .po file

**Comment by kaedroho** [comment]
This bug is a little obscure, it's called by this line: https://github.com/kaedroho/wagtail-localize-pontoon/blob/a849a2636983026723d1dbf3dd99a91eeb40b793/wagtail_localize_pontoon/models.py#L147

As these segments appear in multiple revisions, I added a `distinct()` so that segments only appear once in the results. But ordering by `page_locations__order` prevents it from seeing the segment as a duplicate if it changed position on the page between the revisions.

**Comment by kaedroho** [comment]
Just released `wagtail-localize-pontoon` 0.1.2 with a fix for this

**Comment by TheoChevalier** [comment]
It fixed part of the issue, as strings are no more randomly duplicated at each sync. But I think there’s stills something fishy going on for strings that genuinely appear in multiple places in the same page: https://github.com/kaedroho/mozilla-donate-staging-content/commit/45d132b882b97d7c0e2e461c50823b2b41a28ba1#diff-d64e2efb1505f3bccd0533e4e121553bL218-L226

In this commit, I only remove a period in faq.po, but Wagtail translated the duplicated strings.

These strings should still appear only once in the .po file, as only one occurrence will be displayed in Pontoon anyway: https://torchbox-pontoon.herokuapp.com/es/mozilla-donate-staging-content/templates/mozilla-donate/ways-to-give.po/?search=%3Cb%3EAccount+Number%3A%3C%2Fb%3E+3302412870&string=261

**Comment by kaedroho** [comment]
> In this commit, I only remove a period in `faq.po`, but Wagtail translated the duplicated strings.

Looks like this is the same underlying issue as in https://github.com/mozilla/donate-wagtail/issues/563
Wagtail localize stores one translation per source string per language, so it's taken the translation from another page assuming it's good for this one. I think this behaviour is useful but it probably should mark the translation as "fuzzy" and allow it to have a different translation in another context.

**Comment by TheoChevalier** [comment]
> > In this commit, I only remove a period in `faq.po`, but Wagtail translated the duplicated strings.
> 
> Looks like this is the same underlying issue as in #563
> Wagtail localize stores one translation per source string per language, so it's taken the translation from another page assuming it's good for this one. I think this behaviour is useful but it probably should mark the translation as "fuzzy" and allow it to have a different translation in another context.

Right, if it marks it as fuzzy, that would be the same bahaviour as `manage.py makemessages` for Django templates, by default

**Comment by TheoChevalier** [comment]
Since this is covered by #563, closing this one :)
