### ISSUE TITLE
Localized links are non functional

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#561]
Follow-up from #553 

Link placeholders in https://donate-wagtail.mofostaging.net/fr/ways-to-give/ are not replaced with actual data.

<img width="460" alt="Capture d’écran 2019-11-11 à 10 06 01" src="https://user-images.githubusercontent.com/1294206/68578916-e6983280-046a-11ea-93b1-b53a8803625f.png">

**Comment by kaedroho** [comment]
Fixed on master. I've made it store those attributes in local translation memory (for performance) so this would require resubmitting any affected pages

**Comment by kaedroho** [comment]
Released `wagtail-localize` 0.3.2 and `wagtail-localize-pontoon` 0.1.4 with the fix mentioned above

**Comment by TheoChevalier** [comment]
Links are working! 🎉 https://donate-wagtail.mofostaging.net/fr/ways-to-give/
