### ISSUE TITLE
es-AR, es-CL, es-MX, es-XL are not using es CMS translations

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#570]
Like for Django strings, `es-AR`, `es-CL`, `es-MX` and `es-XL` should consume translations from `es`

For testing purposes, those two pages should use the same translations:

https://donate-wagtail.mofostaging.net/es/faq/
https://donate-wagtail.mofostaging.net/es-MX/faq/

**Comment by kaedroho** [comment]
Working on this here https://github.com/kaedroho/wagtail-localize/pull/24

**Comment by kaedroho** [comment]
New branch: https://github.com/wagtail/wagtail-localize/pull/47

**Comment by TheoChevalier** [comment]
Fixed by https://github.com/mozilla/donate-wagtail/pull/1218
