### ISSUE TITLE
Protected master branch prevents Pontoon from committing

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#573]
https://donate-wagtail.mofostaging.net/ast/ is not showing up translations, I need to investigate what’s going on.

**Comment by TheoChevalier** [comment]
Pretty simple explanation, Pontoon never committed those translations

https://pontoon.mozilla.org/ast/mozilla-donate-website/
https://github.com/mozilla/donate-wagtail/tree/master/donate/locale/ast/LC_MESSAGES

@mathjazz, do you see anything in the logs on production? This locale is not syncing and I have no clue why…

**Comment by mathjazz** [comment]
None of the locales are syncing:

```
Failed to sync locale sk for project mozilla-donate-website due to commit error: remote: error: GH006: Protected branch update failed for refs/heads/master.
```

**Comment by TheoChevalier** [comment]
Argh, thanks @mathjazz! Looks like someone has changed the repo settings over the past week

**Comment by patjouk** [comment]
That's my fault. I was surprised that master was not protected and changes the settings. I'll revert my changes

**Comment by TheoChevalier** [comment]
Thanks! Sync is happening again :)  https://github.com/mozilla/donate-wagtail/commits/master
