### ISSUE TITLE
Migration: Cancel deprecated donor subscriptions for MZLA Stripe/Paypal

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/donate-wagtail#575]
__* This is for both PP and Stripe__
1. @stephaniemcv to export subscription IDs for MZLA recurring donors
2. We will write a script to delete subscriptions by ID from both payment providers. We will need to keep customer + transaction info in order to issue refunds.

__IMPORTANT__: This script will need to be run in coordination with sending email comms about the cancellation + launching the MZLA platform in this order:
1. Step # 1 (see above)
2. Step # 2 (see above)
3. Launch MZLA platform
4. Send email

Assigning to @cadecairos for now to investigate step 2 and provide details on how we would do that.

I will check in with Stripe + PayPal to see if they can do step 2 for us.

**Comment by cadecairos** [comment]
Paypal
======

We'll need to call the cancel subscription method at **POST** `/v1/billing/subscriptions/{subscription_id}/cancel` (https://developer.paypal.com/docs/api/subscriptions/v1/#subscriptions_cancel)

Stripe
======

We'll need to call the cancel subscription method at **DELETE** `/v1/subscriptions/{subscription_id}` (https://stripe.com/docs/api/subscriptions/cancel)

**Comment by gideonthomas** [comment]
Thanks @cadecairos, assigning to @stephaniemcv to identify if we're able to export subscription ids for PayPal recurring donors as we've identified that there *may* be an issue with that. For context:

> Will: afaik, due to those deprecated PayPal APIs, we do not record into Salesforce any paypal recurring donations except the initial one (for both MoFo and MZLA, both micro and main accounts.)

**Comment by gideonthomas** [comment]
cc @alanmoo

**Comment by gideonthomas** [comment]
I'll draft a timeline for this, but the code shouldn't be blocked.
@stephaniemcv will export subscription ids as CSV from PayPal (once timeline is finalized)
@stephaniemcv will export subscription ids as CSV from Salesforce for Stripe (once timeline is finalized).

**Comment by cadecairos** [comment]
I've begun writing the cancellation script. Any hint at the data format would help me write the CSV reader portion of the script.

**Comment by gideonthomas** [comment]
@WillatMozFdn or @stephaniemcv any chance you're able to provide a sample of the data from PayPal and Stripe for MZLA donors?

**Comment by cadecairos** [comment]
WIP code here: https://github.com/MozillaFoundation/mofo-devops/pull/720/files

**Comment by stephaniemcv** [comment]
Working on a sample

**Comment by gideonthomas** [comment]
@cadecairos can you check off here what's done in your PR as you implement it?
- [ ] Cancel stripe recurring donors
- [ ] Cancel PayPal recurring donors
- [ ] Cancel PayPal micropayment recurring donors
