### ISSUE TITLE
Italic text is not properly extracted in .po files

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#586]
`“What else should you know?”` (italic, with smart quotes) got extracted as `<text id="text1"></text><br/><i></i>` in the .po

https://github.com/kaedroho/mozilla-donate-staging-content/blob/master/templates/mozilla-donate/faq.pot#L207

**Comment by kaedroho** [comment]
Just tried this locally and it was extracted as `<i>“What else should you know?”</i>`

I think it might be getting confused with some of the surrounding HTML. Please could you send the entire HTML contents of that field?

**Comment by TheoChevalier** [comment]
Sure, with question 2 on https://donate-wagtail.mofostaging.net/en-US/faq/ "How does Mozilla ensure my personal information is protected?" it’s happening with paragraphs 2 & 3

**Comment by kaedroho** [comment]
Managed to reproduce this now. It happens when there is a block tag within an inline tag.

For example: ``<i>Foo <p>Bar</p></i>``

Becomes: ``<text value="Foo "></text><text value="Bar"></text><p></p><i></i>``

**Comment by kaedroho** [comment]
I've just released version 0.3.3 that includes a bunch of improvements including handling `<br>` tags properly, removing inline tags that wrap whole segments and some extra resilience to invalid HTML.

This might cause some segments to change which will require them to be retranslated.

**Comment by TheoChevalier** [comment]
Confirming this one is fixed as well :) Example here: https://github.com/kaedroho/mozilla-donate-staging-content/blob/master/locales/fr/pages/mozilla-donate/faq.po#L57
