### ISSUE TITLE
wagtail-localize-pontoon stopped syncing

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#588]
I think it happened after pulling translations here https://github.com/kaedroho/mozilla-donate-staging-content/commit/4a71e3fea3cb12f2cd162aaa815cb99ebfba12ad

Potentially related to the fix for https://github.com/mozilla/donate-wagtail/issues/518

Actual error on sentry:
https://sentry.prod.mozaws.net/share/issue/4b73d27d23e848c8bd64697d32569029/

**Comment by kaedroho** [comment]
Looks like the `ListBlock` data is still in the database and it's trying to import the new strings into it.

This might be a bug with Wagtail localize, I don't think we're currently copying the latest streamfield data into the translated pages when they are updated.

This is related to https://github.com/kaedroho/wagtail-localize/issues/20

**Comment by TheoChevalier** [comment]
Confirming this is fixed!
