### ISSUE TITLE
Change Thunderbird share links

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#597]
The share page links for Thunderbird probably need to be updated.

**Comment by mmmavis** [comment]
@alanmoo can you add more details to this ticket? e.g., what are the links currently? how they are shared / where do they appear?

**Comment by alanmoo** [comment]
If you make a transaction on staging, you’ll eventually get to the view asks you to share, as per my flow chart. You might have to copy the existing template into the thunderbird app for the override to kick in when appropriate

**Comment by alanmoo** [comment]
Grab links from https://donate.mofostaging.net/en-US/thunderbird/share/

**Comment by mmmavis** [comment]
What we have currently match what are on https://donate.mozilla.org/en-US/thunderbird/share/. 

Closing this ticket.
