### ISSUE TITLE
Legal: Upsell CTA button design concern

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#599]
>The grayed-out “No” button suggests it’s inactive, leaving the impression that the customer can only continue by selecting “Yes”. Suggest making both buttons blue.

The same comments go for the newsletter signup, though this is the most pressing one.

<img width="852" alt="image" src="https://user-images.githubusercontent.com/1682681/69460544-775fef80-0d42-11ea-85c1-aa8a22d60b5f.png">

**Comment by beccaklam** [comment]
@alanmoo So I talked to designers and they're okay with switching to the ghost button style:
![Screen Shot 2019-11-22 at 4 36 12 PM](https://user-images.githubusercontent.com/20977376/69553213-ce95d800-0f6d-11ea-98ba-363149e38682.png)

**Comment by beccaklam** [comment]
We have examples of the styling in the Foundation site's style guide: https://foundation.mozilla.org/en/style-guide/

**Comment by alanmoo** [comment]
This is good with Abigail.

**Comment by mmmavis** [comment]
Note to self : 

Update the docs to mention front end development & commands mentioned on a Slack thread.

**Comment by mmmavis** [comment]
@alanmoo 

> Dev note: This button styling should change on https://donate-wagtail.mofostaging.net/en-US/card/thank-you/ and https://donate-wagtail.mofostaging.net/en-US/thank-you/ (The former only appears after making a large one-time credit card donation.)

How do I make the two screens mentioned above show? They both redirect me back to root `https://donate-wagtail.mofostaging.net/en-US`.
