### ISSUE TITLE
Identify tasks for SSO integration and build out epic

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#616]
From [this bugzilla comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1598219#c2) reviewing this project from a security standpoint:

> As far as I know, folks working on Mozilla Developer Portal are also using Wagtail CMS, and they have implemented SSO login for it (see bug 1576801 for reference, and comments 14 and 18 in particular). If assistance is needed for this please reach out to them.

To close this issue, we should have a set of other issues created for this epic, including issues tracking coordination with MoCo.

**Comment by Pomax** [comment]
- integrate https://github.com/mozilla/mozilla-django-oidc
  - docs: https://mozilla-django-oidc.readthedocs.io/en/stable/installation.html
  - follow the approach taken by https://github.com/mdn/developer-portal
  - commit that adds oidc to the dev portal [is here](https://github.com/mdn/developer-portal/commit/96d3c736a730565803d6ef665cbab19c1da74831)
- make sure we have appropriate CSP set
- make sure we have appropriate host security (HSTS, etc) set

**Comment by Pomax** [comment]
Filed https://github.com/mozilla/donate-wagtail/issues/630 for work-tracking
