### ISSUE TITLE
Capture credit card type in Salesforce

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#620]
According to Abigail, we need to include the credit card type on the receipt emailed to donors. This means we need to send the card type to Basket, which, according to @stephaniemcv, is already set up to handle this.

We'll need to make sure we're passing it in for both one-time and monthly credit card transactions.

**Comment by alanmoo** [comment]
This work is around this function: https://github.com/mozilla/donate-wagtail/blob/7b60dd336f88428cad7f294e07382a3d8655294e/donate/payments/tasks.py#L38.

**Comment by Pomax** [comment]
I've added a `card_type` to our `CardPaymentView.get_transaction_details_for_session` function, which will take on the value "None" (that's a string, not the python `None`) if for some reason there is no credit card information in the transaction, or any of the values listed in https://developers.braintreepayments.com/reference/response/transaction/python#credit_card_details.card_type
