### ISSUE TITLE
Add support for excluding CMS pages from Pontoon

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#639]
Ideally we would be able to expose a page to a subset of locales, but for now we should at least be able to exclude some pages from the Pontoon integration altogether.

I expect some pages (campaign pages in particular) to be tied to campaigns only relevant for en-US, and we shouldn’t expose this content to other locales.

**Comment by TheoChevalier** [comment]
@kaedroho Do you see a way (even a hacky one) to exclude all campaign pages from localization?

I’d like to exclude them all until we find a proper way to handle this. This would allow us to localize the homepage and the FAQ while not exposing to translators all the noise from the campaign pages

**Comment by kaedroho** [comment]
It should be possible to do this by removing `TranslatablePageMixin` from the model but I wouldn't recommend this if you want them to be translatable in the future.

Alternatively, I could add some logic into the signal here https://github.com/wagtail/wagtail-localize-pontoon/blob/master/wagtail_localize_pontoon/models.py#L388-L395 to stop it auto-submitting this page type for now?

**Comment by TheoChevalier** [comment]
> It should be possible to do this by removing `TranslatablePageMixin` from the model but I wouldn't recommend this if you want them to be translatable in the future.
> 
> Alternatively, I could add some logic into the signal here https://github.com/wagtail/wagtail-localize-pontoon/blob/master/wagtail_localize_pontoon/models.py#L388-L395 to stop it auto-submitting this page type for now?

Indeed, we will want them translatable in the future. So if you could exclude them from wagtail_localize_pontoon for now, that would be rad!

Thanks!

**Comment by kaedroho** [comment]
Hi @theochevalier,

I've just pushed `wagtail-localize-pontoon` version `0.2.1` to PyPI now. You just need to install this version, then add the following line to the campaign page model:

```python
class CampaignPage(Page):
    ...

    submit_to_pontoon_on_publish = False
```

Thanks,
Karl

**Comment by TheoChevalier** [comment]
Awesome, thanks @kaedroho !

**Comment by TheoChevalier** [comment]
Fixed by https://github.com/mozilla/donate-wagtail/pull/1218
