### ISSUE TITLE
Set a better default country

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#642]
As noted by Anil during prod beta-testing, the country dropdown in the detail form defaults to USA for all locales.

While we can’t, and shouldn’t, guess everyone’s country, we should have a short list of default country associated to a locale that make more sense than USA. Associating a language and a country won’t work perfectly all the time, but there are a lot of cases where we can do better.

E.g.: `France` should be the default for `fr`. It will still be wrong for many `fr` users (Canada, Belgium, Switzerland, etc), but it will at least be right for the majority of people. While USA is wrong for (almost) everyone.

We could store a `LOCALE_COUNTRY_MAP ` at the bottom of https://github.com/mozilla/donate-wagtail/blob/master/donate/payments/constants.py

Default country is set here https://github.com/mozilla/donate-wagtail/blob/master/donate/payments/forms.py#L59

Initial list, based on country codes used by Salesforce:

```
LOCALE_COUNTRY_MAP = {
    'ast': 'ES',
    'az': 'AZ',
    'bn': 'BD',
    'bs': 'BA',
    'ca': 'ES',
    'cak': 'GT',
    'cs': 'CZ',
    'da': 'DK',
    'de': 'DE',
    'dsb': 'DE',
    'el': 'GR',
    'en-AU': 'AU',
    'en-CA': 'CA',
    'en-GB': 'GB',
    'en-IN': 'IN',
    'en-NZ': 'NZ',
    'en-US': 'US',
    'en-ZA': 'ZA',
    'es': 'ES',
    'es-AR': 'AR',
    'es-CL': 'CL',
    'es-MX': 'MX',
    'et': 'EE',
    'fi': 'FI',
    'fr': 'FR',
    'fy-NL': 'NL',
    'gu-IN': 'IN',
    'hi-IN': 'IN',
    'hr': 'HR',
    'hsb': 'DE',
    'hu': 'HU',
    'id': 'ID',
    'it': 'IT',
    'ja': 'JP',
    'ka': 'KZ',
    'kab': 'DZ',
    'ko': 'KR',
    'lo': 'LA',
    'lv': 'LV',
    'ml': 'IN',
    'mr': 'IN',
    'ms': 'MY',
    'nb-NO': 'NO',
    'nl': 'NL',
    'nn-NO': 'NO',
    'pa-IN': 'IN',
    'pl': 'PL',
    'pt-BR': 'BR',
    'pt-PT': 'PT',
    'ro': 'RO',
    'ru': 'RU',
    'sk': 'SK',
    'sl': 'SI',
    'sq': 'AL',
    'sv-SE': 'SE',
    'ta': 'IN',
    'te': 'IN',
    'th': 'TH',
    'tr': 'TR',
    'uk': 'UA',
    'zh-CN': 'CN',
    'zh-TW': 'TW'
}
```

Not sure if we should include `'he': 'IL'` as it may be sensitive?

**Comment by Pomax** [comment]
closing as out of date
