### ISSUE TITLE
~Non-EN~ donor info not passed to Salesforce

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#643]
On Nov 27th, around 10AM UTC, I made a donation of 1 RUB from give.mozilla.org/fr/

It’s showing up in Braintree, but according to @WillatMozFdn , Salesforce didn’t receive my info from Braintree, so I didn’t get any receipt.

See https://mozilla.slack.com/archives/CQZTGNSUC/p1574852528002300 for the email address used and the Braintree ID

I’m assuming this is broken for all non EN-US donors

**Comment by alanmoo** [comment]
Are you saying that to replicate this, I should change my browser language?

**Comment by TheoChevalier** [comment]
I don’t think so, just making a donation from anything else than the /en-US URL

**Comment by alanmoo** [comment]
I was able to successfully make a donation, but I do see this Sentry issue: [DONATE-PROD-8](https://sentry.prod.mozaws.net/operations/donate-prod/issues/6601834/)

I think there was another hiccup of some sort...

**Comment by alanmoo** [comment]
@cadecairos @patjouk any thoughts on this?

**Comment by TheoChevalier** [comment]
Tried again, and it worked this time for me as well

**Comment by cadecairos** [comment]
Not sure what happened the first time. I checked GA and I don't see the transaction in there either. According to [the code](https://github.com/mozilla/donate-wagtail/blob/b678f3527cae4bca3e6b2024f5c2ec5341adb1dc/donate/payments/views.py#L255) it should have been recorded if the transaction creates successfully.

**Comment by alanmoo** [comment]
Closing as we can’t reproduce
