### ISSUE TITLE
Implement settled transaction reconciliation with Salesforce

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#678]
Currently we have two pieces of data about transactions that don't make their way to Salesforce:

1.) Converted amount from a transaction in a foreign currency (the `settlement_amount` key in the transaction). This takes a few hours to be confirmed.
2.) Refunds. There's no webhook from Braintree to alert our site of a refund, so we don't have a way to pass it to Salesforce.

My instinct is that both of these can be solved in the same way: with some sort of task that checks transactions in the last X days for refunds or conversion amounts. Thus, making this an Epic, which we'll need to discuss and build out a plan for.

**Comment by cadecairos** [comment]
Closing, let's re-open when we need to get this done.
