### ISSUE TITLE
Add "no value selected" error state on landing page

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#691]
When landing on the homepage, attempting to choose a payment method without putting in a donation amount simply reloads the page with no visible error. Let's change that.

**Comment by cadecairos** [comment]
In the old donate, we always had a value selected by default, we should do the same here.

**Comment by Pomax** [comment]
As a not for whoever ends up doing this: this cannot be a `selected` attribute because of React, it needs to be a setState during componentDidMount, or preset state in the constructor.

**Comment by Pomax** [comment]
Based on the preset-from-url work, this should be easy to do.

**Comment by Pomax** [comment]
@WillatMozFdn I can put this back in, is there a specific amount (or nth button) that should preselected?

**Comment by WillatMozFdn** [comment]
Let's go with the 2nd lowest value -- it's (generally) the closest to the average donation.  Thanks!

**Comment by Pomax** [comment]
sweet, will do.
