### ISSUE TITLE
Migrate donors from Stripe to Braintree 

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#694]
Master tracking epic

**Comment by gideonthomas** [comment]
Not sure if this needs an epic. Basically just the ticket you've added + https://github.com/mozilla/donate-wagtail/issues/575 (which is already tracked in a different epic it seems).

**Comment by alanmoo** [comment]
Yeah, I realize that might be the case but I wanted to lay stuff out before consolidating.

**Comment by cadecairos** [comment]
Closing out this epic
