### ISSUE TITLE
Accessing Pontoon connector settings on staging throws a 500 error

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/donate-wagtail#708]
We can’t access the connector settings on staging: https://donate-wagtail.mofostaging.net/admin/localize/pontoon/ returns a 500.

Prod works fine. This may be related to the SSO work? The Sentry error hopefully tells us more

**Comment by TheoChevalier** [comment]
Looks like this has been fixed?

**Comment by cadecairos** [comment]
yes, this appears fixed.
