### ISSUE TITLE
RTL menu issues

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/donate-wagtail#714]
Small issue first, there is a hamburger menu on the left while using RTL https://donate-wagtail.mofostaging.net/he/ Should either be hidden or on the right.

![hebrew-1](https://user-images.githubusercontent.com/197334/72099359-754ff100-32ee-11ea-9dc5-96261ba177c2.png)

If you click it, this happens, which looks like a bug.
![hebrew-2](https://user-images.githubusercontent.com/197334/72099417-9284bf80-32ee-11ea-89d7-03ba2073ac0f.png)

**Comment by Pomax** [comment]
closing as out of date
