### ISSUE TITLE
custom value can have a value while showing as empty

### ISSUE THREAD

**Issue by Pomax** [mozilla/donate-wagtail#716]
STR
1. click custom field, fill in '2'
2. click one of the predefined amount buttons
3. click the currency label _next to_ to the custom value input

The custom value now shows as empty but the _actual_ stored value is still 2, and you can initial payment even though no value is visible.

This doesn't feel like a blocker, but I tried to see if there was an easy fix and right now there isn't, as far as I can tell.

**Comment by ragnarokatz** [comment]
@Pomax hello, I would like to work on this issue please.

**Comment by ragnarokatz** [comment]
@Pomax I have created a PR to address this issue. Please take a look at it when you have time, thanks.
