### ISSUE TITLE
Monthly card payments - set up Braintree support for multiple currencies

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#72]
In order to process monthly payments, Braintree [requires that](https://developers.braintreepayments.com/reference/request/subscription/create/python#specify-merchant-account):

> The specified merchant account must be in the same currency as the subscription plan, or any attempted subscription transactions will trigger a [validation error](https://developers.braintreepayments.com/reference/general/validation-errors/all/python#code-91923). If you want to use a merchant account with a different currency, you must create a new plan in the Control Panel with the indicated currency.

This means:

1. To accept monthly donations in all of the supported currencies, we will need to set up separate merchant accounts and plans for each currency.

2. You will need to talk to Braintree about getting access to all the currencies you want. By default they only provide the following:
    - AUD - Australian Dollar
    - BRL - Brazilian Real
    - CAD - Canadian Dollar
    - CHF - Swiss Franc
    - CZK - Czech Koruna
    - DKK - Danish Krone
    - EUR - Euro
    - GBP - British Pound
    - HKD - Hong Kong Dollar
    - HUF - Hungarian Forint
    - ILS - Israeli New Sheqel
    - INR - Indian Rupee
    - JPY - Japanese Yen
    - MXN - Mexican Peso
    - MYR - Malaysian Ringgit
    - NOK - Norwegian Krone
    - NZD - New Zealand Dollar
    - PHP - Philippine Peso
    - PLN - Polish Złoty
    - RUB - Russian Ruble
    - SEK - Swedish Krona
    - SGD - Singapore Dollar
    - THB - Thai Baht
    - TWD - New Taiwan Dollar
    - USD - United States Dollar

I don't _think_ that either of these should be an issue, but if you haven't already it is worth talking to them about it as early as possible.

**Comment by alanmoo** [comment]
I've reached out to Braintree about what we need to do for the other 25 currencies we support.
