### ISSUE TITLE
Braintree customer data expects first name, last name

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#73]
Braintree's customer data model expects a first name and last name for customers, but currently we [don't ask for these separately](https://redpen.io/jc07fc459ff5f3fe81). 

My current approach is not to pass name information at all to Braintree - but if we want to store this information there then we will need to look at options:

1. Ask for first name and last name separately.
2. Do some parsing to try and split this ourselves? (This will quickly fall foul of cultural variances).
3. Dump everything into "first name"?

I don't _think_ this has any implication for card verification - seems that only address and CVV is used for that, but that may also be a factor. Flagging as something we need to test before going live.

**Comment by TheoChevalier** [comment]
I think we should go with 1, and let people do the split. Our CRM will store First name and last name in two separate fields as well (assuming Braintree communicates the info to our Salesforce instance), and then we use the first name information when sending the donation receipt by email.

Related to that topic: https://www.w3.org/International/questions/qa-personal-names
