### ISSUE TITLE
Allow landing page as child of landing page

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#731]
There's an ask to allow the existing landing page template to be used for child pages, to work towards better A/B testing. My initial instinct is that we need to add it as a subpage type to itself, but I'm not sure if that opens up any cans of worms regarding fields the landing page model may or may not have, so that needs to be investigated too.

**Comment by Pomax** [comment]
If this is for A/B testing then there shouldn't be a need to make it a child of itself, should there? Instead, we'd want multiple root level pages, with an A/B test that picks and serves up "one of those" in a reliable fashion.

**Comment by alanmoo** [comment]
Yes, but also I think he wants to make "campaign" pages that have a normal layout, not the "banner" one.

**Comment by Pomax** [comment]
in that case I'd like to reserve any kind of thinking until the requirements can be made a little clearer. A/B testing and "we'd like campaigns that look like the landing page" are rather different things, so it's best to understand what is being requested before thinking too hard in a particular direction.

**Comment by Pomax** [comment]
Based on the explanation by @WillatMozFdn on Slack it sounds like the principal use-case is A/B testing, in which case we should be able to set up a more custom version of the Landing Page in which the bits that need changes can be  (iteratively) changed up.

**Comment by Pomax** [comment]
closing as out of date
