### ISSUE TITLE
Update Record type id in Tbird help form

### ISSUE THREAD

**Issue by stephaniemcv** [mozilla/donate-wagtail#743]
(Related to #696 ) I think I isolated what is causing my case creation bug in SFDC. I added the 18 character record type id instead of the 15 character to the form on https://thunderbird-donate.mofostaging.net/.

`<input type=hidden name="recordType" id="recordType" value="012P0000000SW6LIAW">`

should be 

`<input type=hidden name="recordType" id="recordType" value="012P0000000SW6L">`

**Comment by alanmoo** [comment]
The value is going to change based on the environment, so I think we need to store it in the CMS in order to close this.

**Comment by alanmoo** [comment]
Taken care of in #783
