### ISSUE TITLE
Move LandingPage/CampaignPage "project" field to env var

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#747]
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/1682681/72477297-2f4acf80-37bd-11ea-95b7-f2ebd6eefc36.png">

Since we've got two separate stacks spun up, having this field seems like a recipe for a mistake at some point in the future. I suspect it makes sense to move this from the model to the environment.

Thoughts @cadecairos @gideonthomas?

**Comment by gideonthomas** [comment]
If this is purely for Basket, then yeah, probably just put it in settings (since it'll work based on the env var) and rely on that value instead.

**Comment by alanmoo** [comment]
Ah, tie it to the Django configuration setting? Good call.

**Comment by jamilasnell** [comment]
Closing as the folks leading the discussion no longer work at Mofo.
