### ISSUE TITLE
Design maintenance page for downtime

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#754]
We need a simple page to host when the donate sites are down for maintenance. It might be useful to have a space to drop in the Mozilla or Thunderbird logo depending on the site.

**Comment by alanmoo** [comment]
@kristinashu

**Comment by kristinashu** [comment]
Do you mean when https://donate.mozilla.org/ page is down? 
<img width="887" alt="image" src="https://user-images.githubusercontent.com/1068783/72566573-e81a1880-3868-11ea-80a2-f596dc9b79ed.png">

Can we keep the header, footer, grey background and then just add some copy in the middle? If so then we'll mock that up. Do you have any copy suggestions?

**Comment by alanmoo** [comment]
Well, yes, but the wagtail site vs the old site in the screenshot.

**Comment by alanmoo** [comment]
"Thanks for your interest! We're down for maintenance right now but should be back online soon, please check back later!" ?

**Comment by kristinashu** [comment]
Ok here's a quick comp, is it too basic?

![Landing Page Maintenance@2x](https://user-images.githubusercontent.com/1068783/72568860-eef75a00-386d-11ea-9068-0917a35e5b7f.jpg)


cc @beccaklam for R+ and cc @mmmavis since I think she'll be working on it.

**Comment by alanmoo** [comment]
Fine by me, unless you want to center the block of content (but still be left justified).

-Alan Mooiman,
Mozilla Foundation Engineering Manager
Eastern Standard Time (USA) UTC-5

**Comment by xmatthewx** [comment]
Let's add a link to somewhere on the foundation page. Maybe "Signup to to hear the latest news or checkout our  campaigns."

**Comment by kristinashu** [comment]
Opened an implementation ticket here https://github.com/mozilla/donate-wagtail/issues/760
