### ISSUE TITLE
Create hardcoded ways-to-give page

### ISSUE THREAD

**Issue by alanmoo** [mozilla/donate-wagtail#756]
We need a page that has all the banking information on it so that we can embed account numbers as fixed values across translations. (cc @TheoChevalier)

Let's create a 'ways-to-give' template is styled the same as the content page, but with only content that's hardcoded in the template.

Basically, it'll be the content from [this page](https://donate.mozilla.org/en-US/ways-to-give) under the existing black content header. Quick browser mock-up below

<img width="918" alt="image" src="https://user-images.githubusercontent.com/1682681/72622649-a98c6880-3911-11ea-8fb2-942ff4fbbcd8.png">

**Comment by mmmavis** [comment]
@alanmoo I'm assuming both the "Donate Now" link and "Go to this link" go to `/?utm_content=Ways_to_Give`?

**Comment by alanmoo** [comment]
Sounds good to me.
