### ISSUE TITLE
Maintenance page for downtime

### ISSUE THREAD

**Issue by kristinashu** [mozilla/donate-wagtail#760]
Based on - Design maintenance page for downtime #754 

We need a simple page to host when the donate sites are down for maintenance. It might be useful to have a space to drop in the Mozilla or Thunderbird logo depending on the site.

### Copy
> Thanks for your interest! We're down for maintenance right now but should be back online soon, please check back later!

### Comp
![Landing Page Maintenance@2x](https://user-images.githubusercontent.com/1068783/72568860-eef75a00-386d-11ea-9068-0917a35e5b7f.jpg)

cc @alanmoo

**Comment by mmmavis** [comment]
I can build this page but it'll require DevOps' help to set up the Travis task & S3 bucket etc for this page to show during downtime. I'll give DevOp's a ping when I'm done with the page code.

**Comment by mmmavis** [comment]
@alanmoo wondering if we can simplify nav and footer so they don't have "interactive" pieces like toggleable navs and newsletter signup? This page will have to be 100% hardcoded so we won't be able to re-use any Django template or JS code that we set up for the donate stack. We _could_ manually copy the code over to build a maintenance page like the mockup but this will make the maintenance page very high maintenance 🤣 as we will end up having two copies of code that we need to update to make sure they always match. (It's such a pain to keep Foundation site's maintenance page to look align with the main site 😂)

**Comment by mmmavis** [comment]
PR for the maintenance page itself is ready for review. I basically just copied code from the compiled main.css, main.js, and HTML source code from the main site + added minimal changes to make the page look and function the way we want (including toggeable nav and newsletter sign-up). We can discuss in the PR https://github.com/mozilla/donate-wagtail/pull/762 regarding how we wanna modify the code to address the code & asset maintenance problem.
