### ISSUE TITLE
Remove "ALL" currency from site

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/donate-wagtail#770]
Braintree does not support Albanian Leks. Let's remove it as a currency option from the site.

**Comment by TheoChevalier** [comment]
We will need to remove this line, too https://github.com/mozilla/donate-wagtail/blob/master/donate/payments/constants.py#L1074

**Comment by Pomax** [comment]
If ALL is not supported, should we remove SQ as supported language, too, or should we instead default SQ to a different currency?
