### ISSUE TITLE
Error page templates and styles

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#78]
We will need to update the `404` and `500` templates to be consistent with the rest of the site, and to present some meaningful information to the user.

On a related note I notice that any invalid URL on the current site (e.g., https://donate.mozilla.org/foooo) redirects to the home page. Is this behaviour you want to replicate @alanmoo ? I feel like it might have SEO implications (but not an expert in this) - but would imagine this is a deliberate decision?

**Comment by alanmoo** [comment]
It was a deliberate decision when we didn't have a CMS to manage custom pages. Let's do the right thing now, and let an invalid URL 404.

**Comment by nicklee** [comment]
Basic 404 page here:
https://github.com/mozilla/donate-wagtail/pull/95

We could do with some content to go on this page.

**Comment by nicklee** [comment]
@beccaklam @alanmoo we could do with a design and/or content for this template.

We could potentially base it on the MoFo existing 404 page here?
https://foundation.mozilla.org/en/24424224/

**Comment by beccaklam** [comment]
Hi @nicklee yes let's just base it on the existing MoFo 404 page but minus the donate footer?

**Comment by nicklee** [comment]
Styling for 404 done, can be previewed here:
https://donate-wagtail.mofostaging.net/en-US/fdsdfdfd/

**Comment by nicklee** [comment]
https://github.com/mozilla/donate-wagtail/pull/95

**Comment by beccaklam** [comment]
The 404 portion of the page looks good! The footer has too much padding though, it should match the main donate page.

- [ ] Remove extra padding from footer

**Current:**
![image](https://user-images.githubusercontent.com/20977376/66214869-81456a80-e690-11e9-8729-9f6e94732451.png)

**Comment by nicklee** [comment]
Oops, not sure how I missed that! Thanks for spotting, fix applied in https://github.com/mozilla/donate-wagtail/pull/411

**Comment by cadecairos** [comment]
This was resolved, as far as I can tell.
