### ISSUE TITLE
Add a "cuts the mustard" check and load a dom4 shim if a browser doesn't

### ISSUE THREAD

**Issue by Pomax** [mozilla/donate-wagtail#795]
We're relying on some JS APIs that are not universally supported - we should add a "Startup" check to see if the browser indeed supports the things that we rely on, so that we can make sure to either selectively polyfill the things that are missing, or outright load a dom4 shim that just makes sure everything we need is going to work as expected.

**Comment by tagniam** [comment]
Hey @Pomax what JS APIs are you referring to? Interested in working on this issue

**Comment by jamilasnell** [comment]
Closing this as it is obsolete
