### ISSUE TITLE
Investigate the cause of MoFo text present on MZLA paypal pages

### ISSUE THREAD

**Issue by cadecairos** [mozilla/donate-wagtail#818]
We're seeing the text "Mozilla Foundation" on paypal pages when giving to Thunderbird, which shouldn't be the case.

Let's double check the Merchant Account IDs associated with Thunderbird production, and continue investigating the cause of this.

Estimating at 2, but It could change given what we learn

**Comment by cadecairos** [comment]
@gideonthomas I can confirm that `thunderbird-donate production` is using only MZLA labelled merchant accounts.

**Comment by cadecairos** [comment]
Also, The MZLA paypal accounts are only associated with MZLA labelled BT MIDs

**Comment by cadecairos** [comment]
Based on what I can see in the macropayments MZLA Paypal, there's no instance of "Mozilla Foundation". This leads me to believe that the integration that Braintree has with paypal is hard-coded to display the name of the business associated with the Braintree account. 

@gideonthomas @WillatMozFdn we will need to bring this up with Braintree. I have a meeting with Josh and Dan next week on Wednesday and can address this issue (probably). I could also email Dan now to bring up this issue.

**Comment by gideonthomas** [comment]
thanks for following up on this Chris!

**Comment by cadecairos** [comment]
Closing this in favour of #884
