### ISSUE TITLE
Regenerate the PayPal button when donation currency changes

### ISSUE THREAD

**Issue by cadecairos** [mozilla/donate-wagtail#819]
In #807 we added the merchant account ID to the paypal initialization code on the client-side. This fixed the issue with Billing agreements for MZLA being accidentally owned by MoFo (and thus failing).

We must now update this code so that when the currency and amount changes, we regenerate this button so it's properly associated with the correct merchant account.

For example (MIDs are not real):

1. Page loads, USD is the selected currency, so Paypal is initialized with the `MZLA_instant` merchant account ID.
2. The donor selects Canadian dollar as the donation currency
3. We regenerate the PayPal button so that it's now linked to the `MZLA_CAD` merchant account

I'm not entirely sure what the threshold for macro VS micro payments is, but we'll also need to expose the micropayments MIDs and switch to them when the donation amount changes.

**Comment by cadecairos** [comment]
need to hear back from Dan@Paypal

**Comment by WillatMozFdn** [comment]
@cadecairos is this one still outstanding -- ??

**Comment by Pomax** [comment]
closing as out of date
