### ISSUE TITLE
Import conversion amount into SFNP from Braintree

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate-wagtail#842]
With the switch to Braintree, we seem to have lost the "converted-to-dollars" amounts with each donation in Salesforce.com (field is Conversion_Amount__c in SFDC) -- which is a blocker to analyzing results from any fundraising campaign.  This needs to be restored.

**Comment by benhohner** [comment]
Will investigate Cinchy for pulling data from a webhook after the fact, since this field only comes in when payments are reconciled daily

**Comment by jamilasnell** [comment]
Data team already has this issue in their JIRA. Jam will ping Jackie to see if this is true or not.

**Comment by jackielu** [comment]
This process is actually currently covered by a manual Braintree -> Cinchy CSV import process, and is in our backlog for automation as part of Braintree Integration, here https://mozilla-hub.atlassian.net/browse/MFD-29

cc: @GeoDan87
