### ISSUE TITLE
Ability to clone existing default landing/donate page in Wagtail

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate-wagtail#843]
Currently, we can make campaign landing/donate pages using a large banner image across the top, and verbage on the left (i.e. https://donate.mozilla.org/feb2020a/ ).  However, our default page ( https://donate.mozilla.org/ ) is a different style and layout ... so with any A/B test, we'll never know if the change was due to different words/images on the new page, or a different layout.

So we need the ability to clone the template/layout of the current default page, and create new landing/donate pages using that same structure BUT adding in new headline text, lead text, image, intro, and donation amount overrides.

**Comment by TheoChevalier** [comment]
Implementation note: please make sure to exclude those from localization by following the instructions here: https://github.com/mozilla/donate-wagtail/issues/639#issuecomment-588270983

We can’t have these test pages end up in Pontoon

**Comment by cadecairos** [comment]
Chucking in the icebox while the wagtail-localize refactor project happens

**Comment by KalobTaulien** [comment]
Cloning a page now works with wagtail-localize. I'm going to close this ticket.
