### ISSUE TITLE
Update Salesforce when a donation is refunded or monthly donation is cancelled

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate-wagtail#845]
For various reasons, we frequently need to refund donations out of Braintree (both credit cards and paypal) -- obvious fraud, disputes, donor mistakes, etc.  And donors also frequently cancel their recurring donations with us (just the nature of donor churn).

However, currently there is no mechanism that updates Salesforce.com when a refund happens or recurring donation is cancelled, so the transactions stay on our books, and the donor's status remains as "recurring" when it should not be.  This causes customer service issues, problems with reconciling income with accounting, inaccurate reporting as to the number of monthly donors and income from them, and problems in email targeting (we're incorrectly excluding past recurring donors who might be willing to give a one-time gift).

**Comment by benhohner** [comment]
Do an investigation to make action plan

**Comment by jamilasnell** [comment]
@WillatMozFdn Is this problem still relevant with our move to SFDC Non-Profit?

**Comment by WillatMozFdn** [comment]
yes, definitely still relevant.  Steph McV _may_ have this on her planning roadmap as a future enhancement, but I'm not sure when it's targeted for implementation.

**Comment by jamilasnell** [comment]
Assigning this to you @benhohner so that we can figure out when this needs to be planned into our sprints

**Comment by benhohner** [comment]
cinchy working on a solution, will reopen if problem still exists
