### ISSUE TITLE
Enable ApplePay, GooglePay, and SamsungPay in Braintree

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate-wagtail#846]
One of the primary reasons for switching to Braintree from Stripe was Braintree's ability to accept additional payment methods that our donors have been asking for.

Flipping the switch to accept ApplePay, GooglePay and Samsung pay is easy to do in Braintree, but this will also require back-end work on our side (scope unknown to me at this time).

This issue is a placeholder for that work.  End goal is those three payment systems enabled and available to donors on our donate.mozilla.org page.

**Comment by tagniam** [comment]
Hi @WillatMozFdn, interested in working on this issue. Is it possible to gain access to the braintree credentials in order to work on this feature?

**Comment by cadecairos** [comment]
Hi @tagniam, Thanks for your interest in this issue. There's a lot of work involved in this implementation for our team and so this isn't really a good candidate for external contribution at this time. If you'd still like to contribute, I would suggest looking at the issue list for smaller bug fixes.

Regarding Braintree, you can [set up your own sandbox Braintree account](https://sandbox.braintreegateway.com/) and configure a dev environment [based on the documentation here](https://github.com/mozilla/donate-wagtail#braintree-configuration)

**Comment by phildexter** [comment]
Current sprint target - approach documented on this ticket.

**Comment by KalobTaulien** [comment]
https://docs.google.com/document/d/1Gdgsx8DhH1FV_PE55CyGC9eJtFJ3VKXziJEeaUzXbzE/edit

**Comment by cadecairos** [comment]
I've been asked to open a support request with braintree to get us started working with Apple Pay and Google Pay. I'm not sure what's going to come out of it.
