### ISSUE TITLE
Semi-urgent: Update MoFo and T-Bird donate websites to reflect our inability to process checks right now.

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate-wagtail#889]
1. For MoFo, two URLs:

https://donate.mozilla.org/en-US/faq/
https://donate.mozilla.org/en-US/ways-to-give/#check

.... we need to add the following update, right under the larger-font section header:

<font color=red>UPDATE March 19, 2020:</font> Please note that due to the "shelter in place" order recently implemented for the San Francisco Bay Area, processing and acknowledgment of check donations to the Mozilla Foundation will be indefinitely delayed.  Rather than sending us a check, please consider an <link https://donate.mozilla.org>online donation</link> instead.

2. For Thunderbird/MZLA, just one:

https://give.thunderbird.net/en-US/ways-to-give/#check

<font color=red>UPDATE March 19, 2020:</font> Please note that due to the "shelter in place" order recently implemented for the San Francisco Bay Area, processing and acknowledgment of check donations to Thunderbird/MZLA Technologies will be indefinitely delayed.  Rather than sending us a check, please consider an <link https://give.thunderbird.net>online donation</link> instead.

Once we can actually get into the office (that timing is unknown at this point), we will file another bug to remove these statements.  Thanks!

**Comment by TheoChevalier** [comment]
Quick note, due to https://github.com/mozilla/donate-wagtail/issues/852, we won’t be able to update https://donate.mozilla.org/de/faq/ and https://donate.mozilla.org/fr/faq/ at all, not even with English content.

For the ways to give page, we can properly localize it in all languages, because the content is not stored in the CMS

**Comment by WillatMozFdn** [comment]
@TheoChevalier thanks for the update!  Primary goal here is to get it out just for EN; we get very few checks from DE or FR sources anyway, and even when we do, processing is horribly delayed on those anyway.  So if we can get that note translated and up on the FR and DE pages, great, if not, I don't think it will make a big difference at all.

**Comment by WillatMozFdn** [comment]
Update: since shelter in place just went statewide this morning, for both statements above let's replace "the San Francisco Bay Area" with "California".  Thanks.

**Comment by WillatMozFdn** [comment]
Update 3/27 @Pomax ... I was able to update the FAQ page for Mozilla, as it's in Wagtail and easily edited by mere mortals with the right permissions.  We still need to update the "Ways To Give" pages for both MoFo and T-bird, though.

**Comment by Pomax** [comment]
@WillatMozFdn looking at the page, does it make sense to keep the original text? Or should we comment that off so it doesn't show up for now?

![image](https://user-images.githubusercontent.com/177243/77961705-18c9f580-728f-11ea-879f-49a9cf00702b.png)

**Comment by WillatMozFdn** [comment]
Thanks @Pomax  ... yeah, let's comment it off.  (For both Tbird and Mozilla pages).  I'll do the same for the FAQ page, which I can control from here.  Thanks!

**Comment by Pomax** [comment]
PR up with the changes.

**Comment by Pomax** [comment]
landed.
