### ISSUE TITLE
More flexible handling of currency symbols

### ISSUE THREAD

**Issue by solarissmoke** [mozilla/donate-wagtail#93]
From discussion on #82:

> A lot of locales will want the currency symbol to be displayed after the value, would it be possible to add a conditional for that? Maybe storing that preference in settings?
> 
> To give you an idea: https://transvision.mozfr.org/string/?entity=mozilla_org/mozorg/home/index-quantum.lang:3fe118b0ed61665a878f4a81ef2d3357&repo=mozilla_org

**Comment by TheoChevalier** [comment]
Actually, using this would probably be a much cleaner and more reliable way of handling this issue https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat/formatToParts#Examples

Looking for the array index of the currency symbol should let you know where to display it in the UI.

If this works, then we would not need to store and maintain that information

**Comment by solarissmoke** [comment]
I will look into this today. I think we also need to render this stuff correctly in the templates, and am looking at [moneyed](https://github.com/limist/py-moneyed/) to help us do that. In combination, that plus the number formatting API in JS should provide everything we need.

**Comment by solarissmoke** [comment]
This should now all be working - let's address any edge cases in separate tickets.
