### ISSUE TITLE
Add instruction to SEPA/BACS information on donate website

### ISSUE THREAD

**Issue by WillatMozFdn** [mozilla/donate-wagtail#935]
We've received more clarity from Silicon Valley Bank as to our processing fees for SEPA/BACS wire transfers, and they're considerably higher than we would want, especially for smaller donations.  So we're going to try and shift those smaller donations over to payment methods with lower fees.

1. On https://donate.mozilla.org/en-US/ways-to-give/#wire ... just after (and as part of the same paragraph) "We accept donations in Euros through Single European Payment Area (SEPA) transfer, and British Pounds through BACS transfer." ... we need to add a new sentence: "Please note that for smaller (under 10 EUR or equivalent) donations, **and especially for donations under 5 EUR or equivalent,** we request that you donate via credit card or PayPal to help reduce Mozilla’s processing fees."

2. (similar, but worded a bit differently) On https://give.thunderbird.net/en-US/ways-to-give/#wire ... after "We accept contributions in Euros through Single European Payment Area (SEPA) transfer, and British Pounds through BACS transfer." and in the same paragraph, add "Please note that for smaller (under 10 EUR or equivalent) contributions, **and especially for contributions under 5 EUR or equivalent,** we request that you contribute via credit card or PayPal to help reduce our processing fees."

Theo is looped in for localization.  Thanks!

**Comment by phildexter** [comment]
Need to check with @TheoChevalier in case there are localisation considerations on this ticket.

**Comment by TheoChevalier** [comment]
Hey @phildexter, here’s what the process could look like for this ticket.

Engineering work required: 
- adding the two strings from the first comment to the templates.
- asking Will for a review to check it meets his needs
- asking me for a review to make sure everything is okay from a localization standpoint

Then the localization process, once this is approved & merged:

- I run the extract command documented here https://github.com/mozilla/donate-wagtail#exposing-latest-source-strings then everything from here is automated.
- Strings get automatically picked up by [Pontoon](https://pontoon.mozilla.org/projects/mozilla-donate-website/)
- Volunteers translate/review in Pontoon
- Translations are committed back to the [donate-l10n repository](https://github.com/mozilla-l10n/donate-l10n)
- Translations are automatically deployed at the next code deploy

**Comment by Pomax** [comment]
Also, should that still read "Mozilla" at the end?

**Comment by WillatMozFdn** [comment]
thanks, good catch on both, @Pomax !  Editing accordingly above ... yes, for Thunderbird we should use "contributions" in both places, and not say Mozilla.

**Comment by Pomax** [comment]
sweet, made those changes. I've also made the general donate one not start with "Please" since the next paragraph also starts with "Please". PR incoming.

**Comment by Pomax** [comment]
@WillatMozFdn 

- donate url: https://donate-wagta-sepa-bacs--2gi5av.herokuapp.com/en-US/ways-to-give/#wire
- tb url: https://thunderbird-sepa-bacs-i-8ply8w.herokuapp.com/en-US/ways-to-give/#wire
