### ISSUE TITLE
Reduce complexity of donate_form.html

### ISSUE THREAD

**Issue by cadecairos** [mozilla/donate-wagtail#970]
There's an opportunity to reduce the complexity and repetition of the [donate_form.html](https://github.com/mozilla/donate-wagtail/blob/d29a3e5284b16ea573ad4d139907a0c9aad67d59/donate/templates/fragments/donate_form.html) file.

Right now it's got a lot of duplicate code declaring the single and monthly forms, which has led to at least two bugs so far: #968 and #936

We should try to unify this code into a template tag we can reuse here.

**Comment by jamilasnell** [comment]
We are closing this out.
